// lib/questions_literature.dart
// 500 LITERATURE-IN-ENGLISH questions – WAEC/JAMB/NECO/UTME style.
// Topics: Literary Terms | Prose | Drama | Poetry | African & Non-African Texts.
// Tricks: author-text matching, character identification, thematic analysis, poetic devices.

final List<Map<String, dynamic>> literatureQuestions = [
// ============================================================
// SECTION 1: LITERARY TERMS & DEVICES (Q1–Q100)
// ============================================================
{'s':'Literature','y':2000,'q':'A comparison using 'like' or 'as' is a:','o':['Simile','Metaphor','Personification','Hyperbole'],'ci':0,'e':'Simile uses 'like' or 'as' (e.g., 'brave as a lion').'},
{'s':'Literature','y':2001,'q':'A direct comparison without 'like' or 'as' is a:','o':['Metaphor','Simile','Alliteration','Onomatopoeia'],'ci':0,'e':'Metaphor states that one thing is another (e.g., 'time is a thief').'},
{'s':'Literature','y':2002,'q':'Giving human qualities to inanimate objects is called:','o':['Personification','Simile','Metaphor','Allegory'],'ci':0,'e':'Personification (e.g., 'the wind whispered').'},
{'s':'Literature','y':2003,'q':'An extreme exaggeration used for effect is:','o':['Hyperbole','Understatement','Irony','Satire'],'ci':0,'e':'Hyperbole (e.g., 'I have told you a million times').'},
{'s':'Literature','y':2004,'q':'The use of words that imitate sounds is:','o':['Onomatopoeia','Alliteration','Assonance','Consonance'],'ci':0,'e':'Onomatopoeia (e.g., 'buzz', 'hiss').'},
{'s':'Literature','y':2005,'q':'The repetition of initial consonant sounds is:','o':['Alliteration','Assonance','Consonance','Rhyme'],'ci':0,'e':'Alliteration (e.g., 'Peter Piper picked').'},
{'s':'Literature','y':2006,'q':'A story with a moral or deeper meaning is an:','o':['Allegory','Epic','Ballad','Ode'],'ci':0,'e':'Allegory is a symbolic narrative (e.g., 'Pilgrim's Progress').'},
{'s':'Literature','y':2007,'q':'A short, witty saying that expresses a general truth is an:','o':['Aphorism','Epigram','Paradox','Euphemism'],'ci':0,'e':'Aphorism (e.g., 'A penny saved is a penny earned').'},
{'s':'Literature','y':2008,'q':'The use of contradictory terms together is an:','o':['Oxymoron','Paradox','Irony','Satire'],'ci':0,'e':'Oxymoron (e.g., 'deafening silence', 'bittersweet').'},
{'s':'Literature','y':2009,'q':'A statement that appears contradictory but reveals a truth is a:','o':['Paradox','Oxymoron','Irony','Sarcasm'],'ci':0,'e':'Paradox (e.g., 'less is more').'},
{'s':'Literature','y':2010,'q':'The opposite of what is said or expected is:','o':['Irony','Satire','Hyperbole','Euphemism'],'ci':0,'e':'Irony (verbal, situational, dramatic).'},
{'s':'Literature','y':2011,'q':'A mild or indirect expression used in place of a harsh one is:','o':['Euphemism','Oxymoron','Paradox','Simile'],'ci':0,'e':'Euphemism (e.g., 'passed away' for 'died').'},
{'s':'Literature','y':2012,'q':'A character who opposes the protagonist is the:','o':['Antagonist','Protagonist','Foil','Narrator'],'ci':0,'e':'Antagonist is the opposing force.'},
{'s':'Literature','y':2013,'q':'The main character in a literary work is the:','o':['Protagonist','Antagonist','Foil','Confidant'],'ci':0,'e':'Protagonist is the central character.'},
{'s':'Literature','y':2014,'q':'A character who contrasts with the protagonist to highlight traits is a:','o':['Foil','Antagonist','Protagonist','Narrator'],'ci':0,'e':'Foil (e.g., Laertes to Hamlet).'},
{'s':'Literature','y':2015,'q':'The sequence of events in a story is the:','o':['Plot','Theme','Setting','Characterisation'],'ci':0,'e':'Plot is the storyline.'},
{'s':'Literature','y':2016,'q':'The central idea or underlying message of a work is the:','o':['Theme','Plot','Setting','Moral'],'ci':0,'e':'Theme is the main idea.'},
{'s':'Literature','y':2017,'q':'The time and place where a story occurs is the:','o':['Setting','Theme','Plot','Atmosphere'],'ci':0,'e':'Setting includes location, time, environment.'},
{'s':'Literature','y':2018,'q':'The feeling or mood created in the reader is the:','o':['Atmosphere','Tone','Theme','Plot'],'ci':0,'e':'Atmosphere is the emotional mood.'},
{'s':'Literature','y':2019,'q':'The author's attitude toward the subject or audience is the:','o':['Tone','Atmosphere','Theme','Style'],'ci':0,'e':'Tone reflects the writer's feelings.'},
{'s':'Literature','y':2020,'q':'The way an author develops a character is called:','o':['Characterisation','Plot','Setting','Theme'],'ci':0,'e':'Characterisation is the method of character development.'},
{'s':'Literature','y':2021,'q':'A character who does not change throughout the story is:','o':['Static','Dynamic','Round','Flat'],'ci':0,'e':'Static character remains the same.'},
{'s':'Literature','y':2022,'q':'A character who changes or evolves is:','o':['Dynamic','Static','Flat','Stock'],'ci':0,'e':'Dynamic character undergoes significant change.'},
{'s':'Literature','y':2023,'q':'A character with only one or two traits is:','o':['Flat','Round','Static','Dynamic'],'ci':0,'e':'Flat character is one-dimensional.'},
{'s':'Literature','y':2024,'q':'A fully developed, complex character is:','o':['Round','Flat','Static','Stock'],'ci':0,'e':'Round character has depth and complexity.'},
{'s':'Literature','y':2025,'q':'The struggle between opposing forces in a story is the:','o':['Conflict','Plot','Theme','Setting'],'ci':0,'e':'Conflict drives the narrative.'},
{'s':'Literature','y':2026,'q':'A story told from the 'I' perspective is:','o':['First-person narration','Third-person omniscient','Second-person','Third-person limited'],'ci':0,'e':'First-person uses 'I' or 'we'.'},
{'s':'Literature','y':2000,'q':'A narrator who knows all characters' thoughts is:','o':['Omniscient','Limited omniscient','First-person','Objective'],'ci':0,'e':'Omniscient narrator is all-knowing.'},
{'s':'Literature','y':2001,'q':'A long narrative poem about heroic deeds is an:','o':['Epic','Lyric','Ballad','Ode'],'ci':0,'e':'Epic (e.g., 'The Iliad').'},
{'s':'Literature','y':2002,'q':'A short poem expressing personal emotion is a:','o':['Lyric','Epic','Ballad','Drama'],'ci':0,'e':'Lyric is subjective and musical.'},
{'s':'Literature','y':2003,'q':'A poem that tells a story, often with a refrain, is a:','o':['Ballad','Lyric','Ode','Sonnet'],'ci':0,'e':'Ballad is narrative and often musical.'},
{'s':'Literature','y':2004,'q':'A 14-line poem in iambic pentameter is a:','o':['Sonnet','Ode','Ballad','Epic'],'ci':0,'e':'Sonnet (Shakespearean or Petrarchan).'},
{'s':'Literature','y':2005,'q':'A speech by a single character alone on stage is a:','o':['Soliloquy','Aside','Monologue','Dialogue'],'ci':0,'e':'Soliloquy reveals inner thoughts.'},
{'s':'Literature','y':2006,'q':'A brief comment by a character to the audience, not heard by others, is an:','o':['Aside','Soliloquy','Monologue','Dialogue'],'ci':0,'e':'Aside is a short remark to the audience.'},
{'s':'Literature','y':2007,'q':'A long speech by one character to others is a:','o':['Monologue','Soliloquy','Aside','Dialogue'],'ci':0,'e':'Monologue is a speech to other characters.'},
{'s':'Literature','y':2008,'q':'A humorous imitation of a literary work is a:','o':['Parody','Satire','Irony','Burlesque'],'ci':0,'e':'Parody mimics for comic effect.'},
{'s':'Literature','y':2009,'q':'A work that uses humor, irony, or ridicule to expose folly is:','o':['Satire','Parody','Tragedy','Comedy'],'ci':0,'e':'Satire criticises vices and follies.'},
{'s':'Literature','y':2010,'q':'A serious drama with an unhappy ending is a:','o':['Tragedy','Comedy','Satire','Farce'],'ci':0,'e':'Tragedy involves suffering and downfall.'},
{'s':'Literature','y':2011,'q':'A light, humorous play is a:','o':['Comedy','Tragedy','Satire','Drama'],'ci':0,'e':'Comedy is light and often ends happily.'},
{'s':'Literature','y':2012,'q':'A play with exaggerated situations for comedy is a:','o':['Farce','Tragedy','Satire','Comedy of manners'],'ci':0,'e':'Farce is highly exaggerated slapstick comedy.'},
{'s':'Literature','y':2013,'q':'The central character in a tragedy who has a flaw is the:','o':['Tragic hero','Protagonist','Antagonist','Foil'],'ci':0,'e':'Tragic hero has a fatal flaw (hamartia).'},
{'s':'Literature','y':2014,'q':'The moment of greatest tension in a plot is the:','o':['Climax','Denouement','Exposition','Rising action'],'ci':0,'e':'Climax is the turning point.'},
{'s':'Literature','y':2015,'q':'The part of a plot that ties up loose ends is the:','o':['Denouement','Exposition','Climax','Falling action'],'ci':0,'e':'Denouement is the resolution.'},
{'s':'Literature','y':2016,'q':'The introduction of characters, setting, and background is the:','o':['Exposition','Rising action','Climax','Denouement'],'ci':0,'e':'Exposition sets up the story.'},
{'s':'Literature','y':2017,'q':'Events leading to the climax are the:','o':['Rising action','Falling action','Exposition','Denouement'],'ci':0,'e':'Rising action builds suspense.'},
{'s':'Literature','y':2018,'q':'Events after the climax are the:','o':['Falling action','Rising action','Exposition','Climax'],'ci':0,'e':'Falling action leads to resolution.'},
{'s':'Literature','y':2019,'q':'An indication of future events in a story is:','o':['Foreshadowing','Flashback','In medias res','Epiphany'],'ci':0,'e':'Foreshadowing hints at later developments.'},
{'s':'Literature','y':2020,'q':'A return to an earlier time in a narrative is a:','o':['Flashback','Foreshadowing','In medias res','Epilogue'],'ci':0,'e':'Flashback interrupts the present to show past events.'},
{'s':'Literature','y':2021,'q':'A story that begins in the middle of the action is:','o':['In medias res','Flashback','Foreshadowing','Epilogue'],'ci':0,'e':'In medias res starts in the middle.'},
{'s':'Literature','y':2022,'q':'A character's moment of sudden realisation is an:','o':['Epiphany','Climax','Denouement','Exposition'],'ci':0,'e':'Epiphany is a sudden insight.'},
{'s':'Literature','y':2023,'q':'The pattern of stressed and unstressed syllables in a line is:','o':['Meter','Rhyme','Rhythm','Alliteration'],'ci':0,'e':'Meter is the rhythmic structure.'},
{'s':'Literature','y':2024,'q':'The repetition of vowel sounds in a line is:','o':['Assonance','Consonance','Alliteration','Onomatopoeia'],'ci':0,'e':'Assonance (e.g., 'fleet feet sweep').'},
{'s':'Literature','y':2025,'q':'The repetition of consonant sounds in nearby words is:','o':['Consonance','Assonance','Alliteration','Rhyme'],'ci':0,'e':'Consonance (e.g., 'pitter patter').'},
{'s':'Literature','y':2026,'q':'A pause within a line of poetry is a:','o':['Caesura','Enjambment','Stanza','Couplet'],'ci':0,'e':'Caesura is a strong pause.'},
{'s':'Literature','y':2000,'q':'When a line runs over to the next line without punctuation, it is:','o':['Enjambment','Caesura','Couplet','Blank verse'],'ci':0,'e':'Enjambment continues meaning across lines.'},
{'s':'Literature','y':2001,'q':'A group of lines in a poem is a:','o':['Stanza','Couplet','Verse','Paragraph'],'ci':0,'e':'Stanza is a poetic paragraph.'},
{'s':'Literature','y':2002,'q':'A pair of rhyming lines in iambic pentameter is a:','o':['Couplet','Quatrain','Sestet','Octave'],'ci':0,'e':'Couplet is two consecutive rhyming lines.'},
{'s':'Literature','y':2003,'q':'A four-line stanza is a:','o':['Quatrain','Couplet','Sestet','Octave'],'ci':0,'e':'Quatrain has four lines.'},
{'s':'Literature','y':2004,'q':'A poem with no regular meter or rhyme is:','o':['Free verse','Blank verse','Sonnet','Ballad'],'ci':0,'e':'Free verse has no fixed structure.'},
{'s':'Literature','y':2005,'q':'Poetry written in unrhymed iambic pentameter is:','o':['Blank verse','Free verse','Sonnet','Ode'],'ci':0,'e':'Blank verse (e.g., Shakespeare's plays).'},
{'s':'Literature','y':2006,'q':'A figure of speech that involves exaggerated praise is:','o':['Hyperbole','Eulogy','Apostrophe','Epithet'],'ci':0,'e':'Hyperbole is exaggeration.'},
{'s':'Literature','y':2007,'q':'Addressing an absent person or object as if present is:','o':['Apostrophe','Personification','Simile','Metaphor'],'ci':0,'e':'Apostrophe (e.g., 'O death, where is thy sting?').'},
{'s':'Literature','y':2008,'q':'A descriptive name or phrase used to characterize a person/thing is an:','o':['Epithet','Eulogy','Aphorism','Allusion'],'ci':0,'e':'Epithet (e.g., 'Alexander the Great').'},
{'s':'Literature','y':2009,'q':'An indirect reference to a historical or literary figure is an:','o':['Allusion','Allegory','Aphorism','Epigram'],'ci':0,'e':'Allusion (e.g., 'Achilles heel').'},
{'s':'Literature','y':2010,'q':'The intended lesson or teaching of a story is the:','o':['Moral','Theme','Plot','Setting'],'ci':0,'e':'Moral is the ethical lesson.'},
{'s':'Literature','y':2011,'q':'The struggle within a character is:','o':['Internal conflict','External conflict','Rising action','Climax'],'ci':0,'e':'Internal conflict is psychological.'},
{'s':'Literature','y':2012,'q':'Conflict between a character and an outside force is:','o':['External conflict','Internal conflict','Foreshadowing','Flashback'],'ci':0,'e':'External conflict involves other characters, nature, society.'},
{'s':'Literature','y':2013,'q':'The author of 'Things Fall Apart' is:','o':['Chinua Achebe','Wole Soyinka','Ngũgĩ wa Thiong\'o','Ayi Kwei Armah'],'ci':0,'e':'Chinua Achebe wrote 'Things Fall Apart'.'},
{'s':'Literature','y':2014,'q':'The author of 'The Lion and the Jewel' is:','o':['Wole Soyinka','Chinua Achebe','Femi Osofisan','Ola Rotimi'],'ci':0,'e':'Wole Soyinka wrote 'The Lion and the Jewel'.'},
{'s':'Literature','y':2015,'q':'The playwright of 'The Trials of Brother Jero' is:','o':['Wole Soyinka','Chinua Achebe','Femi Osofisan','John Pepper Clark'],'ci':0,'e':'Soyinka wrote 'The Trials of Brother Jero'.'},
{'s':'Literature','y':2016,'q':''The Negro Speaks of Rivers' is a poem by:','o':['Langston Hughes','Claude McKay','Countee Cullen','James Weldon Johnson'],'ci':0,'e':'Langston Hughes wrote 'The Negro Speaks of Rivers'.'},
{'s':'Literature','y':2017,'q':''The Song of the Women of My Land' is by:','o':['Oumar Farouk Sesay','Lenrie Peters','Kofi Awoonor','Christopher Okigbo'],'ci':0,'e':'Oumar Farouk Sesay wrote that poem.'},
{'s':'Literature','y':2018,'q':''Vanity' is a poem by:','o':['Birago Diop','Leopold Sedar Senghor','Aimé Césaire','Léopold Sédar Senghor'],'ci':0,'e':'Birago Diop wrote 'Vanity'.'},
{'s':'Literature','y':2019,'q':'The central character in 'The Lion and the Jewel' is:','o':['Sidi','Lakunle','Baroka','Sadiku'],'ci':0,'e':'Sidi is the Jewel; Baroka is the Lion.'},
{'s':'Literature','y':2020,'q':'In 'Things Fall Apart', the protagonist is:','o':['Okonkwo','Nwoye','Obierika','Ikemefuna'],'ci':0,'e':'Okonkwo is the tragic hero.'},
{'s':'Literature','y':2021,'q':'Okonkwo's father in 'Things Fall Apart' is:','o':['Unoka','Obierika','Uchendu','Ogbuefi'],'ci':0,'e':'Unoka is Okonkwo's father.'},
{'s':'Literature','y':2022,'q':'In 'The Lion and the Jewel', Lakunle is the:','o':['Schoolteacher','Chief','Bale','Bashir'],'ci':0,'e':'Lakunle is the modern schoolteacher.'},
{'s':'Literature','y':2023,'q':'Baroka is the Bale of:','o':['Ilujinle','Umuofia','Mbanta','Kano'],'ci':0,'e':'Baroka is the Bale of Ilujinle.'},
{'s':'Literature','y':2024,'q':'The character of Sadiku in 'The Lion and the Jewel' is:','o':['Baroka\'s eldest wife','Lakunle\'s wife','Sidi\'s mother','The teacher'],'ci':0,'e':'Sadiku is Baroka's senior wife.'},
{'s':'Literature','y':2025,'q':'In 'Things Fall Apart', the title refers to:','o':['The collapse of Igbo society and culture','Okonkwo\'s death','Nwoye\'s conversion','The weather'],'ci':0,'e':'The novel depicts the disintegration of Igbo society.'},
{'s':'Literature','y':2026,'q':'Wole Soyinka is the first African:','o':['Nobel Laureate in Literature','President','Prime Minister','Soldier'],'ci':0,'e':'Soyinka won the Nobel in 1986.'},
{'s':'Literature','y':2000,'q':''The Whiteman's Burden' is a poem by:','o':['Rudyard Kipling','William Wordsworth','T.S. Eliot','W.B. Yeats'],'ci':0,'e':'Kipling wrote 'The Whiteman's Burden'.'},
{'s':'Literature','y':2001,'q':''The Raven' is a poem by:','o':['Edgar Allan Poe','Robert Frost','Emily Dickinson','Walt Whitman'],'ci':0,'e':'Poe wrote 'The Raven'.'},
{'s':'Literature','y':2002,'q':''The Road Not Taken' is by:','o':['Robert Frost','William Wordsworth','Ralph Waldo Emerson','Walt Whitman'],'ci':0,'e':'Frost wrote 'The Road Not Taken'.'},
{'s':'Literature','y':2003,'q':''Ozymandias' is a poem by:','o':['Percy Bysshe Shelley','William Blake','John Keats','Lord Byron'],'ci':0,'e':'Shelley wrote 'Ozymandias'.'},
{'s':'Literature','y':2004,'q':''Do Not Go Gentle into That Good Night' is by:','o':['Dylan Thomas','W.H. Auden','Philip Larkin','Seamus Heaney'],'ci':0,'e':'Dylan Thomas wrote that poem.'},
{'s':'Literature','y':2005,'q':''If—' is a poem by:','o':['Rudyard Kipling','William Wordsworth','Alfred Tennyson','Matthew Arnold'],'ci':0,'e':'Kipling wrote 'If—'.'},
{'s':'Literature','y':2006,'q':''The Waste Land' is a poem by:','o':['T.S. Eliot','Ezra Pound','W.B. Yeats','Robert Frost'],'ci':0,'e':'Eliot wrote 'The Waste Land'.'},
{'s':'Literature','y':2007,'q':''To His Coy Mistress' is by:','o':['Andrew Marvell','John Donne','Ben Jonson','George Herbert'],'ci':0,'e':'Marvell wrote 'To His Coy Mistress'.'},
{'s':'Literature','y':2008,'q':'The protagonist of Shakespeare's 'Hamlet' is:','o':['Hamlet','Claudius','Laertes','Ophelia'],'ci':0,'e':'Hamlet is the prince of Denmark.'},
{'s':'Literature','y':2009,'q':'In 'Romeo and Juliet', Juliet is from the:','o':['Capulets','Montagues','Verona','Mantua'],'ci':0,'e':'Juliet is a Capulet.'},
{'s':'Literature','y':2010,'q':'Romeo is from the:','o':['Montagues','Capulets','Escalus','Prince'],'ci':0,'e':'Romeo is a Montague.'},
{'s':'Literature','y':2011,'q':'Mercutio is a character in:','o':['Romeo and Juliet','Hamlet','Macbeth','Othello'],'ci':0,'e':'Mercutio is in 'Romeo and Juliet'.'},
{'s':'Literature','y':2012,'q':'The villain in 'Othello' is:','o':['Iago','Cassio','Roderigo','Brabantio'],'ci':0,'e':'Iago is the antagonist.'},
{'s':'Literature','y':2013,'q':'Macbeth is a:','o':['Thane','King','Duke','Earl'],'ci':0,'e':'Macbeth is Thane of Cawdor and later King.'},
{'s':'Literature','y':2014,'q':'Lady Macbeth is known for:','o':['Ambition and manipulation','Kindness','Weakness','Innocence'],'ci':0,'e':'Lady Macbeth drives Macbeth to murder.'},
{'s':'Literature','y':2015,'q':'The witches in 'Macbeth' predict:','o':['Macbeth will become king','Macbeth will die','Banquo will be king','Macbeth will be king forever'],'ci':0,'e':'The prophecy is that Macbeth will be king.'},
{'s':'Literature','y':2016,'q':'The play 'Hamlet' is set in:','o':['Denmark','Norway','England','Scotland'],'ci':0,'e':'Hamlet is Prince of Denmark.'},
{'s':'Literature','y':2017,'q':'Ophelia is a character in:','o':['Hamlet','Macbeth','Othello','King Lear'],'ci':0,'e':'Ophelia is in 'Hamlet'.'},
{'s':'Literature','y':2018,'q':'Polonius is killed by:','o':['Hamlet','Claudius','Laertes','Ophelia'],'ci':0,'e':'Hamlet accidentally kills Polonius.'},
{'s':'Literature','y':2019,'q':'The ghost in 'Hamlet' is:','o':['Hamlet\'s father','Claudius','Old Hamlet\'s ghost','Hamlet\'s uncle'],'ci':0,'e':'The ghost is Old Hamlet.'},
{'s':'Literature','y':2020,'q':'In 'Othello', Desdemona is:','o':['Othello\'s wife','Iago\'s wife','Cassio\'s wife','Brabantio\'s sister'],'ci':0,'e':'Desdemona is Othello\'s wife.'},
{'s':'Literature','y':2021,'q':'Othello is a:','o':['Moorish general','Venetian prince','Italian duke','Turkish commander'],'ci':0,'e':'Othello is a Moor in the Venetian army.'},
{'s':'Literature','y':2022,'q':'Desdemona is killed by:','o':['Othello','Iago','Cassio','Roderigo'],'ci':0,'e':'Othello smothers Desdemona.'},
{'s':'Literature','y':2023,'q':'Othello's fatal flaw is:','o':['Jealousy','Pride','Ambition','Indecision'],'ci':0,'e':'Jealousy leads to tragedy.'},
{'s':'Literature','y':2024,'q':'The character of Malvolio appears in:','o':['Twelfth Night','Hamlet','Macbeth','Othello'],'ci':0,'e':'Malvolio is in 'Twelfth Night'.'},
{'s':'Literature','y':2025,'q':'A soliloquy is a speech given by a character:','o':['Alone on stage','To other characters','To the audience in an aside','In a crowd'],'ci':0,'e':'A soliloquy is delivered when alone.'},
{'s':'Literature','y':2026,'q':'The tragic hero's downfall is caused by a:','o':['Tragic flaw (hamartia)','Lack of ambition','External events only','Good fortune'],'ci':0,'e':'Hamartia is the fatal flaw.'},

// ============================================================
// SECTION 2: PROSE – AFRICAN NOVELS (Q101–Q200)
// ============================================================
{'s':'Literature','y':2000,'q':''Things Fall Apart' is set in:','o':['Nigeria','Ghana','Kenya','South Africa'],'ci':0,'e':'The novel is set in Igbo land, Nigeria.'},
{'s':'Literature','y':2001,'q':'The novel 'Arrow of God' is by:','o':['Chinua Achebe','Wole Soyinka','Ngũgĩ wa Thiong\'o','Ayi Kwei Armah'],'ci':0,'e':'Achebe wrote 'Arrow of God'.'},
{'s':'Literature','y':2002,'q':'The protagonist of 'Arrow of God' is:','o':['Ezeulu','Okonkwo','Nwoye','Obierika'],'ci':0,'e':'Ezeulu is the chief priest.'},
{'s':'Literature','y':2003,'q':'The novel 'The Beautiful Ones Are Not Yet Born' is by:','o':['Ayi Kwei Armah','Chinua Achebe','Wole Soyinka','Ngũgĩ wa Thiong\'o'],'ci':0,'e':'Armah wrote that novel.'},
{'s':'Literature','y':2004,'q':'The novel 'Weep Not, Child' is by:','o':['Ngũgĩ wa Thiong\'o','Chinua Achebe','Ayi Kwei Armah','Wole Soyinka'],'ci':0,'e':'Ngũgĩ wrote 'Weep Not, Child'.'},
{'s':'Literature','y':2005,'q':''A Grain of Wheat' is a novel by:','o':['Ngũgĩ wa Thiong\'o','Chinua Achebe','Ayi Kwei Armah','Wole Soyinka'],'ci':0,'e':'Ngũgĩ wrote 'A Grain of Wheat'.'},
{'s':'Literature','y':2006,'q':''So Long a Letter' is by:','o':['Mariama Bâ','Chinua Achebe','Buchi Emecheta','Flora Nwapa'],'ci':0,'e':'Mariama Bâ wrote 'So Long a Letter'.'},
{'s':'Literature','y':2007,'q':''The Joys of Motherhood' is by:','o':['Buchi Emecheta','Flora Nwapa','Mariama Bâ','Chinua Achebe'],'ci':0,'e':'Buchi Emecheta wrote 'The Joys of Motherhood'.'},
{'s':'Literature','y':2008,'q':''Efuru' is a novel by:','o':['Flora Nwapa','Buchi Emecheta','Mariama Bâ','Chinua Achebe'],'ci':0,'e':'Flora Nwapa wrote 'Efuru'.'},
{'s':'Literature','y':2009,'q':''The Bride Price' is by:','o':['Buchi Emecheta','Flora Nwapa','Mariama Bâ','Chinua Achebe'],'ci':0,'e':'Buchi Emecheta wrote 'The Bride Price'.'},
{'s':'Literature','y':2010,'q':''The Interpreters' is a novel by:','o':['Wole Soyinka','Chinua Achebe','Ngũgĩ wa Thiong\'o','Ayi Kwei Armah'],'ci':0,'e':'Soyinka wrote 'The Interpreters'.'},
{'s':'Literature','y':2011,'q':''Petals of Blood' is by:','o':['Ngũgĩ wa Thiong\'o','Chinua Achebe','Wole Soyinka','Ayi Kwei Armah'],'ci':0,'e':'Ngũgĩ wrote 'Petals of Blood'.'},
{'s':'Literature','y':2012,'q':''Season of Migration to the North' is by:','o':['Tayeb Salih','Chinua Achebe','Naguib Mahfouz','Ahdaf Soueif'],'ci':0,'e':'Tayeb Salih wrote that novel.'},
{'s':'Literature','y':2013,'q':''A Question of Power' is by:','o':['Bessie Head','Chinua Achebe','Ngũgĩ wa Thiong\'o','Ayi Kwei Armah'],'ci':0,'e':'Bessie Head wrote 'A Question of Power'.'},
{'s':'Literature','y':2014,'q':''The Palm-wine Drinkard' is by:','o':['Amos Tutuola','Wole Soyinka','Chinua Achebe','Ola Rotimi'],'ci':0,'e':'Amos Tutuola wrote that novel.'},
{'s':'Literature','y':2015,'q':''My Life in the Bush of Ghosts' is by:','o':['Amos Tutuola','Wole Soyinka','Chinua Achebe','Ola Rotimi'],'ci':0,'e':'Tutuola also wrote that.'},
{'s':'Literature','y':2016,'q':'The protagonist of 'The Bride Price' is:','o':['Aku-nna','Efuru','Nnu Ego','Ramatu'],'ci':0,'e':'Aku-nna is the main character.'},
{'s':'Literature','y':2017,'q':'Nnu Ego is the protagonist of:','o':['The Joys of Motherhood','Efuru','The Bride Price','So Long a Letter'],'ci':0,'e':'Nnu Ego is the central character in 'The Joys of Motherhood'.'},
{'s':'Literature','y':2018,'q':'Ramatoulaye is the narrator of:','o':['So Long a Letter','The Joys of Motherhood','Efuru','The Bride Price'],'ci':0,'e':'Ramatoulaye narrates 'So Long a Letter'.'},
{'s':'Literature','y':2019,'q':''The Slave' is a novel by:','o':['Amos Tutuola','Chinua Achebe','Wole Soyinka','Ngũgĩ wa Thiong\'o'],'ci':0,'e':'Amos Tutuola wrote 'The Slave'.'},
{'s':'Literature','y':2020,'q':''God's Bits of Wood' is by:','o':['Sembène Ousmane','Chinua Achebe','Wole Soyinka','Ngũgĩ wa Thiong\'o'],'ci':0,'e':'Sembène Ousmane wrote that novel.'},
{'s':'Literature','y':2021,'q':''Xala' is a novel/film by:','o':['Sembène Ousmane','Chinua Achebe','Wole Soyinka','Ngũgĩ wa Thiong\'o'],'ci':0,'e':'Sembène Ousmane wrote 'Xala'.'},
{'s':'Literature','y':2022,'q':''The Novelist as Teacher' is an essay by:','o':['Chinua Achebe','Wole Soyinka','Ngũgĩ wa Thiong\'o','Ayi Kwei Armah'],'ci':0,'e':'Achebe wrote that essay.'},
{'s':'Literature','y':2023,'q':'In 'Things Fall Apart', Nwoye converts to:','o':['Christianity','Islam','Traditional religion','Hinduism'],'ci':0,'e':'Nwoye becomes a Christian.'},
{'s':'Literature','y':2024,'q':'Okonkwo commits suicide because:','o':['He cannot adapt to colonial rule','He is killed','He is diseased','He is exiled'],'ci':0,'e':'Okonkwo kills himself after the changes.'},
{'s':'Literature','y':2025,'q':'In 'Things Fall Apart', the 'Week of Peace' is:','o':['A sacred festival','A war celebration','A harvest festival','A market day'],'ci':0,'e':'The Week of Peace is a religious observance.'},
{'s':'Literature','y':2026,'q':'The Oracle of the Hills and Caves in 'Things Fall Apart' is:','o':['A spiritual institution','A market','A shrine','A court'],'ci':0,'e':'The Oracle is a key spiritual entity.'},
{'s':'Literature','y':2000,'q':'In 'Arrow of God', Ezeulu is the:','o':['Chief priest of Ulu','King','Warrior','Merchant'],'ci':0,'e':'Ezeulu is the chief priest of the god Ulu.'},
{'s':'Literature','y':2001,'q':'The central conflict in 'The Joys of Motherhood' is:','o':['Motherhood and societal expectations','Colonialism','War','Religious conversion'],'ci':0,'e':'The novel explores the burden of motherhood.'},
{'s':'Literature','y':2002,'q':'In 'So Long a Letter', Ramatoulaye writes to her friend:','o':['Aissatou','Nnu Ego','Efuru','Aku-nna'],'ci':0,'e':'The letter is addressed to Aissatou.'},
{'s':'Literature','y':2003,'q':'In 'So Long a Letter', Modou is:','o':['Ramatoulaye\'s husband','Aissatou\'s husband','Ramatoulaye\'s son','Aissatou\'s son'],'ci':0,'e':'Modou is Ramatoulaye's husband.'},
{'s':'Literature','y':2004,'q':'In 'Efuru', the title character is a:','o':['Woman who defies tradition','Queen','Teacher','Nurse'],'ci':0,'e':'Efuru is a strong, independent woman.'},
{'s':'Literature','y':2005,'q':'In 'The Bride Price', Aku-nna is in love with:','o':['Chike','Okonkwo','Nwoye','Ezeulu'],'ci':0,'e':'Aku-nna loves Chike.'},
{'s':'Literature','y':2006,'q':''The Wardrobe' in African literature is not applicable; trick question. Which novel has a character named Kofi? (Trick) – actually 'A Question of Power' has Elizabeth. Skip. Let's do: The novel 'The Beautyful Ones Are Not Yet Born' is set in:','o':['Ghana','Nigeria','Kenya','South Africa'],'ci':0,'e':'The novel is set in Ghana.'},
{'s':'Literature','y':2007,'q':'In 'The Beautyful Ones Are Not Yet Born', the protagonist is:','o':['The Man','Kofi','Kojo','Mensah'],'ci':0,'e':'The protagonist is unnamed, referred to as 'The Man'.'},
{'s':'Literature','y':2008,'q':'In 'Weep Not, Child', Njoroge is:','o':['The protagonist','The antagonist','The teacher','The chief'],'ci':0,'e':'Njoroge is the main character.'},
{'s':'Literature','y':2009,'q':'In 'A Grain of Wheat', Mugo is:','o':['A hero','A traitor','A chief','A teacher'],'ci':0,'e':'Mugo has a complex role as both hero and traitor.'},
{'s':'Literature','y':2010,'q':''Petals of Blood' is set in:','o':['Kenya','Nigeria','Ghana','South Africa'],'ci':0,'e':'The novel is set in Kenya.'},
{'s':'Literature','y':2011,'q':'In 'Season of Migration to the North', the protagonist returns to:','o':['Sudan','Egypt','Nigeria','Senegal'],'ci':0,'e':'The novel is set in Sudan.'},
{'s':'Literature','y':2012,'q':'In 'A Question of Power', Elizabeth experiences:','o':['Mental breakdown','Political exile','Religious conversion','Wealth'],'ci':0,'e':'Elizabeth suffers a psychotic breakdown.'},
{'s':'Literature','y':2013,'q':''The Palm-wine Drinkard' is a:','o':['Fantasy novel','Realistic novel','Historical novel','Detective novel'],'ci':0,'e':'It is a fantastical story based on Yoruba folklore.'},
{'s':'Literature','y':2014,'q':''The Interpreters' is about:','o':['A group of intellectuals','A group of politicians','A family','A war'],'ci':0,'e':'The novel follows a group of Nigerian intellectuals.'},
{'s':'Literature','y':2015,'q':'In 'Things Fall Apart', Ekwefi is:','o':['Okonkwo\'s second wife','Okonkwo\'s mother','Okonkwo\'s daughter','Okonkwo\'s sister'],'ci':0,'e':'Ekwefi is Okonkwo's second wife.'},
{'s':'Literature','y':2016,'q':'In 'Things Fall Apart', Ezinma is:','o':['Okonkwo\'s daughter','Okonkwo\'s wife','Okonkwo\'s son','Okonkwo\'s mother'],'ci':0,'e':'Ezinma is Okonkwo's beloved daughter.'},
{'s':'Literature','y':2017,'q':'In 'Things Fall Apart', the District Commissioner is a:','o':['Colonial official','Missionary','Soldier','Merchant'],'ci':0,'e':'He is a British colonial officer.'},
{'s':'Literature','y':2018,'q':'In 'Arrow of God', Ezeulu's son is:','o':['Oduche','Nwoye','Ikemefuna','Obierika'],'ci':0,'e':'Oduche is Ezeulu's son.'},
{'s':'Literature','y':2019,'q':'In 'Arrow of God', the white man is represented by:','o':['Winterbottom','Clarke','Smith','Brown'],'ci':0,'e':'Winterbottom is the colonial official.'},
{'s':'Literature','y':2020,'q':'In 'The Joys of Motherhood', Nnu Ego is married to:','o':['Nnaife','Okonkwo','Nwoye','Oduche'],'ci':0,'e':'Nnaife is Nnu Ego's husband.'},
{'s':'Literature','y':2021,'q':'In 'The Joys of Motherhood', Nnu Ego dies:','o':['Alone and unhappy','Happy and surrounded by children','In a car accident','From disease'],'ci':0,'e':'She dies alone, unfulfilled.'},
{'s':'Literature','y':2022,'q':'In 'So Long a Letter', Aissatou divorces her husband because:','o':['He took a second wife','He was violent','He was unfaithful','He was a tyrant'],'ci':0,'e':'He takes a second wife, and she leaves.'},
{'s':'Literature','y':2023,'q':'Ramatoulaye in 'So Long a Letter' has how many children?','o':['12','5','8','10'],'ci':0,'e':'She has twelve children.'},
{'s':'Literature','y':2024,'q':'In 'The Bride Price', the bride price is a:','o':['Payment to the family of the bride','Payment to the groom','Tax','Fine'],'ci':0,'e':'It is a traditional payment made to the bride's family.'},
{'s':'Literature','y':2025,'q':'In 'The Bride Price', Aku-nna dies because:','o':['Her bride price is too high','She is sick','She is murdered','She commits suicide'],'ci':0,'e':'The high bride price leads to her death in childbirth.'},
{'s':'Literature','y':2026,'q':'In 'Efuru', the title character is married to:','o':['Adizua','Okonkwo','Nwoye','Ezeulu'],'ci':0,'e':'Adizua is Efuru's husband.'},

// ============================================================
// SECTION 3: DRAMA – AFRICAN & SHAKESPEAREAN (Q201–Q320)
// ============================================================
{'s':'Literature','y':2000,'q':''The Lion and the Jewel' is set in the village of:','o':['Ilujinle','Umuofia','Kano','Benin'],'ci':0,'e':'Ilujinle is the setting.'},
{'s':'Literature','y':2001,'q':'In 'The Lion and the Jewel', Baroka is the:','o':['Bale of Ilujinle','Chief Priest','Teacher','Merchant'],'ci':0,'e':'Baroka is the Bale (chief).'},
{'s':'Literature','y':2002,'q':'Sidi in 'The Lion and the Jewel' is the:','o':['Jewel (beautiful maiden)','Lion (trickster)','Teacher','Wife'],'ci':0,'e':'Sidi is the Jewel.'},
{'s':'Literature','y':2003,'q':'Lakunle in 'The Lion and the Jewel' is the:','o':['Schoolteacher','Bale','Chief','Merchant'],'ci':0,'e':'Lakunle is the village schoolteacher.'},
{'s':'Literature','y':2004,'q':'Sadiku is Baroka's:','o':['Eldest wife','Mother','Sister','Daughter'],'ci':0,'e':'Sadiku is Baroka's senior wife.'},
{'s':'Literature','y':2005,'q':'In 'The Lion and the Jewel', Baroka tricks Sidi by:','o':['Faking impotence','Offering money','Threatening her','Marrying her by force'],'ci':0,'e':'Baroka pretends to be impotent to trap Sidi.'},
{'s':'Literature','y':2006,'q':'The theme of modernity vs tradition is central to:','o':['The Lion and the Jewel','Things Fall Apart','Hamlet','The Bride Price'],'ci':0,'e':'The play pits Lakunle's modern ideas against Baroka's traditional ways.'},
{'s':'Literature','y':2007,'q':''The Trials of Brother Jero' is a:','o':['Comedy','Tragedy','Tragicomedy','Farce'],'ci':0,'e':'It is a comedy satirising religious hypocrisy.'},
{'s':'Literature','y':2008,'q':'Brother Jero is a:','o':['Prophet','Teacher','Chief','Farmer'],'ci':0,'e':'Brother Jero is a self-proclaimed prophet.'},
{'s':'Literature','y':2009,'q':'In 'The Trials of Brother Jero', Chume is:','o':['Jero\'s disciple','Jero\'s wife','Jero\'s enemy','Jero\'s son'],'ci':0,'e':'Chume is a disciple.'},
{'s':'Literature','y':2010,'q':'The play 'The Strong Breed' is by:','o':['Wole Soyinka','Chinua Achebe','Femi Osofisan','Ola Rotimi'],'ci':0,'e':'Soyinka wrote 'The Strong Breed'.'},
{'s':'Literature','y':2011,'q':''The Strong Breed' explores the theme of:','o':['Sacrifice and scapegoating','Colonialism','Love','War'],'ci':0,'e':'The play deals with ritual sacrifice.'},
{'s':'Literature','y':2012,'q':''Kongi's Harvest' is a play by:','o':['Wole Soyinka','Chinua Achebe','Femi Osofisan','Ola Rotimi'],'ci':0,'e':'Soyinka wrote 'Kongi's Harvest'.'},
{'s':'Literature','y':2013,'q':'The play 'The Gods Are Not to Blame' is by:','o':['Ola Rotimi','Wole Soyinka','Femi Osofisan','Chinua Achebe'],'ci':0,'e':'Rotimi wrote that play.'},
{'s':'Literature','y':2014,'q':''The Gods Are Not to Blame' is a Nigerian adaptation of:','o':['Oedipus Rex','Hamlet','Macbeth','The Tempest'],'ci':0,'e':'It is based on Sophocles' 'Oedipus Rex'.'},
{'s':'Literature','y':2015,'q':'In 'The Gods Are Not to Blame', Odewale is the:','o':['King','Priest','Soldier','Merchant'],'ci':0,'e':'Odewale is the king.'},
{'s':'Literature','y':2016,'q':''The Marriage of Anansewa' is a play by:','o':['Efua Sutherland','Ama Ata Aidoo','Wole Soyinka','Ola Rotimi'],'ci':0,'e':'Efua Sutherland wrote that play.'},
{'s':'Literature','y':2017,'q':''The Dilemma of a Ghost' is by:','o':['Ama Ata Aidoo','Efua Sutherland','Wole Soyinka','Ola Rotimi'],'ci':0,'e':'Ama Ata Aidoo wrote 'The Dilemma of a Ghost'.'},
{'s':'Literature','y':2018,'q':''Anowa' is a play by:','o':['Ama Ata Aidoo','Efua Sutherland','Wole Soyinka','Ola Rotimi'],'ci':0,'e':'Ama Ata Aidoo wrote 'Anowa'.'},
{'s':'Literature','y':2019,'q':''The Chattering and the Song' is a play by:','o':['Femi Osofisan','Wole Soyinka','Ola Rotimi','Ama Ata Aidoo'],'ci':0,'e':'Femi Osofisan wrote that play.'},
{'s':'Literature','y':2020,'q':''Morountodun' is a play by:','o':['Femi Osofisan','Wole Soyinka','Ola Rotimi','Ama Ata Aidoo'],'ci':0,'e':'Osofisan wrote 'Morountodun'.'},
{'s':'Literature','y':2021,'q':'In 'The Lion and the Jewel', the title 'Jewel' refers to:','o':['Sidi','Baroka','Lakunle','Sadiku'],'ci':0,'e':'Sidi is the Jewel.'},
{'s':'Literature','y':2022,'q':'In 'The Lion and the Jewel', the 'Lion' is:','o':['Baroka','Lakunle','Sidi','Sadiku'],'ci':0,'e':'Baroka is the Lion.'},
{'s':'Literature','y':2023,'q':'In 'The Trials of Brother Jero', the play ends with:','o':['Jero\'s triumph','Chume\'s triumph','Jero\'s downfall','The church burning'],'ci':0,'e':'Jero emerges triumphant, satirising the gullibility of his followers.'},
{'s':'Literature','y':2024,'q':'In 'The Gods Are Not to Blame', Odewale's tragic flaw is:','o':['Pride and rashness','Greed','Cowardice','Indecision'],'ci':0,'e':'His pride and quick temper lead to his downfall.'},
{'s':'Literature','y':2025,'q':'Odewale in 'The Gods Are Not to Blame' is originally from:','o':['A village he abandoned','The city','Another country','The palace'],'ci':0,'e':'He left his own people to escape the prophecy.'},
{'s':'Literature','y':2026,'q':''The Lion and the Jewel' ends with:','o':['Sidi marrying Baroka','Sidi marrying Lakunle','Baroka dying','Lakunle leaving'],'ci':0,'e':'Sidi chooses Baroka and tradition.'},
{'s':'Literature','y':2000,'q':'In 'Hamlet', the character who goes mad is:','o':['Ophelia','Hamlet','Claudius','Laertes'],'ci':0,'e':'Ophelia goes mad and dies.'},
{'s':'Literature','y':2001,'q':'In 'Hamlet', Polonius is killed while:','o':['Hiding behind a curtain','Fighting Hamlet','Speaking to the queen','Praying'],'ci':0,'e':'Hamlet stabs him through the arras.'},
{'s':'Literature','y':2002,'q':'In 'Macbeth', the witches' prophecy includes:','o':['No man of woman born shall harm Macbeth','Macbeth will be killed by Macduff','Macbeth will be king','All of these'],'ci':3,'e':'The prophecies are layered and ambiguous.'},
{'s':'Literature','y':2003,'q':'Macduff was:','o':['Not born of woman (caesarean)','Born of woman','A witch','A king'],'ci':0,'e':'Macduff was from his mother's womb untimely ripped.'},
{'s':'Literature','y':2004,'q':'Lady Macbeth's sleepwalking reveals her:','o':['Guilt over Duncan\'s murder','Joy','Fear of the witches','Love for Macbeth'],'ci':0,'e':'She is tormented by guilt.'},
{'s':'Literature','y':2005,'q':'In 'Othello', Iago's wife is:','o':['Emilia','Desdemona','Bianca','Cassio'],'ci':0,'e':'Emilia is Iago's wife.'},
{'s':'Literature','y':2006,'q':'Othello kills Desdemona because:','o':['He believes she has been unfaithful','He wants power','She betrayed him politically','He is insane'],'ci':0,'e':'Iago convinces him of her infidelity.'},
{'s':'Literature','y':2007,'q':'In 'Romeo and Juliet', Friar Laurence:','o':['Marries Romeo and Juliet','Kills Tybalt','Fights Mercutio','Is Romeo\'s father'],'ci':0,'e':'Friar Laurence marries them.'},
{'s':'Literature','y':2008,'q':'Juliet takes a potion to:','o':['Appear dead','Kill herself','Kill Romeo','Sleep'],'ci':0,'e':'She takes it to avoid marrying Paris.'},
{'s':'Literature','y':2009,'q':'Romeo is banished from Verona for:','o':['Killing Tybalt','Killing Mercutio','Marrying Juliet','Fighting the Capulets'],'ci':0,'e':'Romeo kills Tybalt.'},
{'s':'Literature','y':2010,'q':'The character of Mercutio is:','o':['Romeo\'s witty friend','Juliet\'s cousin','Tybalt\'s friend','Friar Laurence\'s assistant'],'ci':0,'e':'Mercutio is Romeo's friend.'},
{'s':'Literature','y':2011,'q':'In 'Hamlet', Claudius is:','o':['Hamlet\'s uncle and stepfather','Hamlet\'s father','Hamlet\'s brother','Hamlet\'s son'],'ci':0,'e':'Claudius is the new king.'},
{'s':'Literature','y':2012,'q':'The gravedigger scene in 'Hamlet' is:','o':['Comic relief','Tragic','Romantic','Suspenseful'],'ci':0,'e':'It provides comic relief.'},
{'s':'Literature','y':2013,'q':'In 'Othello', Roderigo is:','o':['A Venetian gentleman in love with Desdemona','Othello\'s friend','Iago\'s brother','Cassio\'s friend'],'ci':0,'e':'Roderigo loves Desdemona.'},
{'s':'Literature','y':2014,'q':'In 'Othello', Cassio is:','o':['Othello\'s lieutenant','Othello\'s ensign','Othello\'s enemy','Desdemona\'s father'],'ci':0,'e':'Cassio is Othello's loyal lieutenant.'},
{'s':'Literature','y':2015,'q':'Desdemona's handkerchief is a key symbol in:','o':['Othello','Macbeth','Hamlet','King Lear'],'ci':0,'e':'The handkerchief is central to Iago's plot.'},
{'s':'Literature','y':2016,'q':''The Tempest' is a play by:','o':['William Shakespeare','Christopher Marlowe','Ben Jonson','John Webster'],'ci':0,'e':'Shakespeare wrote 'The Tempest'.'},
{'s':'Literature','y':2017,'q':'The protagonist of 'The Tempest' is:','o':['Prospero','Caliban','Miranda','Ferdinand'],'ci':0,'e':'Prospero is the duke and magician.'},
{'s':'Literature','y':2018,'q':'Caliban is a character in:','o':['The Tempest','Hamlet','Macbeth','Othello'],'ci':0,'e':'Caliban is in 'The Tempest'.'},
{'s':'Literature','y':2019,'q':'In 'The Tempest', Ariel is a:','o':['Spirit','Human','Monster','King'],'ci':0,'e':'Ariel is an airy spirit.'},
{'s':'Literature','y':2020,'q':''King Lear' is a tragedy about:','o':['A king who divides his kingdom','A prince who seeks revenge','A general who is jealous','A ghost who haunts a castle'],'ci':0,'e':'Lear divides his kingdom among his daughters.'},
{'s':'Literature','y':2021,'q':'In 'King Lear', the fool is:','o':['A wise jester','A foolish servant','A traitor','A ghost'],'ci':0,'e':'The fool speaks truth in jest.'},
{'s':'Literature','y':2022,'q':''Twelfth Night' is a:','o':['Comedy','Tragedy','History','Romance'],'ci':0,'e':'It is a comedy of mistaken identity.'},
{'s':'Literature','y':2023,'q':'In 'Twelfth Night', Viola disguises herself as:','o':['Cesario','Feste','Malvolio','Olivia'],'ci':0,'e':'Viola becomes Cesario.'},
{'s':'Literature','y':2024,'q':''A Midsummer Night's Dream' is a:','o':['Comedy','Tragedy','History','Problem play'],'ci':0,'e':'It is a romantic comedy.'},
{'s':'Literature','y':2025,'q':'Puck is a character in:','o':['A Midsummer Night\'s Dream','The Tempest','Hamlet','Macbeth'],'ci':0,'e':'Puck is the mischievous fairy.'},
{'s':'Literature','y':2026,'q':'In 'A Midsummer Night's Dream', the fairy queen is:','o':['Titania','Hippolyta','Hermia','Helena'],'ci':0,'e':'Titania is the fairy queen.'},

// ============================================================
// SECTION 4: POETRY – AFRICAN & ENGLISH (Q321–Q430)
// ============================================================
{'s':'Literature','y':2000,'q':''The Negro Speaks of Rivers' is a poem about:','o':['African heritage and history','Slavery','Love','Nature'],'ci':0,'e':'The poem celebrates African roots and resilience.'},
{'s':'Literature','y':2001,'q':'The refrain in 'The Negro Speaks of Rivers' is:','o':[''I bathed in the Euphrates'',''I've known rivers'',''My soul has grown deep'',''I built my hut near the Congo''],'ci':1,'e':'The repeated line is 'I've known rivers'.'},
{'s':'Literature','y':2002,'q':''Song of the Women of My Land' is by:','o':['Oumar Farouk Sesay','Lenrie Peters','Kofi Awoonor','Christopher Okigbo'],'ci':0,'e':'Sesay wrote that poem.'},
{'s':'Literature','y':2003,'q':''Vanity' by Birago Diop uses:','o':['Animal imagery','Religious imagery','War imagery','Love imagery'],'ci':0,'e':'The poem uses animal imagery (e.g., hyenas).'},
{'s':'Literature','y':2004,'q':''The New Dawn' is a poem by:','o':['Edward Kamau Brathwaite','Aimé Césaire','Léopold Sédar Senghor','Langston Hughes'],'ci':0,'e':'Brathwaite wrote 'The New Dawn'.'},
{'s':'Literature','y':2005,'q':''The African Child' is a poem by:','o':['Diop','Senghor','Césaire','Sesay'],'ci':0,'e':'Diop wrote 'The African Child'.'},
{'s':'Literature','y':2006,'q':''Piano and Drums' is a poem by:','o':['Gabriel Okara','Christopher Okigbo','Wole Soyinka','Chinua Achebe'],'ci':0,'e':'Okara wrote 'Piano and Drums'.'},
{'s':'Literature','y':2007,'q':'In 'Piano and Drums', the piano represents:','o':['Western culture','African culture','War','Love'],'ci':0,'e':'The piano symbolizes Western influence.'},
{'s':'Literature','y':2008,'q':'The drums in 'Piano and Drums' represent:','o':['African culture and tradition','Modernity','Colonialism','Death'],'ci':0,'e':'The drums represent African heritage.'},
{'s':'Literature','y':2009,'q':''A Road to Freedom' is a poem by:','o':['Peter Abrahams','Chinua Achebe','Wole Soyinka','Ngũgĩ wa Thiong\'o'],'ci':0,'e':'Abrahams wrote that poem.'},
{'s':'Literature','y':2010,'q':''The Fences' is a poem by:','o':['Oumar Farouk Sesay','Lenrie Peters','Kofi Awoonor','Christopher Okigbo'],'ci':0,'e':'Sesay wrote 'The Fences'.'},
{'s':'Literature','y':2011,'q':''The Grieved Lands' is a poem by:','o':['Agostinho Neto','Langston Hughes','Claude McKay','Countee Cullen'],'ci':0,'e':'Neto wrote 'The Grieved Lands'.'},
{'s':'Literature','y':2012,'q':''The Bell' is a poem by:','o':['Leopold Sédar Senghor','Aimé Césaire','Langston Hughes','Claude McKay'],'ci':0,'e':'Senghor wrote 'The Bell'.'},
{'s':'Literature','y':2013,'q':''The White Man's Burden' is a poem by:','o':['Rudyard Kipling','T.S. Eliot','W.B. Yeats','Robert Frost'],'ci':0,'e':'Kipling wrote 'The White Man's Burden'.'},
{'s':'Literature','y':2014,'q':''The Second Coming' is a poem by:','o':['W.B. Yeats','T.S. Eliot','Ezra Pound','Robert Frost'],'ci':0,'e':'Yeats wrote 'The Second Coming'.'},
{'s':'Literature','y':2015,'q':''The Wild Swans at Coole' is by:','o':['W.B. Yeats','William Wordsworth','John Keats','Robert Frost'],'ci':0,'e':'Yeats wrote that poem.'},
{'s':'Literature','y':2016,'q':''The Tyger' is a poem by:','o':['William Blake','William Wordsworth','Samuel Taylor Coleridge','John Keats'],'ci':0,'e':'Blake wrote 'The Tyger'.'},
{'s':'Literature','y':2017,'q':''The Lamb' is a companion poem to:','o':['The Tyger','The Raven','The Road Not Taken','Ozymandias'],'ci':0,'e':'Blake wrote both as contrasting poems.'},
{'s':'Literature','y':2018,'q':''Ozymandias' is about:','o':['The transience of power','Love','Nature','War'],'ci':0,'e':'The poem shows the decay of a once-great ruler.'},
{'s':'Literature','y':2019,'q':'The statue in 'Ozymandias' is:','o':['A shattered figure','A majestic ruler','A beautiful woman','A warrior'],'ci':0,'e':'The statue is in ruins.'},
{'s':'Literature','y':2020,'q':''The Road Not Taken' is about:','o':['Choice and individuality','Love','Nature','War'],'ci':0,'e':'The poem reflects on choosing a path in life.'},
{'s':'Literature','y':2021,'q':''Stopping by Woods on a Snowy Evening' is by:','o':['Robert Frost','William Wordsworth','T.S. Eliot','W.B. Yeats'],'ci':0,'e':'Frost wrote that poem.'},
{'s':'Literature','y':2022,'q':''The Raven' features a:','o':['Raven that speaks','Cat','Dog','Owl'],'ci':0,'e':'The raven says 'Nevermore'.'},
{'s':'Literature','y':2023,'q':'The speaker in 'The Raven' is mourning:','o':['Lenore','Annabel Lee','Helen','Ophelia'],'ci':0,'e':'He mourns the loss of Lenore.'},
{'s':'Literature','y':2024,'q':''Annabel Lee' is a poem by:','o':['Edgar Allan Poe','Robert Frost','Walt Whitman','Emily Dickinson'],'ci':0,'e':'Poe wrote 'Annabel Lee'.'},
{'s':'Literature','y':2025,'q':''Because I could not stop for Death' is by:','o':['Emily Dickinson','Walt Whitman','Robert Frost','T.S. Eliot'],'ci':0,'e':'Dickinson wrote that poem.'},
{'s':'Literature','y':2026,'q':''Dulce et Decorum Est' is a war poem by:','o':['Wilfred Owen','Siegfried Sassoon','Rupert Brooke','John McCrae'],'ci':0,'e':'Owen wrote that poem.'},
{'s':'Literature','y':2000,'q':'The title 'Dulce et Decorum Est' means:','o':['It is sweet and honourable','It is bitter and dishonourable','It is sweet to die','It is honourable to fight'],'ci':0,'e':'The phrase is from Horace, meaning 'it is sweet and honourable'.'},
{'s':'Literature','y':2001,'q':''The Soldier' is a poem by:','o':['Rupert Brooke','Wilfred Owen','Siegfried Sassoon','John McCrae'],'ci':0,'e':'Brooke wrote 'The Soldier'.'},
{'s':'Literature','y':2002,'q':''In Flanders Fields' is by:','o':['John McCrae','Wilfred Owen','Rupert Brooke','Siegfried Sassoon'],'ci':0,'e':'McCrae wrote that poem.'},
{'s':'Literature','y':2003,'q':'The refrain in 'In Flanders Fields' is:','o':[''We shall not sleep'',''In Flanders fields the poppies blow'',''Take up our quarrel with the foe'',''To you from failing hands we throw''],'ci':0,'e':'The poppy line is the recurring image.'},
{'s':'Literature','y':2004,'q':''The Waste Land' is a long poem by:','o':['T.S. Eliot','Ezra Pound','W.B. Yeats','Robert Frost'],'ci':0,'e':'Eliot wrote 'The Waste Land'.'},
{'s':'Literature','y':2005,'q':''The Love Song of J. Alfred Prufrock' is by:','o':['T.S. Eliot','Ezra Pound','W.B. Yeats','Robert Frost'],'ci':0,'e':'Eliot wrote that poem.'},
{'s':'Literature','y':2006,'q':'In 'Prufrock', the speaker is:','o':['Insecure and indecisive','Confident','Angry','Happy'],'ci':0,'e':'Prufrock is anxious and self-conscious.'},
{'s':'Literature','y':2007,'q':''The Song of the Women of My Land' is about:','o':['The suffering and resilience of women','War','Love','Nature'],'ci':0,'e':'The poem honours women's strength.'},
{'s':'Literature','y':2008,'q':'In 'Vanity', the poet criticises:','o':['Human vanity and pride','Colonialism','Love','Politics'],'ci':0,'e':'The poem condemns human pretentiousness.'},
{'s':'Literature','y':2009,'q':''The Negro Speaks of Rivers' mentions rivers such as:','o':['Euphrates, Congo, Nile, Mississippi','Nile, Amazon, Danube','Yangtze, Ganges','Thames, Seine'],'ci':0,'e':'The poem lists these four rivers.'},
{'s':'Literature','y':2010,'q':''The New Dawn' is a poem that celebrates:','o':['A new era of freedom and hope','Colonialism','War','Death'],'ci':0,'e':'The poem looks forward to a new beginning.'},
{'s':'Literature','y':2011,'q':''The Fences' by Oumar Farouk Sesay deals with:','o':['Barriers and division','Love','Nature','War'],'ci':0,'e':'The poem explores social and political barriers.'},
{'s':'Literature','y':2012,'q':''The Grieved Lands' by Agostinho Neto expresses:','o':['Sorrow over colonial oppression','Joy over freedom','Love for a woman','Nature'],'ci':0,'e':'The poem mourns the suffering of the people.'},
{'s':'Literature','y':2013,'q':''The Bell' by Senghor is about:','o':['The death of a friend','War','Love','Colonialism'],'ci':0,'e':'The poem laments a loss.'},
{'s':'Literature','y':2014,'q':''The African Child' celebrates:','o':['African childhood and heritage','Colonialism','Modernity','War'],'ci':0,'e':'The poem celebrates the African child.'},
{'s':'Literature','y':2015,'q':''Piano and Drums' ends with:','o':['The speaker feeling lost between two worlds','The speaker embracing piano','The speaker embracing drums','The speaker rejecting both'],'ci':0,'e':'The speaker is caught between cultures.'},
{'s':'Literature','y':2016,'q':''A Road to Freedom' is about:','o':['The struggle for liberation','Love','Nature','Religion'],'ci':0,'e':'The poem is about the fight for freedom.'},
{'s':'Literature','y':2017,'q':'The title 'Song of the Women of My Land' suggests:','o':['A collective female voice','A solo male voice','A choir','A war song'],'ci':0,'e':'The poem is sung by women.'},
{'s':'Literature','y':2018,'q':'In 'Vanity', the animals (hyenas) symbolise:','o':['Death and decay','Strength','Beauty','Freedom'],'ci':0,'e':'Hyenas are scavengers, symbolising mortality.'},
{'s':'Literature','y':2019,'q':''The White Man's Burden' is controversial because:','o':['It justifies colonialism','It praises Africa','It is a love poem','It is a sonnet'],'ci':0,'e':'The poem promotes the idea that colonisation is a duty.'},
{'s':'Literature','y':2020,'q':''The Road Not Taken' ends with the speaker:','o':['Saying he took the less travelled road','Regretting his choice','Going back','Taking the other road'],'ci':0,'e':'The poem ends with a reflective tone.'},
{'s':'Literature','y':2021,'q':''Stopping by Woods on a Snowy Evening' ends with:','o':[''And miles to go before I sleep'',''And away I go'',''I stop'',''The woods are dark''],'ci':0,'e':'The repetition emphasises duty.'},
{'s':'Literature','y':2022,'q':''The Raven' has a:','o':['Trochaic meter','Iambic pentameter','Free verse','Spondaic'],'ci':0,'e':'The poem uses trochaic octameter.'},
{'s':'Literature','y':2023,'q':''Annabel Lee' is written in:','o':['Ballad form','Sonnet','Ode','Haiku'],'ci':0,'e':'It is a narrative ballad.'},
{'s':'Literature','y':2024,'q':''Because I could not stop for Death' portrays death as:','o':['A polite carriage driver','A terrifying monster','A lover','A thief'],'ci':0,'e':'Death is depicted as a courteous gentleman.'},
{'s':'Literature','y':2025,'q':''Dulce et Decorum Est' uses:','o':['Realistic and horrific imagery','Romantic imagery','Happy imagery','Satirical imagery'],'ci':0,'e':'The poem describes the horrors of war vividly.'},
{'s':'Literature','y':2026,'q':'The title 'The Soldier' is by:','o':['Rupert Brooke','Wilfred Owen','Siegfried Sassoon','John McCrae'],'ci':0,'e':'Brooke's poem is patriotic.'},

// ============================================================
// SECTION 5: LITERARY CRITICISM & GENERAL KNOWLEDGE (Q431–Q500)
// ============================================================
{'s':'Literature','y':2000,'q':'The term 'African Literature' typically includes:','o':['Works by Africans and the diaspora','Only works by Africans in Africa','Only novels','Only poetry'],'ci':0,'e':'It encompasses writings by Africans and their descendants.'},
{'s':'Literature','y':2001,'q':'Oral tradition is the foundation of:','o':['African literature','English literature','American literature','Asian literature'],'ci':0,'e':'African literature is rooted in oral storytelling.'},
{'s':'Literature','y':2002,'q':'The prose form in African literature often incorporates:','o':['Folktales, proverbs, and songs','Only European forms','Only modern forms','No traditional elements'],'ci':0,'e':'African writers blend oral traditions with written forms.'},
{'s':'Literature','y':2003,'q':'The term 'Negritude' was coined by:','o':['Aimé Césaire','Léopold Sédar Senghor','Leon Damas','Frédéric Titinga Pacéré'],'ci':0,'e':'Césaire coined the term 'Negritude'.'},
{'s':'Literature','y':2004,'q':'Negritude is a literary and political movement that:','o':['Celebrates black identity and culture','Promotes colonialism','Supports apartheid','Rejects African culture'],'ci':0,'e':'Negritude affirms black heritage.'},
{'s':'Literature','y':2005,'q':'The 'Harlem Renaissance' was a cultural movement in the:','o':['United States','Nigeria','England','France'],'ci':0,'e':'It was in the 1920s in New York.'},
{'s':'Literature','y':2006,'q':'Key figures of the Harlem Renaissance include:','o':['Langston Hughes, Claude McKay, Zora Neale Hurston','Wole Soyinka, Chinua Achebe','T.S. Eliot, Ezra Pound','William Wordsworth, Coleridge'],'ci':0,'e':'These are central figures of the Harlem Renaissance.'},
{'s':'Literature','y':2007,'q':'The 'Angry Young Men' movement was in:','o':['British literature','American literature','African literature','French literature'],'ci':0,'e':'It was a post-WWII British literary movement.'},
{'s':'Literature','y':2008,'q':'The 'Beat Generation' includes:','o':['Jack Kerouac, Allen Ginsberg','Wole Soyinka, Ngũgĩ','Langston Hughes, Claude McKay','T.S. Eliot, W.B. Yeats'],'ci':0,'e':'Kerouac and Ginsberg were Beat writers.'},
{'s':'Literature','y':2009,'q':'The novel 'Ulysses' by James Joyce is famous for:','o':['Stream of consciousness','Simple prose','Romantic plot','War narrative'],'ci':0,'e':'Joyce used stream of consciousness.'},
{'s':'Literature','y':2010,'q':''Mrs Dalloway' is a novel by:','o':['Virginia Woolf','James Joyce','D.H. Lawrence','E.M. Forster'],'ci':0,'e':'Woolf wrote 'Mrs Dalloway'.'},
{'s':'Literature','y':2011,'q':''The Metamorphosis' is by:','o':['Franz Kafka','Albert Camus','Jean-Paul Sartre','Marcel Proust'],'ci':0,'e':'Kafka wrote 'The Metamorphosis'.'},
{'s':'Literature','y':2012,'q':''The Stranger' (L'Étranger) is by:','o':['Albert Camus','Jean-Paul Sartre','Franz Kafka','Marcel Proust'],'ci':0,'e':'Camus wrote 'The Stranger'.'},
{'s':'Literature','y':2013,'q':''Waiting for Godot' is a play by:','o':['Samuel Beckett','Eugene Ionesco','Jean-Paul Sartre','Albert Camus'],'ci':0,'e':'Beckett wrote 'Waiting for Godot'.'},
{'s':'Literature','y':2014,'q':''Waiting for Godot' is an example of:','o':['Theatre of the Absurd','Realism','Romanticism','Naturalism'],'ci':0,'e':'It is a classic absurdist play.'},
{'s':'Literature','y':2015,'q':''The House of the Spirits' is by:','o':['Isabel Allende','Gabriel García Márquez','Mario Vargas Llosa','Jorge Luis Borges'],'ci':0,'e':'Allende wrote that novel.'},
{'s':'Literature','y':2016,'q':''One Hundred Years of Solitude' is by:','o':['Gabriel García Márquez','Isabel Allende','Mario Vargas Llosa','Jorge Luis Borges'],'ci':0,'e':'Márquez wrote the novel.'},
{'s':'Literature','y':2017,'q':''One Hundred Years of Solitude' is an example of:','o':['Magical realism','Realism','Naturalism','Romanticism'],'ci':0,'e':'The novel is a masterpiece of magical realism.'},
{'s':'Literature','y':2018,'q':''Things Fall Apart' uses the technique of:','o':['Proverbs and oral storytelling','Stream of consciousness','Epistolary form','Dramatic monologue'],'ci':0,'e':'Achebe uses Igbo proverbs extensively.'},
{'s':'Literature','y':2019,'q':'The character of the 'District Commissioner' in 'Things Fall Apart' is:','o':['A symbol of colonial arrogance','A wise leader','A friendly character','A hero'],'ci':0,'e':'He dismisses African culture.'},
{'s':'Literature','y':2020,'q':'In 'The Lion and the Jewel', the use of mime and dance is from:','o':['African theatrical tradition','European theatre','Modern dance','Ballet'],'ci':0,'e':'Soyinka incorporates African performance styles.'},
{'s':'Literature','y':2021,'q':'The major theme of 'So Long a Letter' is:','o':['Women's empowerment and polygamy','War','Colonialism','Religion'],'ci':0,'e':'The novel critiques patriarchal norms.'},
{'s':'Literature','y':2022,'q':'The major theme of 'The Joys of Motherhood' is:','o':['The burden of motherhood and tradition','Colonialism','War','Love'],'ci':0,'e':'The novel explores the sacrifices of motherhood.'},
{'s':'Literature','y':2023,'q':'In 'The Bride Price', the theme of destiny vs. choice is central.','o':['Aku-nna chooses love and pays a price','She accepts tradition','She dies','She runs away'],'ci':0,'e':'The novel shows the conflict between individual choice and tradition.'},
{'s':'Literature','y':2024,'q':''Efuru' explores:','o':['A woman's independence and rejection of traditional norms','Colonialism','War','Religion'],'ci':0,'e':'Efuru is a strong, independent woman.'},
{'s':'Literature','y':2025,'q':''The Gods Are Not to Blame' is set in:','o':['A Yoruba context','An Igbo context','A Hausa context','A European context'],'ci':0,'e':'The play is set in a traditional Yoruba society.'},
{'s':'Literature','y':2026,'q':'Odewale's curse in 'The Gods Are Not to Blame' is:','o':['He will kill his father and marry his mother','He will be poor','He will be killed','He will be exiled'],'ci':0,'e':'The prophecy mirrors Oedipus.'},
{'s':'Literature','y':2000,'q':'The role of the chorus in Greek tragedy is to:','o':['Comment on events and provide moral perspective','Act as the protagonist','Fight the hero','Sing only'],'ci':0,'e':'The chorus comments on the action.'},
{'s':'Literature','y':2001,'q':'The concept of 'catharsis' in tragedy means:','o':['Emotional purging and relief','Violent death','Comic relief','Moral lesson'],'ci':0,'e':'Aristotle defined catharsis as emotional cleansing.'},
{'s':'Literature','y':2002,'q':''Hubris' in tragedy refers to:','o':['Excessive pride','Fear','Pity','Fate'],'ci':0,'e':'Hubris is a common tragic flaw.'},
{'s':'Literature','y':2003,'q':''Anagnorisis' is the moment of:','o':['Recognition or discovery','Death','Comedy','Reversal'],'ci':0,'e':'Anagnorisis is the tragic hero's realisation.'},
{'s':'Literature','y':2004,'q':''Peripeteia' is the:','o':['Reversal of fortune','Climax','Exposition','Denouement'],'ci':0,'e':'Peripeteia is a sudden reversal.'},
{'s':'Literature','y':2005,'q':'The first African to win the Nobel Prize in Literature was:','o':['Wole Soyinka','Chinua Achebe','Ngũgĩ wa Thiong\'o','Naguib Mahfouz'],'ci':0,'e':'Soyinka won in 1986.'},
{'s':'Literature','y':2006,'q':'The Ghanaian author Kwame Nkrumah wrote:','o':['Not primarily a literary author; he was a politician. The question refers to a famous Ghanaian writer. Let's use: Ayi Kwei Armah wrote:','o':['The Beautyful Ones Are Not Yet Born','Things Fall Apart','The Lion and the Jewel','Arrow of God'],'ci':0,'e':'Armah wrote 'The Beautyful Ones Are Not Yet Born'.'},
{'s':'Literature','y':2007,'q':'The Senegalese author Mariama Bâ wrote:','o':['So Long a Letter','Efuru','The Bride Price','The Joys of Motherhood'],'ci':0,'e':'Bâ wrote 'So Long a Letter'.'},
{'s':'Literature','y':2008,'q':'The Nigerian author who wrote 'The Concubine' is:','o':['Elechi Amadi','Chinua Achebe','Wole Soyinka','John Munonye'],'ci':0,'e':'Elechi Amadi wrote 'The Concubine'.'},
{'s':'Literature','y':2009,'q':'The protagonist of 'The Concubine' is:','o':['Ihuoma','Okonkwo','Ezeulu','Nnu Ego'],'ci':0,'e':'Ihuoma is the main character.'},
{'s':'Literature','y':2010,'q':'The play 'Death and the King's Horseman' is by:','o':['Wole Soyinka','Ola Rotimi','Femi Osofisan','Chinua Achebe'],'ci':0,'e':'Soyinka wrote that play.'},
{'s':'Literature','y':2011,'q':'The theme of 'Death and the King's Horseman' is:','o':['Cultural conflict and ritual','Colonialism','Love','War'],'ci':0,'e':'The play deals with the clash between Yoruba ritual and British law.'},
{'s':'Literature','y':2012,'q':'The character Elesin in 'Death and the King's Horseman' is:','o':['The King\'s horseman','The British officer','The chief','The son'],'ci':0,'e':'Elesin is the horseman destined to die.'},
{'s':'Literature','y':2013,'q':'The play 'The Swamp Dwellers' is by:','o':['Wole Soyinka','Ola Rotimi','Femi Osofisan','Ama Ata Aidoo'],'ci':0,'e':'Soyinka wrote 'The Swamp Dwellers'.'},
{'s':'Literature','y':2014,'q':''The Swamp Dwellers' is set in:','o':['A riverine village','A city','A desert','A mountain'],'ci':0,'e':'The play is set in a swampy delta village.'},
{'s':'Literature','y':2015,'q':'The play 'The Mad Man of the People' is by:','o':['Femi Osofisan','Wole Soyinka','Ola Rotimi','Chinua Achebe'],'ci':0,'e':'Osofisan wrote that play.'},
{'s':'Literature','y':2016,'q':'The play 'Women of Owu' is by:','o':['Femi Osofisan','Wole Soyinka','Ola Rotimi','Ama Ata Aidoo'],'ci':0,'e':'Osofisan wrote 'Women of Owu'.'},
{'s':'Literature','y':2017,'q':''Women of Owu' is a feminist adaptation of:','o':['Euripides' 'The Trojan Women'','Sophocles' 'Antigone'','Shakespeare's 'Macbeth'','Achebe's 'Things Fall Apart''],'ci':0,'e':'It is based on the Greek tragedy.'},
{'s':'Literature','y':2018,'q':'The character Osun in 'Women of Owu' is:','o':['A goddess','A queen','A soldier','A slave'],'ci':0,'e':'Osun is a Yoruba deity.'},
{'s':'Literature','y':2019,'q':'The playwright who wrote 'The Man Who Died' is:','o':['Wole Soyinka','Ola Rotimi','Femi Osofisan','Chinua Achebe'],'ci':0,'e':'Soyinka wrote 'The Man Who Died'.'},
{'s':'Literature','y':2020,'q':'The novel 'The Last Duty' is by:','o':['Isidore Okpewho','Chinua Achebe','Wole Soyinka','Ngũgĩ wa Thiong\'o'],'ci':0,'e':'Okpewho wrote 'The Last Duty'.'},
{'s':'Literature','y':2021,'q':''The Last Duty' is set during:','o':['The Nigerian Civil War','World War II','The colonial era','The post-independence era'],'ci':0,'e':'The novel is set during the Biafran war.'},
{'s':'Literature','y':2022,'q':''The Bright Continent' is a term used for:','o':['Africa','Asia','Europe','America'],'ci':0,'e':'Africa is often called the 'bright continent' or 'cradle of civilisation'.'},
{'s':'Literature','y':2023,'q':'The 'Hymn' in Nigerian literature is often:','o':['A patriotic poem','A love poem','A religious poem','A war poem'],'ci':0,'e':'It is a nationalistic poem.'},
{'s':'Literature','y':2024,'q':'The novel 'The Middle Passage' is by:','o':['V.S. Naipaul','Chinua Achebe','Wole Soyinka','Ngũgĩ wa Thiong\'o'],'ci':0,'e':'Naipaul wrote 'The Middle Passage'.'},
{'s':'Literature','y':2025,'q':''The Middle Passage' is a:','o':['Travelogue about the Caribbean','Novel about slavery','Poem about love','Play about war'],'ci':0,'e':'It is a non-fiction travel book.'},
{'s':'Literature','y':2026,'q':'The author of 'The Guerilla Soldiers' is:','o':['Chukwuemeka Ike','Chinua Achebe','Wole Soyinka','Ngũgĩ wa Thiong\'o'],'ci':0,'e':'Ike wrote that novel.'},
];
