// lib/questions_chemistry.dart
// 550 CHEMISTRY questions – WAEC/JAMB/NECO/UTME style.
// Topics: Atomic | Bonding | Stoichiometry | Gases | Acids/Bases/Salts | Electrolysis | Thermo/Kinetics | Organic | Analytical.
// Tricks: oxidation state traps, limiting reagents, isomer counting, pH of salts, electrolysis products, IUPAC naming, exceptions.

final List<Map<String, dynamic>> chemistryQuestions = [
// ============================================================
// SECTION 1: ATOMIC STRUCTURE & PERIODICITY (Q1–Q90)
// ============================================================
{'s':'Chemistry','y':2000,'q':'Which of the following has the highest first ionization energy?','o':['N','O','C','B'],'ci':0,'e':'N has half-filled 2p³ (extra stability), higher IE than O despite O being to the right.'},
{'s':'Chemistry','y':2001,'q':'The number of neutrons in ²⁴¹₁₀₄Pu is:','o':['137','144','241','104'],'ci':0,'e':'Neutrons = mass number - atomic number = 241 - 104 = 137.'},
{'s':'Chemistry','y':2002,'q':'Which element has the electron configuration 1s²2s²2p⁶3s²3p⁵?','o':['Cl','Ar','S','F'],'ci':0,'e':'3p⁵ = Group 17, period 3 → Chlorine (Cl, Z=17).'},
{'s':'Chemistry','y':2003,'q':'The maximum number of electrons that can occupy an f‑subshell is:','o':['14','10','6','2'],'ci':0,'e':'f subshell has 7 orbitals × 2 e⁻ = 14.'},
{'s':'Chemistry','y':2004,'q':'Which of the following is an isotope of ¹²C?','o':['¹⁴C','¹⁴N','¹²N','¹³C'],'ci':0,'e':'Isotopes have same atomic number (protons) but different mass number. ¹²C and ¹⁴C both Z=6.'},
{'s':'Chemistry','y':2005,'q':'The atomic radius increases down a group because:','o':['Addition of electron shells','Increased nuclear charge','Decreased shielding','Higher electronegativity'],'ci':0,'e':'New shells add distance from nucleus, outweighing nuclear charge increase.'},
{'s':'Chemistry','y':2006,'q':'Which of the following has the smallest atomic radius?','o':['F','Cl','Br','I'],'ci':0,'e':'Atomic radius decreases across a period; F is at top right.'},
{'s':'Chemistry','y':2007,'q':'The number of valence electrons in phosphorus (Z=15) is:','o':['5','3','15','8'],'ci':0,'e':'P: 1s²2s²2p⁶3s²3p³ → 5 valence electrons.'},
{'s':'Chemistry','y':2008,'q':'Which quantum number describes the shape of an orbital?','o':['Azimuthal (l)','Principal (n)','Magnetic (ml)','Spin (ms)'],'ci':0,'e':'l = 0 (s), 1 (p), 2 (d), 3 (f) determines shape.'},
{'s':'Chemistry','y':2009,'q':'The element with atomic number 24 has electronic configuration:','o':['[Ar]3d⁵4s¹','[Ar]3d⁴4s²','[Ar]3d⁶4s⁰','[Ar]3d⁵4s²'],'ci':0,'e':'Cr (Z=24) has half-filled d⁵ and s¹ for extra stability.'},
{'s':'Chemistry','y':2010,'q':'Which of the following is isoelectronic with Ne?','o':['Na⁺','Mg²⁺','F⁻','All of these'],'ci':3,'e':'All have 10 electrons: Na⁺ (11-1=10), Mg²⁺ (12-2=10), F⁻ (9+1=10).'},
{'s':'Chemistry','y':2011,'q':'The Aufbau principle states that electrons fill orbitals:','o':['From lowest to highest energy','From highest to lowest energy','Randomly','In pairs first'],'ci':0,'e':'Aufbau = building up from lowest energy.'},
{'s':'Chemistry','y':2012,'q':'Hund\'s rule states that electrons:','o':['Fill degenerate orbitals singly first','Pair up immediately','Fill s before p','Have opposite spins'],'ci':0,'e':'Maximum multiplicity: one electron per orbital before pairing.'},
{'s':'Chemistry','y':2013,'q':'The Pauli exclusion principle says that no two electrons can have the same:','o':['Set of all four quantum numbers','Principal quantum number','Azimuthal quantum number','Spin'],'ci':0,'e':'No two electrons can share all four QNs in an atom.'},
{'s':'Chemistry','y':2014,'q':'Which of the following violates the octet rule?','o':['BF₃','CF₄','NF₃','OF₂'],'ci':0,'e':'BF₃ has only 6 electrons around B (incomplete octet).'},
{'s':'Chemistry','y':2015,'q':'The screening effect (shielding) is caused by:','o':['Inner electrons repelling outer electrons','Nuclear charge','Protons','Neutrons'],'ci':0,'e':'Inner electrons shield outer electrons from full nuclear attraction.'},
{'s':'Chemistry','y':2016,'q':'Which of the following has the highest electron affinity?','o':['Cl','F','Br','I'],'ci':0,'e':'Cl has highest electron affinity; F is small, electron repulsion reduces it.'},
{'s':'Chemistry','y':2017,'q':'The number of unpaired electrons in O₂ is:','o':['2','0','4','1'],'ci':0,'e':'O₂ has 2 unpaired electrons in π* orbitals (paramagnetic).'},
{'s':'Chemistry','y':2018,'q':'Which is the most electropositive element?','o':['Cs','Fr','Li','Na'],'ci':1,'e':'Francium is most electropositive (but radioactive); Cs is often listed as most stable. Among options, Fr is most electropositive.'},
{'s':'Chemistry','y':2019,'q':'The periodicity of elements is based on:','o':['Atomic number','Atomic mass','Neutron number','Isotopic abundance'],'ci':0,'e':'Modern periodic table is arranged by atomic number (Moseley).'},
{'s':'Chemistry','y':2020,'q':'Which group elements are known as halogens?','o':['17','1','2','18'],'ci':0,'e':'Group 17 = halogens (F, Cl, Br, I, At).'},
{'s':'Chemistry','y':2021,'q':'Alkali metals are stored under oil because:','o':['They react with oxygen and moisture','They are dense','They are volatile','They are radioactive'],'ci':0,'e':'Alkali metals are highly reactive with air/water, so stored in oil to prevent oxidation.'},
{'s':'Chemistry','y':2022,'q':'Which of the following has the highest melting point?','o':['NaCl','HCl','Cl₂','CH₄'],'ci':0,'e':'NaCl is ionic solid with strong electrostatic forces → high melting point.'},
{'s':'Chemistry','y':2023,'q':'The element with the highest electronegativity is:','o':['F','O','Cl','N'],'ci':0,'e':'Fluorine (4.0) is the most electronegative element.'},
{'s':'Chemistry','y':2024,'q':'Which of the following is a metalloid?','o':['Si','Ge','As','All of these'],'ci':3,'e':'Si, Ge, As are all metalloids (B, Sb, Te, Po also).'},
{'s':'Chemistry','y':2025,'q':'The lanthanides and actinides are also called:','o':['Inner transition metals','Transition metals','Alkali metals','Halogens'],'ci':0,'e':'f‑block elements are inner transition metals.'},
{'s':'Chemistry','y':2026,'q':'Which of the following has the largest ionic radius?','o':['Cl⁻','K⁺','Ca²⁺','S²⁻'],'ci':3,'e':'S²⁻ has extra electrons and is isoelectronic with Cl⁻, but S²⁻ has less nuclear pull (Z=16 vs Cl=17) → larger.'},
{'s':'Chemistry','y':2000,'q':'The ground state electronic configuration of Cu (Z=29) is:','o':['[Ar]3d¹⁰4s¹','[Ar]3d⁹4s²','[Ar]3d⁸4s²4p¹','[Ar]3d¹⁰4s²'],'ci':0,'e':'Cu has d¹⁰s¹ for extra stability (fully filled d).'},
{'s':'Chemistry','y':2001,'q':'Which of the following statements about s‑block elements is correct?','o':['They are all metals','They are all non‑metals','They have high ionization energies','They are in groups 1 and 2'],'ci':3,'e':'s‑block = Groups 1 and 2 (plus He).'},
{'s':'Chemistry','y':2002,'q':'The element with atomic number 34 belongs to which period and group?','o':['Period 4, Group 16','Period 3, Group 16','Period 4, Group 17','Period 4, Group 15'],'ci':0,'e':'Se (Z=34) is Period 4, Group 16 (chalcogens).'},
{'s':'Chemistry','y':2003,'q':'Which of the following elements has the greatest metallic character?','o':['Cs','Na','Mg','Al'],'ci':0,'e':'Metallic character increases down a group; Cs is lowest in Group 1.'},
{'s':'Chemistry','y':2004,'q':'The ionisation energy generally increases across a period because:','o':['Increasing nuclear charge and decreasing atomic radius','Decreasing nuclear charge','Increasing shielding','Increasing atomic radius'],'ci':0,'e':'More protons, smaller radius → stronger pull on electrons.'},
{'s':'Chemistry','y':2005,'q':'The number of electrons in the n=3 shell of Fe (Z=26) is:','o':['14','18','8','6'],'ci':0,'e':'Fe: [Ar]3d⁶4s². n=3 has 3s²3p⁶3d⁶ = 2+6+6 = 14.'},
{'s':'Chemistry','y':2006,'q':'Which of the following is a violation of the octet rule?','o':['PCl₅','CCl₄','HCl','NaCl'],'ci':0,'e':'PCl₅ has 10 electrons around P (expanded octet).'},
{'s':'Chemistry','y':2007,'q':'The effective nuclear charge felt by the outermost electron in Na is less than the actual nuclear charge due to:','o':['Shielding by inner electrons','Electron repulsion','Nuclear decay','Isotopic effect'],'ci':0,'e':'Inner electrons shield outer electrons, reducing effective nuclear charge.'},
{'s':'Chemistry','y':2008,'q':'Which of the following elements has the lowest electronegativity?','o':['Cs','Fr','Rb','K'],'ci':1,'e':'Electronegativity decreases down a group; Fr (if considered) is lowest, but Cs is often given. Among options, Fr is lowest.'},
{'s':'Chemistry','y':2009,'q':'The number of orbitals in a d subshell is:','o':['5','3','7','1'],'ci':0,'e':'d subshell has 5 orbitals (ml = -2,-1,0,1,2).'},
{'s':'Chemistry','y':2010,'q':'The maximum number of electrons in a p orbital is:','o':['6','2','8','10'],'ci':0,'e':'p subshell has 3 orbitals × 2 e⁻ = 6 electrons total, but each orbital holds 2.'},
{'s':'Chemistry','y':2011,'q':'Which of the following is paramagnetic?','o':['O₂','N₂','H₂','He'],'ci':0,'e':'O₂ has unpaired electrons (paramagnetic); others are diamagnetic.'},
{'s':'Chemistry','y':2012,'q':'The group number for elements with ns²np⁵ configuration is:','o':['17','16','18','15'],'ci':0,'e':'ns²np⁵ → Group 17 (halogens).'},
{'s':'Chemistry','y':2013,'q':'Which of the following has the highest second ionization energy?','o':['Li','Be','B','C'],'ci':0,'e':'Li+ has 1s² (noble gas core); removing second electron requires breaking into core → very high IE.'},
{'s':'Chemistry','y':2014,'q':'The atomic number of an element with electronic configuration [Xe]4f¹⁴5d¹⁰6s² is:','o':['80','70','82','78'],'ci':0,'e':'Xe=54 +14+10+2 = 80 (Hg).'},
{'s':'Chemistry','y':2015,'q':'Which block of elements contains the transition metals?','o':['d‑block','s‑block','p‑block','f‑block'],'ci':0,'e':'Transition metals are d‑block elements (groups 3–12).'},
{'s':'Chemistry','y':2016,'q':'The element with the highest boiling point in its group is usually:','o':['The one with the largest atomic size','The one with the smallest atomic size','The one with the highest electronegativity','The one with the lowest mass'],'ci':0,'e':'Boiling point increases down a group due to increased van der Waals forces (larger size).'},
{'s':'Chemistry','y':2017,'q':'Which of the following is a noble gas?','o':['Ar','Kr','Xe','All of these'],'ci':3,'e':'All are noble gases (Group 18).'},
{'s':'Chemistry','y':2018,'q':'The outermost shell of an atom with Z=11 has how many electrons?','o':['1','2','8','11'],'ci':0,'e':'Na: [Ne]3s¹ → 1 valence electron.'},
{'s':'Chemistry','y':2019,'q':'Which of the following statements about isotopes is correct?','o':['They have the same chemical properties','They have different atomic numbers','They have different numbers of protons','They have the same mass number'],'ci':0,'e':'Isotopes have same Z (same chemical properties) but different mass numbers.'},
{'s':'Chemistry','y':2020,'q':'The first ionization energy of Mg is higher than that of Na because:','o':['Mg has a higher nuclear charge and smaller radius','Mg has more electrons','Mg is a metal','Mg has d electrons'],'ci':0,'e':'Mg (Z=12) has greater nuclear pull than Na (Z=11) → higher IE.'},
{'s':'Chemistry','y':2021,'q':'Which of the following has a half‑filled p subshell?','o':['N','O','C','F'],'ci':0,'e':'N: 1s²2s²2p³ → p³ is half‑filled.'},
{'s':'Chemistry','y':2022,'q':'The number of unpaired electrons in a nitrogen atom is:','o':['3','2','4','1'],'ci':0,'e':'N: 1s²2s²2p³ → 3 unpaired electrons.'},
{'s':'Chemistry','y':2023,'q':'Which of the following is diamagnetic?','o':['Zn²⁺','Cu²⁺','Fe³⁺','Cr³⁺'],'ci':0,'e':'Zn²⁺: [Ar]3d¹⁰ (all paired) → diamagnetic.'},
{'s':'Chemistry','y':2024,'q':'The element with the highest melting point among the following is:','o':['C (diamond)','Si','Ge','Sn'],'ci':0,'e':'Diamond has a giant covalent structure with strong C‑C bonds → very high melting point.'},
{'s':'Chemistry','y':2025,'q':'Which quantum number determines the orientation of an orbital in space?','o':['Magnetic (ml)','Azimuthal (l)','Principal (n)','Spin (ms)'],'ci':0,'e':'ml describes the spatial orientation (e.g., px, py, pz).'},
{'s':'Chemistry','y':2026,'q':'The element with Z=35 is a:','o':['Halogen','Noble gas','Alkali metal','Transition metal'],'ci':0,'e':'Br (Z=35) is in Group 17 (halogen).'},
{'s':'Chemistry','y':2000,'q':'Which of the following pairs are isoelectronic?','o':['Na⁺ and F⁻','Na⁺ and Cl⁻','Mg²⁺ and O²⁻','Both A and C'],'ci':3,'e':'Na⁺(10e⁻) = F⁻(10e⁻); Mg²⁺(10e⁻) = O²⁻(10e⁻).'},
{'s':'Chemistry','y':2001,'q':'The number of protons in Sr²⁺ (Z=38) is:','o':['38','36','40','19'],'ci':0,'e':'Protons = atomic number = 38 (electrons = 36).'},
{'s':'Chemistry','y':2002,'q':'Which of the following has the smallest bond length?','o':['N₂','O₂','F₂','H₂'],'ci':0,'e':'N₂ has a triple bond → shortest bond length.'},
{'s':'Chemistry','y':2003,'q':'The bond angle in methane (CH₄) is:','o':['109.5°','120°','90°','180°'],'ci':0,'e':'Tetrahedral geometry → 109.5°.'},
{'s':'Chemistry','y':2004,'q':'Which of the following is a polar molecule?','o':['HCl','Cl₂','CO₂','CCl₄'],'ci':0,'e':'HCl has a polar covalent bond with dipole moment. CO₂ is linear and non‑polar; CCl₄ is non‑polar despite polar bonds.'},
{'s':'Chemistry','y':2005,'q':'The type of bond in NH₄⁺ is:','o':['Coordinate covalent','Ionic','Metallic','Hydrogen'],'ci':0,'e':'NH₄⁺ has a dative (coordinate) bond from N to H⁺.'},
{'s':'Chemistry','y':2006,'q':'Which of the following is a network covalent solid?','o':['SiO₂','NaCl','Ice','K'],'ci':0,'e':'SiO₂ (silica) has a giant covalent network structure.'},
{'s':'Chemistry','y':2007,'q':'Metallic bonding is characterized by:','o':['Delocalized electrons','Ionic interactions','Covalent bonds','Hydrogen bonds'],'ci':0,'e':'Metals have a sea of delocalized electrons.'},
{'s':'Chemistry','y':2008,'q':'Which of the following compounds has ionic bonding?','o':['NaCl','HCl','CO₂','H₂O'],'ci':0,'e':'NaCl is an ionic compound (metal + non‑metal).'},
{'s':'Chemistry','y':2009,'q':'The number of sigma and pi bonds in C₂H₄ is:','o':['5 sigma, 1 pi','4 sigma, 2 pi','3 sigma, 3 pi','6 sigma, 0 pi'],'ci':0,'e':'C₂H₄: H₂C=CH₂ → 4 C‑H (sigma) + 1 C‑C (sigma) = 5 sigma; 1 C=C (pi).'},
{'s':'Chemistry','y':2010,'q':'The shape of SF₆ is:','o':['Octahedral','Square planar','Tetrahedral','Trigonal bipyramidal'],'ci':0,'e':'SF₆ has 6 bonding pairs, no lone pairs → octahedral.'},
{'s':'Chemistry','y':2011,'q':'Which of the following has sp³ hybridization?','o':['CH₄','C₂H₄','C₂H₂','CO₂'],'ci':0,'e':'CH₄: tetrahedral → sp³.'},
{'s':'Chemistry','y':2012,'q':'The intermolecular force present in solid iodine (I₂) is:','o':['van der Waals (dispersion)','Hydrogen bonds','Dipole‑dipole','Ionic'],'ci':0,'e':'I₂ is non‑polar, only dispersion forces (London forces).'},
{'s':'Chemistry','y':2013,'q':'Which of the following has the highest boiling point?','o':['H₂O','H₂S','H₂Se','H₂Te'],'ci':0,'e':'H₂O has strong hydrogen bonds, elevating its boiling point despite lower molar mass.'},
{'s':'Chemistry','y':2014,'q':'Hydrogen bonds occur between molecules containing H bonded to:','o':['F, O, N','F, O, Cl','O, N, S','N, O, Br'],'ci':0,'e':'H‑bonding requires H bonded to highly electronegative small atoms (F, O, N).'},
{'s':'Chemistry','y':2015,'q':'The shape of a molecule with two bonding pairs and two lone pairs is:','o':['Bent','Linear','Tetrahedral','Trigonal planar'],'ci':0,'e':'VSEPR: 2 bonding + 2 lone → bent (e.g., H₂O).'},
{'s':'Chemistry','y':2016,'q':'Which of the following is a non‑polar compound?','o':['CCl₄','HCl','NH₃','H₂O'],'ci':0,'e':'CCl₄ has tetrahedral symmetry, bond dipoles cancel → non‑polar.'},
{'s':'Chemistry','y':2017,'q':'The bond in F₂ is:','o':['Non‑polar covalent','Polar covalent','Ionic','Metallic'],'ci':0,'e':'F₂ has identical atoms → non‑polar covalent bond.'},
{'s':'Chemistry','y':2018,'q':'Which of the following has the highest lattice energy?','o':['MgO','NaCl','KCl','CsI'],'ci':0,'e':'MgO has small ions with +2/−2 charges → very high lattice energy.'},
{'s':'Chemistry','y':2019,'q':'The VSEPR theory predicts the shape of:','o':['Molecules based on repulsion of electron pairs','Ions based on nuclear charge','Crystals based on ionic radii','Metals based on electron sea'],'ci':0,'e':'VSEPR = Valence Shell Electron Pair Repulsion.'},
{'s':'Chemistry','y':2020,'q':'Which of the following is a linear molecule?','o':['BeCl₂','H₂O','NH₃','CH₄'],'ci':0,'e':'BeCl₂ has two bonding pairs, no lone pairs → linear (180°).'},
{'s':'Chemistry','y':2021,'q':'The number of lone pairs on Xe in XeF₂ is:','o':['3','2','1','0'],'ci':0,'e':'XeF₂: 5 electron pairs on Xe; 2 bonding, 3 lone pairs → linear shape.'},
{'s':'Chemistry','y':2022,'q':'Which of the following has a trigonal planar shape?','o':['BF₃','NH₃','CH₄','H₂O'],'ci':0,'e':'BF₃: 3 bonding, 0 lone → trigonal planar (120°).'},
{'s':'Chemistry','y':2023,'q':'The bond polarity in HCl is due to:','o':['Difference in electronegativity','Difference in size','Difference in mass','Difference in temperature'],'ci':0,'e':'Electronegativity difference between H and Cl creates a dipole.'},
{'s':'Chemistry','y':2024,'q':'Which of the following solids is an electrical conductor?','o':['Graphite','Diamond','Sulfur','Iodine'],'ci':0,'e':'Graphite has delocalized electrons in layers → conducts electricity.'},
{'s':'Chemistry','y':2025,'q':'The type of crystal in NaCl is:','o':['Ionic crystal','Covalent network','Molecular crystal','Metallic'],'ci':0,'e':'NaCl forms a face‑centered cubic ionic lattice.'},
{'s':'Chemistry','y':2026,'q':'Which of the following has a double bond?','o':['CO₂','CH₄','NH₃','H₂O'],'ci':0,'e':'CO₂ has two C=O double bonds.'},

// ============================================================
// SECTION 2: STOICHIOMETRY & MOLE CONCEPT (Q91–Q180)
// ============================================================
{'s':'Chemistry','y':2000,'q':'What is the molar mass of H₂SO₄? (H=1, S=32, O=16)','o':['98','96','100','88'],'ci':0,'e':'2(1)+32+4(16)=2+32+64=98 g/mol.'},
{'s':'Chemistry','y':2001,'q':'How many moles are in 36 g of H₂O? (H=1, O=16)','o':['2','1','0.5','4'],'ci':0,'e':'Molar mass H₂O = 18 g/mol. Moles = 36/18 = 2.'},
{'s':'Chemistry','y':2002,'q':'The number of atoms in 0.5 mol of CO₂ is: (Avogadro\'s number = 6.02×10²³)','o':['9.03×10²³','3.01×10²³','6.02×10²³','1.2×10²⁴'],'ci':0,'e':'1 mol CO₂ has 3 atoms (1 C + 2 O). 0.5 mol has 0.5×3×6.02×10²³ = 9.03×10²³ atoms.'},
{'s':'Chemistry','y':2003,'q':'What is the mass of 0.25 mol of NaCl? (Na=23, Cl=35.5)','o':['14.625 g','58.5 g','29.25 g','7.312 g'],'ci':0,'e':'Molar mass NaCl = 58.5 g/mol. Mass = 0.25×58.5 = 14.625 g.'},
{'s':'Chemistry','y':2004,'q':'Calculate the percentage of oxygen in Al₂O₃. (Al=27, O=16)','o':['47.06%','52.94%','40%','60%'],'ci':0,'e':'Molar mass Al₂O₃ = 2(27)+3(16)=54+48=102. O% = (48/102)×100 = 47.06%.'},
{'s':'Chemistry','y':2005,'q':'A compound has empirical formula CH₂O and molar mass 90 g/mol. What is its molecular formula?','o':['C₃H₆O₃','C₂H₄O₂','C₄H₈O₄','CH₂O'],'ci':0,'e':'Empirical mass = 12+2+16=30. n = 90/30 = 3 → molecular formula = C₃H₆O₃.'},
{'s':'Chemistry','y':2006,'q':'What volume does 2 mol of a gas occupy at STP? (Molar volume = 22.4 L)','o':['44.8 L','22.4 L','11.2 L','67.2 L'],'ci':0,'e':'2 mol × 22.4 L/mol = 44.8 L.'},
{'s':'Chemistry','y':2007,'q':'What is the concentration of a solution containing 0.1 mol of NaCl in 500 cm³?','o':['0.2 mol/dm³','0.1 mol/dm³','0.5 mol/dm³','0.05 mol/dm³'],'ci':0,'e':'500 cm³ = 0.5 dm³. C = n/V = 0.1/0.5 = 0.2 mol/dm³.'},
{'s':'Chemistry','y':2008,'q':'How many moles of NaOH are required to neutralize 0.5 mol of H₂SO₄? (Equation: H₂SO₄ + 2NaOH → Na₂SO₄ + 2H₂O)','o':['1.0','0.5','2.0','0.25'],'ci':0,'e':'Mole ratio NaOH:H₂SO₄ = 2:1 → moles NaOH = 2×0.5 = 1.0.'},
{'s':'Chemistry','y':2009,'q':'What is the mass of 1 mole of electrons? (Mass of electron = 9.11×10⁻³¹ kg)','o':['5.49×10⁻⁷ kg','9.11×10⁻³¹ kg','1.67×10⁻²⁷ kg','6.02×10²³ kg'],'ci':0,'e':'1 mol e⁻ = 6.02×10²³ × 9.11×10⁻³¹ kg = 5.49×10⁻⁷ kg.'},
{'s':'Chemistry','y':2010,'q':'Which of the following has the greatest mass? (H=1, O=16, C=12, N=14)','o':['1 mol C₂H₅OH','1 mol H₂O','1 mol CO₂','1 mol NH₃'],'ci':0,'e':'Molar masses: C₂H₅OH=46, H₂O=18, CO₂=44, NH₃=17 → ethanol has greatest mass.'},
{'s':'Chemistry','y':2011,'q':'The limiting reagent in a reaction is the one that:','o':['Is completely consumed','Is in excess','Is a catalyst','Has the highest molar mass'],'ci':0,'e':'Limiting reagent determines product yield and is fully used up.'},
{'s':'Chemistry','y':2012,'q':'If 5 g of CaCO₃ is heated, how many grams of CaO are produced? (Ca=40, C=12, O=16)','o':['2.8 g','5.6 g','1.4 g','4.2 g'],'ci':0,'e':'Molar mass CaCO₃=100, CaO=56. Mass CaO = 5×(56/100)=2.8 g.'},
{'s':'Chemistry','y':2013,'q':'A solution contains 0.02 mol of HCl in 250 cm³. What is its concentration?','o':['0.08 mol/dm³','0.04 mol/dm³','0.02 mol/dm³','0.16 mol/dm³'],'ci':0,'e':'250 cm³ = 0.25 dm³. C = 0.02/0.25 = 0.08 mol/dm³.'},
{'s':'Chemistry','y':2014,'q':'What volume of 0.5 M NaOH is needed to neutralize 20 cm³ of 0.2 M HCl?','o':['8 cm³','20 cm³','10 cm³','40 cm³'],'ci':0,'e':'Moles HCl = 0.2×0.02 = 0.004. NaOH moles = 0.004. V = 0.004/0.5 = 0.008 L = 8 cm³.'},
{'s':'Chemistry','y':2015,'q':'The empirical formula of a compound with 40% C, 6.7% H, and 53.3% O is: (C=12, H=1, O=16)','o':['CH₂O','C₂H₄O₂','C₃H₆O₃','CHO'],'ci':0,'e':'Moles: C=40/12=3.33, H=6.7/1=6.7, O=53.3/16=3.33 → ratio 1:2:1 → CH₂O.'},
{'s':'Chemistry','y':2016,'q':'A gas has a density of 1.96 g/L at STP. What is its molar mass? (Molar volume = 22.4 L)','o':['43.9 g/mol','22.4 g/mol','1.96 g/mol','44.8 g/mol'],'ci':0,'e':'M = density × molar volume = 1.96 × 22.4 = 43.9 g/mol.'},
{'s':'Chemistry','y':2017,'q':'If 2 mol of H₂ reacts with 1 mol of O₂, how many moles of H₂O are produced?','o':['2','1','4','0.5'],'ci':0,'e':'2H₂ + O₂ → 2H₂O. Mole ratio H₂:H₂O = 1:1 → 2 mol H₂O.'},
{'s':'Chemistry','y':2018,'q':'What is the oxidation state of S in H₂SO₄?','o':['+6','+4','+8','-2'],'ci':0,'e':'2(+1)+x+4(-2)=0 → 2+x-8=0 → x=+6.'},
{'s':'Chemistry','y':2019,'q':'The number of moles of ions in 1 mole of NaCl is:','o':['2','1','3','4'],'ci':0,'e':'NaCl dissociates into Na⁺ and Cl⁻ → 2 moles of ions.'},
{'s':'Chemistry','y':2020,'q':'Which of the following has the highest number of molecules? (H=1, C=12, O=16)','o':['36 g H₂O','44 g CO₂','16 g CH₄','46 g C₂H₅OH'],'ci':0,'e':'Moles: H₂O=36/18=2; CO₂=44/44=1; CH₄=16/16=1; C₂H₅OH=46/46=1. H₂O has most moles (2).'},
{'s':'Chemistry','y':2021,'q':'The percentage by mass of nitrogen in NH₃ is: (N=14, H=1)','o':['82.35%','17.65%','50%','75%'],'ci':0,'e':'Molar mass NH₃=17. N% = (14/17)×100 = 82.35%.'},
{'s':'Chemistry','y':2022,'q':'A 0.1 M solution of H₂SO₄ has an H⁺ ion concentration of:','o':['0.2 M','0.1 M','0.05 M','0.4 M'],'ci':0,'e':'H₂SO₄ → 2H⁺ + SO₄²⁻. [H⁺] = 2×0.1 = 0.2 M.'},
{'s':'Chemistry','y':2023,'q':'What is the volume of 0.5 mol of O₂ at STP?','o':['11.2 L','22.4 L','44.8 L','5.6 L'],'ci':0,'e':'0.5 × 22.4 = 11.2 L.'},
{'s':'Chemistry','y':2024,'q':'How many grams of NaCl are needed to prepare 500 mL of 0.2 M solution? (Na=23, Cl=35.5)','o':['5.85 g','11.7 g','2.925 g','58.5 g'],'ci':0,'e':'Moles = 0.2×0.5 = 0.1. Mass = 0.1×58.5 = 5.85 g.'},
{'s':'Chemistry','y':2025,'q':'A hydrocarbon contains 85.7% C and 14.3% H. What is its empirical formula? (C=12, H=1)','o':['CH₂','CH₃','C₂H₄','C₃H₆'],'ci':0,'e':'C:85.7/12=7.14; H:14.3/1=14.3; ratio 1:2 → CH₂.'},
{'s':'Chemistry','y':2026,'q':'The molarity of a solution containing 4.0 g of NaOH in 250 cm³ is: (Na=23, O=16, H=1)','o':['0.4 M','0.1 M','1.0 M','0.2 M'],'ci':0,'e':'Moles NaOH = 4/40=0.1. V=0.25 L. C=0.1/0.25=0.4 M.'},

// ============================================================
// SECTION 3: GAS LAWS & KINETIC THEORY (Q181–Q230)
// ============================================================
{'s':'Chemistry','y':2000,'q':'Boyle\'s law states that at constant temperature, the volume of a gas is:','o':['Inversely proportional to pressure','Directly proportional to pressure','Independent of pressure','Directly proportional to temperature'],'ci':0,'e':'Boyle: PV = k (V ∝ 1/P).'},
{'s':'Chemistry','y':2001,'q':'Charles\'s law relates volume and:','o':['Temperature (Kelvin)','Pressure','Mass','Density'],'ci':0,'e':'Charles: V ∝ T (at constant P).'},
{'s':'Chemistry','y':2002,'q':'The ideal gas equation is:','o':['PV = nRT','PV = NkT','Both','PV = RT'],'ci':2,'e':'PV = nRT = NkT (where N = number of molecules).'},
{'s':'Chemistry','y':2003,'q':'A gas occupies 2 L at 1 atm. What volume does it occupy at 2 atm (constant T)?','o':['1 L','4 L','0.5 L','2 L'],'ci':0,'e':'P₁V₁ = P₂V₂ → 1×2 = 2×V₂ → V₂ = 1 L.'},
{'s':'Chemistry','y':2004,'q':'A gas has a volume of 3 L at 300 K. What is the volume at 600 K (constant P)?','o':['6 L','1.5 L','3 L','12 L'],'ci':0,'e':'V₁/T₁ = V₂/T₂ → 3/300 = V₂/600 → V₂=6 L.'},
{'s':'Chemistry','y':2005,'q':'The pressure exerted by a gas is due to:','o':['Collisions of molecules with the walls','Molecular weight','Gravity','Intermolecular forces'],'ci':0,'e':'Gas pressure comes from molecular impacts on container walls.'},
{'s':'Chemistry','y':2006,'q':'At STP, 1 mole of any gas occupies:','o':['22.4 L','24.4 L','22.4 m³','24.4 m³'],'ci':0,'e':'Molar volume at STP = 22.4 L (0°C, 1 atm).'},
{'s':'Chemistry','y':2007,'q':'Which gas deviates most from ideal behavior at high pressure?','o':['NH₃','He','H₂','N₂'],'ci':0,'e':'NH₃ has strong intermolecular forces (H‑bonding), deviates most.'},
{'s':'Chemistry','y':2008,'q':'The kinetic theory assumes that gas molecules:','o':['Have negligible volume','Have no intermolecular forces','Move in random motion','All of these'],'ci':3,'e':'All are assumptions of the kinetic theory of ideal gases.'},
{'s':'Chemistry','y':2009,'q':'What is the pressure of 0.5 mol of gas in a 10 L container at 300 K? (R=0.082 L·atm/mol·K)','o':['1.23 atm','2.46 atm','0.615 atm','4.92 atm'],'ci':0,'e':'P = nRT/V = (0.5×0.082×300)/10 = 1.23 atm.'},
{'s':'Chemistry','y':2010,'q':'The root mean square speed of gas molecules is directly proportional to:','o':['√T','T','1/√T','1/T'],'ci':0,'e':'v_rms = √(3RT/M) → ∝ √T.'},
{'s':'Chemistry','y':2011,'q':'Which of the following gases effuses the fastest?','o':['He','Ne','Ar','Kr'],'ci':0,'e':'Graham\'s law: rate ∝ 1/√M. He has the smallest molar mass.'},
{'s':'Chemistry','y':2012,'q':'Dalton\'s law of partial pressure states that total pressure is the sum of:','o':['Partial pressures of individual gases','Volumes of individual gases','Masses of individual gases','Temperatures of individual gases'],'ci':0,'e':'Dalton: P_total = P₁ + P₂ + ...'},
{'s':'Chemistry','y':2013,'q':'A mixture of gases at 1 atm has partial pressures: 0.3 atm O₂ and 0.4 atm N₂. What is the partial pressure of CO₂?','o':['0.3 atm','0.1 atm','0.4 atm','0.7 atm'],'ci':0,'e':'P_total = 1 = 0.3+0.4+P_CO₂ → P_CO₂ = 0.3 atm.'},
{'s':'Chemistry','y':2014,'q':'Which of the following is NOT a condition for ideal gas behavior?','o':['High pressure','Low pressure','High temperature','Large volume'],'ci':0,'e':'Ideal behavior is approached at low pressure and high temperature. High pressure causes deviations.'},
{'s':'Chemistry','y':2015,'q':'Van der Waals equation corrects for:','o':['Molecular volume and intermolecular forces','Temperature and pressure','Mass and velocity','Energy and entropy'],'ci':0,'e':'The a term corrects for attraction, b term for molecular volume.'},
{'s':'Chemistry','y':2016,'q':'A gas at 27°C has volume V. What is the volume at 127°C at constant pressure?','o':['(400/300)V','(300/400)V','2V','V/2'],'ci':0,'e':'T₁=300K, T₂=400K. V₂ = (T₂/T₁)V = (400/300)V.'},
{'s':'Chemistry','y':2017,'q':'At constant volume, the pressure of a gas is:','o':['Directly proportional to temperature','Inversely proportional to temperature','Independent of temperature','Proportional to volume'],'ci':0,'e':'Gay‑Lussac: P ∝ T (at constant V).'},
{'s':'Chemistry','y':2018,'q':'A gas sample has a pressure of 2 atm at 300 K. What is the pressure at 600 K if volume is constant?','o':['4 atm','2 atm','1 atm','6 atm'],'ci':0,'e':'P₁/T₁ = P₂/T₂ → 2/300 = P₂/600 → P₂ = 4 atm.'},
{'s':'Chemistry','y':2019,'q':'The average kinetic energy of gas molecules depends on:','o':['Temperature only','Pressure only','Volume only','Molar mass'],'ci':0,'e':'KE_avg = (3/2)RT, depends only on temperature.'},
{'s':'Chemistry','y':2020,'q':'Which of the following is a real gas that behaves ideally at low pressure?','o':['Any gas','Only noble gases','Only H₂','Only He'],'ci':0,'e':'At low pressure, all gases approach ideal behavior.'},
{'s':'Chemistry','y':2021,'q':'The gas with the highest rate of diffusion is:','o':['H₂','O₂','CO₂','Cl₂'],'ci':0,'e':'Rate ∝ 1/√M. H₂ has smallest molar mass (2 g/mol).'},
{'s':'Chemistry','y':2022,'q':'If the volume of a gas is halved at constant temperature, the pressure:','o':['Doubles','Halves','Quadruples','Remains same'],'ci':0,'e':'Boyle\'s law: P₁V₁ = P₂V₂ → V half → P doubles.'},
{'s':'Chemistry','y':2023,'q':'A container holds 2 moles of N₂ and 3 moles of O₂. What is the mole fraction of N₂?','o':['0.4','0.6','0.5','0.2'],'ci':0,'e':'X_N₂ = 2/(2+3) = 0.4.'},
{'s':'Chemistry','y':2024,'q':'The compressibility factor Z = PV/nRT. For an ideal gas, Z =:','o':['1','0','∞','>1'],'ci':0,'e':'For ideal gas, Z = 1. Deviations give Z≠1.'},
{'s':'Chemistry','y':2025,'q':'Which gas has the highest critical temperature?','o':['H₂O','CO₂','H₂','He'],'ci':0,'e':'H₂O has strong intermolecular forces → high critical temperature.'},
{'s':'Chemistry','y':2026,'q':'At absolute zero, the volume of an ideal gas becomes:','o':['Zero','Infinite','Constant','Negative'],'ci':0,'e':'V ∝ T; at 0 K, V = 0 (theoretical).'},

// ============================================================
// SECTION 4: ACIDS, BASES & SALTS (Q231–Q310)
// ============================================================
{'s':'Chemistry','y':2000,'q':'An acid is a substance that:','o':['Donates protons','Accepts protons','Donates electrons','Accepts electrons'],'ci':0,'e':'Bronsted‑Lowry: acid = proton donor.'},
{'s':'Chemistry','y':2001,'q':'A base is a substance that:','o':['Accepts protons','Donates protons','Donates electrons','Accepts electrons'],'ci':0,'e':'Bronsted‑Lowry: base = proton acceptor.'},
{'s':'Chemistry','y':2002,'q':'Which of the following is a strong acid?','o':['HCl','CH₃COOH','H₂CO₃','H₂S'],'ci':0,'e':'HCl is a strong acid (fully dissociates).'},
{'s':'Chemistry','y':2003,'q':'Which of the following is a weak base?','o':['NH₃','NaOH','KOH','Ba(OH)₂'],'ci':0,'e':'NH₃ is a weak base (partial ionisation).'},
{'s':'Chemistry','y':2004,'q':'The pH of a 0.01 M HCl solution is:','o':['2','1','3','4'],'ci':0,'e':'HCl is strong acid, [H⁺]=0.01 M, pH = -log(0.01)=2.'},
{'s':'Chemistry','y':2005,'q':'What is the pH of a 0.001 M NaOH solution?','o':['11','3','12','10'],'ci':0,'e':'pOH = -log(0.001)=3; pH = 14-3=11.'},
{'s':'Chemistry','y':2006,'q':'The salt formed from a strong acid and a weak base is:','o':['Acidic','Basic','Neutral','Amphoteric'],'ci':0,'e':'e.g., NH₄Cl (strong acid HCl + weak base NH₃) → acidic salt.'},
{'s':'Chemistry','y':2007,'q':'Which of the following salts will produce a basic solution when dissolved in water?','o':['Na₂CO₃','NH₄Cl','NaCl','KNO₃'],'ci':0,'e':'Na₂CO₃ is salt of weak acid (H₂CO₃) and strong base (NaOH) → basic.'},
{'s':'Chemistry','y':2008,'q':'The pH of a solution with [H⁺] = 1×10⁻⁵ M is:','o':['5','9','7','1'],'ci':0,'e':'pH = -log(1×10⁻⁵)=5.'},
{'s':'Chemistry','y':2009,'q':'In the titration of HCl with NaOH, the equivalence point has pH:','o':['7','>7','<7','0'],'ci':0,'e':'Strong acid + strong base → neutral salt → pH = 7.'},
{'s':'Chemistry','y':2010,'q':'Which indicator changes colour at pH 8–10?','o':['Phenolphthalein','Methyl orange','Litmus','Methyl red'],'ci':0,'e':'Phenolphthalein: colourless below 8, pink above 10.'},
{'s':'Chemistry','y':2011,'q':'A buffer solution resists changes in:','o':['pH','Temperature','Concentration','Pressure'],'ci':0,'e':'Buffer = weak acid/base + its salt, maintains pH.'},
{'s':'Chemistry','y':2012,'q':'Which of the following is NOT a buffer?','o':['NaCl + HCl','CH₃COOH + CH₃COONa','NH₃ + NH₄Cl','H₂CO₃ + NaHCO₃'],'ci':0,'e':'NaCl + HCl is a strong acid + salt of strong acid; not a buffer.'},
{'s':'Chemistry','y':2013,'q':'The conjugate base of HSO₄⁻ is:','o':['SO₄²⁻','H₂SO₄','HSO₃⁻','SO₃²⁻'],'ci':0,'e':'Conjugate base = acid minus H⁺.'},
{'s':'Chemistry','y':2014,'q':'The conjugate acid of NH₃ is:','o':['NH₄⁺','NH₂⁻','NH₂OH','N₂H₄'],'ci':0,'e':'Conjugate acid = base + H⁺.'},
{'s':'Chemistry','y':2015,'q':'Which of the following is amphiprotic?','o':['H₂O','HCl','NaOH','NaCl'],'ci':0,'e':'H₂O can act as acid or base (donates or accepts H⁺).'},
{'s':'Chemistry','y':2016,'q':'The salt formed when NaOH reacts with H₂SO₄ is:','o':['Na₂SO₄','NaHSO₄','Na₂SO₃','NaSO₄'],'ci':0,'e':'2NaOH + H₂SO₄ → Na₂SO₄ + 2H₂O (normal salt).'},
{'s':'Chemistry','y':2017,'q':'A salt that contains water of crystallisation is called:','o':['Hydrated salt','Anhydrous salt','Double salt','Complex salt'],'ci':0,'e':'Hydrated salts have water molecules in their crystal structure (e.g., CuSO₄·5H₂O).'},
{'s':'Chemistry','y':2018,'q':'Which of the following is a deliquescent substance?','o':['NaOH','NaCl','CaCO₃','SiO₂'],'ci':0,'e':'NaOH absorbs moisture from air and dissolves in it (deliquescence).'},
{'s':'Chemistry','y':2019,'q':'Which substance is hygroscopic but not deliquescent?','o':['Concentrated H₂SO₄','NaOH','CaCl₂','MgCl₂'],'ci':0,'e':'H₂SO₄ absorbs water but does not dissolve to form a solution (does not deliquesce).'},
{'s':'Chemistry','y':2020,'q':'The pH of a 0.1 M acetic acid (Ka=1.8×10⁻⁵) is approximately:','o':['2.87','4.76','1.0','5.0'],'ci':0,'e':'[H⁺] = √(Ka×C) = √(1.8×10⁻⁵×0.1) = 1.34×10⁻³ M; pH = -log(1.34×10⁻³) = 2.87.'},
{'s':'Chemistry','y':2021,'q':'Which of the following is a monobasic acid?','o':['HCl','H₂SO₄','H₃PO₄','CH₃COOH'],'ci':0,'e':'Monobasic = one ionizable H⁺ (HCl).'},
{'s':'Chemistry','y':2022,'q':'A dibasic acid has how many replaceable hydrogen atoms?','o':['2','1','3','4'],'ci':0,'e':'Dibasic = two H⁺ ions per molecule (e.g., H₂SO₄).'},
{'s':'Chemistry','y':2023,'q':'Which of the following is a basic oxide?','o':['Na₂O','CO₂','SO₂','P₂O₅'],'ci':0,'e':'Na₂O is a basic oxide (metal oxide). Others are acidic oxides.'},
{'s':'Chemistry','y':2024,'q':'Which of the following is an acidic oxide?','o':['CO₂','CaO','MgO','Na₂O'],'ci':0,'e':'CO₂ dissolves in water to form carbonic acid (acidic oxide).'},
{'s':'Chemistry','y':2025,'q':'Amphoteric oxides react with both:','o':['Acids and bases','Only acids','Only bases','Salts'],'ci':0,'e':'Amphoteric oxides (e.g., Al₂O₃, ZnO) react with acids and bases.'},
{'s':'Chemistry','y':2026,'q':'Which of the following is an example of an amphoteric oxide?','o':['Al₂O₃','Na₂O','CO₂','SO₃'],'ci':0,'e':'Al₂O₃ is amphoteric.'},

// ============================================================
// SECTION 5: ELECTROCHEMISTRY & ELECTROLYSIS (Q311–Q380)
// ============================================================
{'s':'Chemistry','y':2000,'q':'Electrolysis is the decomposition of a compound by:','o':['Electric current','Heat','Light','Pressure'],'ci':0,'e':'Electrolysis uses electricity to drive a non‑spontaneous reaction.'},
{'s':'Chemistry','y':2001,'q':'In electrolysis, the anode is the electrode where:','o':['Oxidation occurs','Reduction occurs','Neutralisation occurs','No reaction'],'ci':0,'e':'Anode attracts anions → oxidation (loss of electrons).'},
{'s':'Chemistry','y':2002,'q':'The cathode is the electrode where:','o':['Reduction occurs','Oxidation occurs','Both','Neither'],'ci':0,'e':'Cathode attracts cations → reduction (gain of electrons).'},
{'s':'Chemistry','y':2003,'q':'During electrolysis of molten NaCl, the product at the cathode is:','o':['Na','Cl₂','Na⁺','Cl⁻'],'ci':0,'e':'Na⁺ + e⁻ → Na (reduction).'},
{'s':'Chemistry','y':2004,'q':'During electrolysis of molten NaCl, the product at the anode is:','o':['Cl₂','Na','Na⁺','Cl⁻'],'ci':0,'e':'2Cl⁻ → Cl₂ + 2e⁻ (oxidation).'},
{'s':'Chemistry','y':2005,'q':'A faraday is equal to:','o':['96500 C','96.5 C','9.65×10⁷ C','965 C'],'ci':0,'e':'1 Faraday = charge on 1 mol of electrons = 96500 C.'},
{'s':'Chemistry','y':2006,'q':'How many faradays are required to deposit 1 mol of Cu from Cu²⁺?','o':['2','1','3','4'],'ci':0,'e':'Cu²⁺ + 2e⁻ → Cu → 2 faradays.'},
{'s':'Chemistry','y':2007,'q':'In the electrolysis of brine (NaCl solution), the product at the cathode is:','o':['H₂','Cl₂','Na','O₂'],'ci':0,'e':'Water is reduced preferentially: 2H₂O + 2e⁻ → H₂ + 2OH⁻.'},
{'s':'Chemistry','y':2008,'q':'The product at the anode during electrolysis of brine (using inert electrodes) is:','o':['Cl₂','O₂','H₂','NaOH'],'ci':0,'e':'2Cl⁻ → Cl₂ + 2e⁻ (chlorine gas).'},
{'s':'Chemistry','y':2009,'q':'Which of the following is a strong electrolyte?','o':['NaCl','CH₃COOH','NH₃','Sugar'],'ci':0,'e':'NaCl fully dissociates in water → strong electrolyte.'},
{'s':'Chemistry','y':2010,'q':'The electrical conductivity of metals is due to:','o':['Delocalized electrons','Mobile ions','Protons','Neutrons'],'ci':0,'e':'Metals have free (delocalised) electrons that carry charge.'},
{'s':'Chemistry','y':2011,'q':'In the electrochemical series, which metal is the strongest reducing agent?','o':['Li','K','Na','Ca'],'ci':0,'e':'Li has the most negative reduction potential → strongest reducing agent.'},
{'s':'Chemistry','y':2012,'q':'Which of the following is displaced from its salt solution by copper?','o':['Ag','Zn','Fe','Pb'],'ci':0,'e':'Cu is less reactive than Ag, so Cu + Ag⁺ → Cu²⁺ + Ag.'},
{'s':'Chemistry','y':2013,'q':'A galvanic cell converts:','o':['Chemical energy to electrical energy','Electrical energy to chemical energy','Heat to chemical','Light to chemical'],'ci':0,'e':'Galvanic (voltaic) cells produce electricity from spontaneous reactions.'},
{'s':'Chemistry','y':2014,'q':'The salt bridge in a galvanic cell allows:','o':['Flow of ions to maintain charge balance','Flow of electrons','Flow of current','Flow of protons'],'ci':0,'e':'Salt bridge completes the circuit by ion migration.'},
{'s':'Chemistry','y':2015,'q':'The standard electrode potential of hydrogen is:','o':['0.00 V','1.00 V','-0.76 V','+0.34 V'],'ci':0,'e':'Standard hydrogen electrode (SHE) is assigned 0.00 V.'},
{'s':'Chemistry','y':2016,'q':'Which of the following ions is reduced at the cathode during electrolysis of aqueous CuSO₄?','o':['Cu²⁺','H⁺','SO₄²⁻','OH⁻'],'ci':0,'e':'Cu²⁺ has a higher reduction potential than H⁺, so Cu²⁺ is reduced first.'},
{'s':'Chemistry','y':2017,'q':'During electrolysis of dilute H₂SO₄ with Pt electrodes, the product at the anode is:','o':['O₂','H₂','SO₃','SO₂'],'ci':0,'e':'OH⁻ → ½O₂ + H₂O + 2e⁻ (oxygen gas).'},
{'s':'Chemistry','y':2018,'q':'The discharge potential of an ion depends on:','o':['Electrode potential and concentration','Only concentration','Only temperature','Only pressure'],'ci':0,'e':'Discharge depends on standard potential and ion concentration (Nernst equation).'},
{'s':'Chemistry','y':2019,'q':'Which of the following will not undergo electrolysis?','o':['Solid NaCl','Molten NaCl','Aqueous NaCl','All can electrolyse'],'ci':0,'e':'Solid NaCl has no free ions; electrolysis requires mobile ions.'},
{'s':'Chemistry','y':2020,'q':'In the electrolysis of aqueous NaCl, what is formed at the cathode?','o':['H₂','Na','Cl₂','O₂'],'ci':0,'e':'Water is reduced to H₂ (since Na⁺ is not easily reduced in water).'},
{'s':'Chemistry','y':2021,'q':'The anode in an electrochemical cell is:','o':['Negative electrode in a galvanic cell, positive in electrolytic cell','Positive in both','Negative in both','Positive in galvanic, negative in electrolytic'],'ci':0,'e':'Anode = negative in galvanic (oxidation), positive in electrolytic (oxidation).'},
{'s':'Chemistry','y':2022,'q':'A metal that is electroplated uses:','o':['Electrolysis','Galvanic cell','Neutralisation','Combustion'],'ci':0,'e':'Electroplating is done using electrolysis (deposition of metal ions).'},
{'s':'Chemistry','y':2023,'q':'The number of moles of electrons required to deposit 1 mol of Al from Al³⁺ is:','o':['3','1','2','4'],'ci':0,'e':'Al³⁺ + 3e⁻ → Al → 3 faradays.'},
{'s':'Chemistry','y':2024,'q':'In the electrolysis of CuSO₄ with copper electrodes, the mass of the anode:','o':['Decreases','Increases','Remains same','Dissolves completely'],'ci':0,'e':'Copper from anode dissolves as Cu²⁺ (anode loses mass).'},
{'s':'Chemistry','y':2025,'q':'In the electrolysis of CuSO₄ with inert electrodes, the solution becomes:','o':['More acidic','More basic','Neutral','Unchanged'],'ci':0,'e':'2H₂O → O₂ + 4H⁺ + 4e⁻ at anode; H⁺ increases → acidic.'},
{'s':'Chemistry','y':2026,'q':'The Faraday constant is the charge on:','o':['1 mole of electrons','1 mole of protons','1 mole of ions','1 gram of electrons'],'ci':0,'e':'1 F = charge on 1 mole of e⁻ = 96500 C.'},

// ============================================================
// SECTION 6: THERMODYNAMICS & KINETICS (Q381–Q430)
// ============================================================
{'s':'Chemistry','y':2000,'q':'Exothermic reactions:','o':['Release heat','Absorb heat','Require catalyst','Are spontaneous always'],'ci':0,'e':'Exothermic = ΔH negative (heat released).'},
{'s':'Chemistry','y':2001,'q':'Endothermic reactions:','o':['Absorb heat','Release heat','Have negative ΔH','Produce light'],'ci':0,'e':'Endothermic = ΔH positive (heat absorbed).'},
{'s':'Chemistry','y':2002,'q':'The enthalpy change of a reaction depends on:','o':['Initial and final states','Pathway','Rate','Catalyst'],'ci':0,'e':'Enthalpy is a state function; ΔH depends only on initial and final states.'},
{'s':'Chemistry','y':2003,'q':'The activation energy is the minimum energy required for:','o':['A reaction to occur','A bond to break','A catalyst to work','A gas to expand'],'ci':0,'e':'Activation energy is the energy barrier that reactants must overcome.'},
{'s':'Chemistry','y':2004,'q':'A catalyst:','o':['Lowers activation energy','Increases activation energy','Changes ΔH','Is consumed in reaction'],'ci':0,'e':'Catalysts provide an alternative pathway with lower Ea.'},
{'s':'Chemistry','y':2005,'q':'The rate of a reaction increases with temperature because:','o':['More molecules have energy > Ea','Molecules collide less','Concentration changes','Pressure decreases'],'ci':0,'e':'Higher T increases the fraction of molecules with sufficient energy.'},
{'s':'Chemistry','y':2006,'q':'The law of mass action states that the rate is proportional to:','o':['Product of concentrations of reactants','Product of concentrations of products','Sum of concentrations','Square of concentrations'],'ci':0,'e':'Rate ∝ [A]^a[B]^b for elementary reactions.'},
{'s':'Chemistry','y':2007,'q':'The order of a reaction is determined by:','o':['Experiment','Stoichiometry','Temperature','Pressure'],'ci':0,'e':'Reaction order is empirical, determined from experimental data.'},
{'s':'Chemistry','y':2008,'q':'A zero‑order reaction has a rate that:','o':['Is independent of concentration','Doubles when concentration doubles','Is proportional to concentration','Is proportional to square of concentration'],'ci':0,'e':'Rate = k (independent of [reactant]).'},
{'s':'Chemistry','y':2009,'q':'The half‑life of a first‑order reaction:','o':['Is independent of initial concentration','Depends on initial concentration','Is inversely proportional to initial concentration','Is directly proportional to initial concentration'],'ci':0,'e':'t₁/₂ = 0.693/k (constant for first‑order).'},
{'s':'Chemistry','y':2010,'q':'Which of the following increases the rate of a reaction?','o':['Increasing temperature','Adding catalyst','Increasing concentration','All of these'],'ci':3,'e':'All increase reaction rate (except in some specific cases).'},
{'s':'Chemistry','y':2011,'q':'The collision theory states that for a reaction to occur, molecules must:','o':['Collide with sufficient energy and correct orientation','Collide with any energy','Be in same phase','Have similar masses'],'ci':0,'e':'Effective collisions require energy ≥ Ea and proper geometry.'},
{'s':'Chemistry','y':2012,'q':'In a reversible reaction at equilibrium, the rate of forward reaction equals:','o':['Rate of reverse reaction','Zero','Maximum','Infinity'],'ci':0,'e':'Equilibrium = dynamic balance of forward and reverse rates.'},
{'s':'Chemistry','y':2013,'q':'Le Chatelier\'s principle states that a system at equilibrium will:','o':['Respond to oppose a stress','Always shift to products','Always shift to reactants','Remain unchanged'],'ci':0,'e':'The system adjusts to minimise the effect of an external change.'},
{'s':'Chemistry','y':2014,'q':'If pressure is increased on a gaseous equilibrium, the system shifts toward:','o':['Fewer moles of gas','More moles of gas','No shift','The side with higher volume'],'ci':0,'e':'Increase pressure favours the side with fewer gas moles.'},
{'s':'Chemistry','y':2015,'q':'For the equilibrium N₂ + 3H₂ ⇌ 2NH₃, increasing temperature:','o':['Shifts to reactants (endothermic forward)','Shifts to products','No effect','Increases pressure'],'ci':0,'e':'Forward reaction is exothermic; increasing T shifts to reactants (absorbs heat).'},
{'s':'Chemistry','y':2016,'q':'A catalyst affects equilibrium by:','o':['Increasing rate of both forward and reverse reactions equally','Shifting equilibrium to products','Shifting equilibrium to reactants','Changing ΔH'],'ci':0,'e':'Catalyst speeds up both directions equally; equilibrium position unchanged.'},
{'s':'Chemistry','y':2017,'q':'The equilibrium constant Kc for a reaction depends on:','o':['Temperature','Concentration','Pressure','Volume'],'ci':0,'e':'Kc is constant at a given temperature.'},
{'s':'Chemistry','y':2018,'q':'If Kc is large (>>1), the equilibrium:','o':['Favours products','Favours reactants','Is at middle','No reaction'],'ci':0,'e':'Large Kc → products dominate at equilibrium.'},
{'s':'Chemistry','y':2019,'q':'The entropy of a system:','o':['Increases with disorder','Decreases with disorder','Is always zero','Is independent of temperature'],'ci':0,'e':'Entropy is a measure of randomness/disorder.'},
{'s':'Chemistry','y':2020,'q':'For a spontaneous reaction, the Gibbs free energy change ΔG is:','o':['Negative','Positive','Zero','Undefined'],'ci':0,'e':'Spontaneous → ΔG < 0.'},
{'s':'Chemistry','y':2021,'q':'ΔG = ΔH - TΔS. At high temperature, a reaction with positive ΔS becomes:','o':['More spontaneous','Less spontaneous','Unchanged','Non‑spontaneous'],'ci':0,'e':'For ΔH positive, ΔS positive → spontaneous at high T.'},
{'s':'Chemistry','y':2022,'q':'A reaction with ΔH > 0 and ΔS < 0 is:','o':['Non‑spontaneous at all temperatures','Spontaneous at all temperatures','Spontaneous only at low T','Spontaneous only at high T'],'ci':0,'e':'ΔG = ΔH - TΔS → both terms positive → ΔG always positive.'},
{'s':'Chemistry','y':2023,'q':'The enthalpy of combustion is always:','o':['Negative','Positive','Zero','Variable'],'ci':0,'e':'Combustion is exothermic → ΔH negative.'},
{'s':'Chemistry','y':2024,'q':'Hess\'s law states that enthalpy change depends only on:','o':['Initial and final states','Pathway','Number of steps','Catalyst'],'ci':0,'e':'Hess\'s law: enthalpy is a state function.'},
{'s':'Chemistry','y':2025,'q':'Bond breaking is:','o':['Endothermic','Exothermic','Neither','Both'],'ci':0,'e':'Breaking bonds requires energy (endothermic).'},
{'s':'Chemistry','y':2026,'q':'Bond formation is:','o':['Exothermic','Endothermic','Neither','Both'],'ci':0,'e':'Forming bonds releases energy (exothermic).'},

// ============================================================
// SECTION 7: ORGANIC CHEMISTRY (Q431–Q500)
// ============================================================
{'s':'Chemistry','y':2000,'q':'The general formula for alkanes is:','o':['CₙH₂ₙ₊₂','CₙH₂ₙ','CₙH₂ₙ₋₂','CₙH₂ₙ₊₁'],'ci':0,'e':'Alkanes are saturated with formula CₙH₂ₙ₊₂.'},
{'s':'Chemistry','y':2001,'q':'The general formula for alkenes is:','o':['CₙH₂ₙ','CₙH₂ₙ₊₂','CₙH₂ₙ₋₂','CₙH₂ₙ₊₁'],'ci':0,'e':'Alkenes have one C=C bond → CₙH₂ₙ.'},
{'s':'Chemistry','y':2002,'q':'The functional group of alcohols is:','o':['-OH','-COOH','-CHO','-CO-'],'ci':0,'e':'Alcohols contain the hydroxyl group (−OH).'},
{'s':'Chemistry','y':2003,'q':'The functional group of carboxylic acids is:','o':['-COOH','-OH','-CHO','-CO-'],'ci':0,'e':'Carboxylic acids have the carboxyl group (-COOH).'},
{'s':'Chemistry','y':2004,'q':'The IUPAC name for CH₃CH₂CH₂OH is:','o':['Propan-1-ol','Propan-2-ol','Propanal','Propanone'],'ci':0,'e':'CH₃CH₂CH₂OH = propan‑1‑ol (OH on carbon 1).'},
{'s':'Chemistry','y':2005,'q':'The compound CH₃COOH is called:','o':['Ethanoic acid','Ethanol','Ethanal','Ethyl acetate'],'ci':0,'e':'CH₃COOH = ethanoic acid (acetic acid).'},
{'s':'Chemistry','y':2006,'q':'Isomers are compounds with the same:','o':['Molecular formula but different structure','Empirical formula but different molecular formula','Functional group','Boiling point'],'ci':0,'e':'Isomers have same molecular formula but different structural arrangement.'},
{'s':'Chemistry','y':2007,'q':'How many structural isomers does C₄H₁₀ have?','o':['2','3','4','5'],'ci':0,'e':'Butane has 2 isomers: n‑butane and isobutane (2‑methylpropane).'},
{'s':'Chemistry','y':2008,'q':'C₅H₁₂ has how many structural isomers?','o':['3','4','5','2'],'ci':0,'e':'Pentane has 3 isomers: n‑pentane, isopentane, neopentane.'},
{'s':'Chemistry','y':2009,'q':'Which of the following is an alkene?','o':['C₂H₄','C₂H₆','C₃H₈','C₄H₁₀'],'ci':0,'e':'C₂H₄ = ethene (alkene).'},
{'s':'Chemistry','y':2010,'q':'The type of reaction that converts an alkene to an alkane is:','o':['Hydrogenation (addition)','Substitution','Elimination','Oxidation'],'ci':0,'e':'Alkene + H₂ → alkane (addition of hydrogen).'},
{'s':'Chemistry','y':2011,'q':'Benzene has the formula:','o':['C₆H₆','C₆H₁₂','C₆H₁₀','C₆H₅'],'ci':0,'e':'Benzene is C₆H₆ (aromatic).'},
{'s':'Chemistry','y':2012,'q':'The functional group of ketones is:','o':['-CO- (carbonyl)','-CHO','-COOH','-OH'],'ci':0,'e':'Ketones have R‑CO‑R\' (carbonyl group bonded to two carbons).'},
{'s':'Chemistry','y':2013,'q':'Aldehydes have the general formula R‑CHO. The functional group is:','o':['-CHO','-COOH','-OH','-CO-'],'ci':0,'e':'Aldehydes have the carbonyl group at the end of the chain (-CHO).'},
{'s':'Chemistry','y':2014,'q':'The ester functional group is:','o':['-COO-','-COOH','-OH','-CO-'],'ci':0,'e':'Ester linkage: R‑COO‑R\'.'},
{'s':'Chemistry','y':2015,'q':'The saponification reaction is the hydrolysis of:','o':['Esters','Acids','Alcohols','Alkanes'],'ci':0,'e':'Saponification = hydrolysis of esters (fats/oils) with NaOH to form soap.'},
{'s':'Chemistry','y':2016,'q':'Which of the following is a polymer?','o':['Polyethylene','Glucose','Ethanol','Methane'],'ci':0,'e':'Polyethylene is a polymer (many repeating ethene units).'},
{'s':'Chemistry','y':2017,'q':'The monomer of poly(ethene) is:','o':['Ethene','Ethane','Ethylene','Both A and C'],'ci':3,'e':'Ethene (or ethylene) is the monomer.'},
{'s':'Chemistry','y':2018,'q':'The addition polymerisation of propene gives:','o':['Polypropene','Polyethene','PVC','Teflon'],'ci':0,'e':'Propene → polypropene (polypropylene).'},
{'s':'Chemistry','y':2019,'q':'Which of the following is a condensation polymer?','o':['Nylon','Polyethene','Polypropene','PVC'],'ci':0,'e':'Nylon is a condensation polymer (amide bonds).'},
{'s':'Chemistry','y':2020,'q':'The IUPAC name for CH₃CH₂CHO is:','o':['Propanal','Propanone','Propanoic acid','Propan-1-ol'],'ci':0,'e':'CH₃CH₂CHO = propanal (aldehyde).'},
{'s':'Chemistry','y':2021,'q':'The IUPAC name for CH₃COCH₃ is:','o':['Propanone','Acetone','Propanal','Propanol'],'ci':0,'e':'CH₃COCH₃ = propanone (acetone).'},
{'s':'Chemistry','y':2022,'q':'An organic compound that gives a silver mirror with Tollen\'s reagent is:','o':['Aldehyde','Ketone','Alcohol','Carboxylic acid'],'ci':0,'e':'Aldehydes reduce Tollens\' reagent to metallic silver (positive test).'},
{'s':'Chemistry','y':2023,'q':'Fehling\'s solution is reduced by:','o':['Aldehydes','Ketones','Alkenes','Aromatics'],'ci':0,'e':'Aldehydes (except some) reduce Fehling\'s to red Cu₂O.'},
{'s':'Chemistry','y':2024,'q':'The process of converting glucose to ethanol is called:','o':['Fermentation','Distillation','Hydrolysis','Oxidation'],'ci':0,'e':'Fermentation: glucose → ethanol + CO₂ (enzymes).'},
{'s':'Chemistry','y':2025,'q':'The major product of the dehydration of ethanol is:','o':['Ethene','Ethane','Ethyne','Ether'],'ci':0,'e':'Alcohol → alkene + H₂O (dehydration).'},
{'s':'Chemistry','y':2026,'q':'Which of the following is a primary alcohol?','o':['Ethanol','Propan-2-ol','2-methylpropan-2-ol','Cyclohexanol'],'ci':0,'e':'Primary alcohol: −OH on a carbon attached to only one other carbon (ethanol).'},
{'s':'Chemistry','y':2000,'q':'Which of the following is a secondary alcohol?','o':['Propan-2-ol','Ethanol','Propan-1-ol','2-methylpropan-2-ol'],'ci':0,'e':'Propan‑2‑ol: OH on carbon 2 attached to two carbons.'},
{'s':'Chemistry','y':2001,'q':'Which is a tertiary alcohol?','o':['2-methylpropan-2-ol','Propan-2-ol','Ethanol','Butan-1-ol'],'ci':0,'e':'Tertiary: OH on carbon attached to three carbons.'},
{'s':'Chemistry','y':2002,'q':'The acid used in the esterification of ethanol to form ethyl ethanoate is:','o':['Ethanoic acid','Sulphuric acid','Hydrochloric acid','Nitric acid'],'ci':0,'e':'Ethanol + ethanoic acid → ethyl ethanoate (esterification).'},
{'s':'Chemistry','y':2003,'q':'The process of converting alkenes to alkanes is called:','o':['Hydrogenation','Halogenation','Hydration','Polymerisation'],'ci':0,'e':'Addition of H₂ across double bond.'},
{'s':'Chemistry','y':2004,'q':'The process of converting alkenes to alcohols is:','o':['Hydration','Hydrogenation','Dehydration','Cracking'],'ci':0,'e':'Alkene + H₂O → alcohol (hydration, acid catalyst).'},
{'s':'Chemistry','y':2005,'q':'The chloroalkane obtained from the reaction of ethane with chlorine is:','o':['Chloroethane','Dichloroethane','Chloromethane','Tetrachloroethane'],'ci':0,'e':'Ethane + Cl₂ (substitution) → chloroethane.'},
{'s':'Chemistry','y':2006,'q':'The reaction of benzene with nitric acid in the presence of sulphuric acid is:','o':['Nitration','Halogenation','Friedel‑Crafts','Hydrogenation'],'ci':0,'e':'Nitration: benzene + HNO₃/H₂SO₄ → nitrobenzene.'},
{'s':'Chemistry','y':2007,'q':'Benzene undergoes substitution reactions instead of addition because:','o':['Aromatic stabilisation (delocalised π electrons)','It is unsaturated','It has a ring','It is polar'],'ci':0,'e':'Aromaticity confers stability, so addition would break stabilisation.'},
{'s':'Chemistry','y':2008,'q':'The formula for the phenyl group is:','o':['C₆H₅','C₆H₆','C₆H₄','C₆H₇'],'ci':0,'e':'Phenyl = C₆H₅− (benzene minus one H).'},
{'s':'Chemistry','y':2009,'q':'Which of the following is an aromatic hydrocarbon?','o':['Benzene','Cyclohexane','Hexene','Hexane'],'ci':0,'e':'Benzene is aromatic; others are aliphatic.'},
{'s':'Chemistry','y':2010,'q':'The gas used in the hydrogenation of vegetable oils is:','o':['H₂','O₂','N₂','Cl₂'],'ci':0,'e':'Hydrogenation uses H₂ to convert unsaturated fats to saturated.'},
{'s':'Chemistry','y':2011,'q':'Natural gas is mainly:','o':['Methane','Ethane','Propane','Butane'],'ci':0,'e':'Natural gas is predominantly CH₄ (methane).'},
{'s':'Chemistry','y':2012,'q':'Petroleum is separated into fractions by:','o':['Fractional distillation','Crystallisation','Filtration','Chromatography'],'ci':0,'e':'Fractional distillation separates hydrocarbons by boiling point.'},
{'s':'Chemistry','y':2013,'q':'Cracking is the process of breaking:','o':['Large hydrocarbons into smaller ones','Small hydrocarbons into larger ones','Alkanes into alkenes','Alkenes into alkanes'],'ci':0,'e':'Cracking breaks long chain alkanes into shorter alkenes/alkanes.'},
{'s':'Chemistry','y':2014,'q':'The octane number of petrol is increased by:','o':['Adding branched hydrocarbons','Adding straight chains','Adding oxygen','Adding water'],'ci':0,'e':'Branched hydrocarbons have higher octane numbers (anti‑knock).'},
{'s':'Chemistry','y':2015,'q':'Biodiesel is produced from:','o':['Vegetable oils','Petroleum','Coal','Natural gas'],'ci':0,'e':'Biodiesel is made from renewable sources like vegetable oils.'},
{'s':'Chemistry','y':2016,'q':'The soap molecule has a:','o':['Hydrophilic head and hydrophobic tail','Hydrophobic head and hydrophilic tail','Both hydrophobic','Both hydrophilic'],'ci':0,'e':'Soap has a polar (hydrophilic) head and non‑polar (hydrophobic) tail.'},
{'s':'Chemistry','y':2017,'q':'The effect of soap in hard water is:','o':['Scum formation','Lathering easily','Cleaning better','No effect'],'ci':0,'e':'Soap reacts with Ca²⁺/Mg²⁺ to form insoluble scum.'},
{'s':'Chemistry','y':2018,'q':'Detergents are better than soaps in hard water because:','o':['They do not form scum','They are more soluble','They are cheaper','They are biodegradable'],'ci':0,'e':'Detergents contain sulfonate groups that do not precipitate with hard water ions.'},
{'s':'Chemistry','y':2019,'q':'The polymer used to make polythene bags is:','o':['Polyethene','PVC','Polypropene','Polystyrene'],'ci':0,'e':'Polyethene (polyethylene) is used for plastic bags.'},
{'s':'Chemistry','y':2020,'q':'PVC is a polymer of:','o':['Vinyl chloride','Ethene','Propene','Styrene'],'ci':0,'e':'PVC = poly(vinyl chloride) from vinyl chloride monomer.'},
{'s':'Chemistry','y':2021,'q':'Teflon is a polymer of:','o':['Tetrafluoroethene','Ethene','Propene','Vinyl chloride'],'ci':0,'e':'Teflon is polytetrafluoroethylene (PTFE).'},
{'s':'Chemistry','y':2022,'q':'Nylon is a:','o':['Synthetic polyamide','Natural polymer','Polysaccharide','Protein'],'ci':0,'e':'Nylon is a synthetic polyamide (condensation polymer).'},
{'s':'Chemistry','y':2023,'q':'Cellulose is a polymer of:','o':['Glucose','Fructose','Sucrose','Maltose'],'ci':0,'e':'Cellulose is a polysaccharide of β‑glucose units.'},
{'s':'Chemistry','y':2024,'q':'Starch is a polymer of:','o':['α‑glucose','β‑glucose','Fructose','Galactose'],'ci':0,'e':'Starch is made of α‑D‑glucose units.'},
{'s':'Chemistry','y':2025,'q':'Proteins are polymers of:','o':['Amino acids','Nucleotides','Monosaccharides','Fatty acids'],'ci':0,'e':'Proteins are polypeptides made from amino acids.'},
{'s':'Chemistry','y':2026,'q':'DNA is a polymer of:','o':['Nucleotides','Amino acids','Monosaccharides','Glycerol'],'ci':0,'e':'DNA is a polynucleotide.'},

// ============================================================
// SECTION 8: ANALYTICAL & ENVIRONMENTAL (Q501–Q550)
// ============================================================
{'s':'Chemistry','y':2000,'q':'The pH of a 0.1 M solution of a strong acid is:','o':['1','2','3','0.1'],'ci':0,'e':'pH = -log(0.1) = 1.'},
{'s':'Chemistry','y':2001,'q':'The pH of pure water at 25°C is:','o':['7','6','8','5'],'ci':0,'e':'Neutral water has pH = 7 at 25°C.'},
{'s':'Chemistry','y':2002,'q':'The product of [H⁺] and [OH⁻] in water at 25°C is:','o':['1×10⁻¹⁴','1×10⁻⁷','1×10⁻¹','1×10⁻⁵'],'ci':0,'e':'Kw = [H⁺][OH⁻] = 1×10⁻¹⁴ at 25°C.'},
{'s':'Chemistry','y':2003,'q':'Which of the following is a greenhouse gas?','o':['CO₂','O₂','N₂','Ar'],'ci':0,'e':'CO₂ is a greenhouse gas (traps infrared radiation).'},
{'s':'Chemistry','y':2004,'q':'Acid rain is mainly caused by:','o':['SO₂ and NOₓ','CO₂','CO','CH₄'],'ci':0,'e':'SO₂ and NOₓ form sulphuric and nitric acids in rain.'},
{'s':'Chemistry','y':2005,'q':'The ozone layer is depleted by:','o':['CFCs','CO₂','SO₂','NOₓ'],'ci':0,'e':'CFCs release chlorine radicals that destroy ozone.'},
{'s':'Chemistry','y':2006,'q':'Photochemical smog is caused by:','o':['NOₓ and hydrocarbons','SO₂ and dust','CO₂ and H₂O','CFCs'],'ci':0,'e':'NOₓ + VOCs react in sunlight to form photochemical smog.'},
{'s':'Chemistry','y':2007,'q':'The pH of acid rain is usually:','o':['<5.6','>5.6','=7','>7'],'ci':0,'e':'Normal rain pH ~5.6 due to CO₂; acid rain is lower (<5.6).'},
{'s':'Chemistry','y':2008,'q':'The process of removing hardness from water is called:','o':['Softening','Hardening','Distillation','Filtration'],'ci':0,'e':'Water softening removes Ca²⁺/Mg²⁺ ions.'},
{'s':'Chemistry','y':2009,'q':'Temporary hardness is caused by:','o':['Ca(HCO₃)₂','CaSO₄','MgCl₂','NaCl'],'ci':0,'e':'Temporary hardness is due to bicarbonates; removed by boiling.'},
{'s':'Chemistry','y':2010,'q':'Permanent hardness is due to:','o':['Sulphates and chlorides of Ca/Mg','Bicarbonates of Ca/Mg','Nitrates','Carbonates'],'ci':0,'e':'Permanent hardness is caused by soluble sulfates and chlorides.'},
{'s':'Chemistry','y':2011,'q':'Temporary hardness can be removed by:','o':['Boiling','Adding soap','Adding washing soda','Filtration'],'ci':0,'e':'Boiling decomposes bicarbonates to insoluble carbonates.'},
{'s':'Chemistry','y':2012,'q':'The water‑gas shift reaction is:','o':['CO + H₂O → CO₂ + H₂','C + H₂O → CO + H₂','CH₄ + H₂O → CO + 3H₂','CO₂ + H₂ → CO + H₂O'],'ci':0,'e':'Water‑gas shift: CO + H₂O ⇌ CO₂ + H₂ (used for H₂ production).'},
{'s':'Chemistry','y':2013,'q':'Which of the following is a pollutant from vehicle exhaust?','o':['CO','CO₂','NOₓ','All of these'],'ci':3,'e':'All are emitted from vehicles.'},
{'s':'Chemistry','y':2014,'q':'The catalytic converter in cars converts:','o':['CO and NOx to CO₂ and N₂','CO₂ to O₂','SO₂ to SO₃','HC to CO₂'],'ci':0,'e':'Catalytic converters oxidise CO and reduce NOx.'},
{'s':'Chemistry','y':2015,'q':'The process of treating water with chlorine is called:','o':['Chlorination','Ozonation','Fluoridation','Sedimentation'],'ci':0,'e':'Chlorination disinfects water by killing pathogens.'},
{'s':'Chemistry','y':2016,'q':'Which of the following is a primary pollutant?','o':['CO','NO₂','SO₂','All of these'],'ci':3,'e':'All are emitted directly (primary pollutants).'},
{'s':'Chemistry','y':2017,'q':'A secondary pollutant is:','o':['O₃ (ozone)','CO','NO','SO₂'],'ci':0,'e':'Ozone is formed in the atmosphere from NOx and VOCs (secondary).'},
{'s':'Chemistry','y':2018,'q':'The chemical formula of ozone is:','o':['O₃','O₂','O','O₄'],'ci':0,'e':'Ozone is trioxygen (O₃).'},
{'s':'Chemistry','y':2019,'q':'The function of a buffer is to:','o':['Maintain pH','Increase pH','Decrease pH','Change colour'],'ci':0,'e':'Buffers resist changes in pH.'},
{'s':'Chemistry','y':2020,'q':'The indicator used in the titration of a weak acid with a strong base is:','o':['Phenolphthalein','Methyl orange','Litmus','Bromothymol blue'],'ci':0,'e':'Phenolphthalein (pH range 8‑10) is suitable for weak acid/strong base.'},
{'s':'Chemistry','y':2021,'q':'The equivalence point of a titration is when:','o':['Moles of acid = moles of base','pH = 7','Indicator changes colour','Reaction stops'],'ci':0,'e':'Equivalence point = stoichiometric completion.'},
{'s':'Chemistry','y':2022,'q':'The end point of a titration is when:','o':['Indicator changes colour','Moles are equal','pH is neutral','Reaction is complete'],'ci':0,'e':'End point is the point at which the indicator changes colour.'},
{'s':'Chemistry','y':2023,'q':'Which of the following is used as a primary standard in acid‑base titrations?','o':['Na₂CO₃','HCl','NaOH','H₂SO₄'],'ci':0,'e':'Na₂CO₃ is a primary standard (pure, stable, high molar mass).'},
{'s':'Chemistry','y':2024,'q':'A secondary standard is a substance whose concentration is determined by:','o':['Titration against a primary standard','Direct weighing','Dilution','Calculation'],'ci':0,'e':'Secondary standards are standardised using primary standards.'},
{'s':'Chemistry','y':2025,'q':'The concentration of a solution can be expressed as:','o':['Molarity, molality, normality','Only molarity','Only molality','Only normality'],'ci':0,'e':'Various concentration units exist.'},
{'s':'Chemistry','y':2026,'q':'Molality is defined as moles of solute per:','o':['kg of solvent','L of solution','kg of solution','L of solvent'],'ci':0,'e':'Molality = moles solute / kg solvent (not solution).'},
];
