name: naijalearn
<<<<<<< HEAD
description: "NaijaLearn - JAMB & WAEC CBT Practice"
=======
description: "NaijaLearn - Nigeria's Video Platform"
>>>>>>> 27dd778 (Rename package to com.naijalearn.app)
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
