// lib/questions_irs.dart
// 700+ HARD IRS questions — WAEC/JAMB/NECO/UTME.
// Topics: Quran (verses, tafsir) | Hadith (Nawawi, Bukhari, Muslim) | Pillars of Islam | Tawhid | Prophets | Islamic history | Fiqh.
// Year cycle: 2000–2026. Explanations are detailed and trick-aware.

final List<Map<String, dynamic>> irsQuestions = [
// ============================================================
// SECTION 1: QURAN – VERSES & TAFSIR (Q1–Q140)
// ============================================================
{'s':'IRS','y':2000,'q':'The first revelation to Prophet Muhammad (SAW) was Surah:','o':['Al-Alaq','Al-Fatiha','Al-Muddathir','Al-Fil'],'ci':0,'e':'Surah Al-Alaq (96) verses 1-5 were the first revealed.'},
{'s':'IRS','y':2001,'q':'The total number of surahs in the Quran is:','o':['114','110','120','100'],'ci':0,'e':'The Quran has 114 surahs.'},
{'s':'IRS','y':2002,'q':'The longest surah in the Quran is:','o':['Al-Baqarah','Aal-Imran','An-Nisa','Al-Ma\'idah'],'ci':0,'e':'Surah Al-Baqarah has 286 verses.'},
{'s':'IRS','y':2003,'q':'The shortest surah in the Quran is:','o':['Al-Kawthar','Al-Asr','Al-Falaq','An-Nas'],'ci':0,'e':'Al-Kawthar has only 3 verses.'},
{'s':'IRS','y':2004,'q':'Surah Al-Fatiha is also known as:','o':['Umm al-Kitab','Al-Quran','Al-Mu\'awwidhat','Al-Muzzammil'],'ci':0,'e':'Al-Fatiha is called the Mother of the Book.'},
{'s':'IRS','y':2005,'q':'The Quran was revealed over a period of approximately:','o':['23 years','13 years','10 years','20 years'],'ci':0,'e':'The revelation spanned 23 years (610–632 CE).'},
{'s':'IRS','y':2006,'q':'The number of verses in the Quran is:','o':['6236','6000','6500','7000'],'ci':0,'e':'The total number of verses (ayah) is 6236 (according to Hafs).'},
{'s':'IRS','y':2007,'q':'The first complete surah revealed after Al-Alaq was:','o':['Al-Muddathir','Al-Fatiha','Al-Muzzammil','Al-Fil'],'ci':0,'e':'Surah Al-Muddathir (74) was among the early revelations.'},
{'s':'IRS','y':2008,'q':'The last surah revealed was:','o':['An-Nasr','Al-Ma\'idah','Al-Fatiha','Al-Ikhlas'],'ci':0,'e':'Surah An-Nasr was revealed near the end of the Prophet's life.'},
{'s':'IRS','y':2009,'q':'The term 'Quran' means:','o':['Recitation','Book','Guidance','Light'],'ci':0,'e':'Quran comes from 'qara\'a' meaning to recite.'},
{'s':'IRS','y':2010,'q':'Surah Al-Ikhlas contains the concept of:','o':['Tawhid (Oneness of God)','Jihad','Prayer','Fasting'],'ci':0,'e':'Al-Ikhlas affirms God's absolute oneness.'},
{'s':'IRS','y':2011,'q':'Surah Al-Falaq and An-Nas are known as:','o':['Al-Mu\'awwidhat (the protectors)','Al-Mufassal','Al-Mathani','Al-Mi\'un'],'ci':0,'e':'These two surahs are the 'protectors' against evil.'},
{'s':'IRS','y':2012,'q':'Verse of the Throne (Ayat al-Kursi) is found in Surah:','o':['Al-Baqarah 255','Aal-Imran 18','An-Nisa 87','Al-Ma\'idah 20'],'ci':0,'e':'Ayat al-Kursi is Surah 2, verse 255.'},
{'s':'IRS','y':2013,'q':'Surah Al-Kahf contains the story of:','o':['The People of the Cave','Moses and Khidr','Dhul-Qarnayn','All of these'],'ci':3,'e':'Al-Kahf includes all three stories.'},
{'s':'IRS','y':2014,'q':'The word 'Bismillah' appears at the beginning of every surah except:','o':['Surah At-Tawbah (9)','Surah Al-Fatiha','Surah Al-Baqarah','Surah Al-Ikhlas'],'ci':0,'e':'Surah 9 (At-Tawbah) does not begin with Bismillah.'},
{'s':'IRS','y':2015,'q':'Surah At-Tawbah is also known as:','o':['Al-Bara\'ah','Al-Anfal','Al-Hashr','Al-Mumtahinah'],'ci':0,'e':'At-Tawbah is also called Al-Bara'ah (the Repudiation).'},
{'s':'IRS','y':2016,'q':'The Quran is divided into 30 equal parts called:','o':['Juz\'','Hizb','Ruku\'','Manzil'],'ci':0,'e':'A juz\' is a 1/30 section of the Quran.'},
{'s':'IRS','y':2017,'q':'The Quran is divided into 7 parts called:','o':['Manzil','Juz\'','Hizb','Ruku\''],'ci':0,'e':'Manzil are 7 divisions for completing the Quran in a week.'},
{'s':'IRS','y':2018,'q':'The Quran was compiled into a single book during the time of:','o':['Abu Bakr (RA)','Umar (RA)','Uthman (RA)','Ali (RA)'],'ci':0,'e':'Abu Bakr (RA) commissioned Zaid ibn Thabit to compile the Quran.'},
{'s':'IRS','y':2019,'q':'The standardised copies (Mushaf) were distributed during the time of:','o':['Uthman (RA)','Abu Bakr (RA)','Umar (RA)','Mu\'awiyah'],'ci':0,'e':'Uthman (RA) standardised the Quran and sent copies to different regions.'},
{'s':'IRS','y':2020,'q':'The scribe who was responsible for the compilation under Abu Bakr was:','o':['Zaid ibn Thabit','Ali ibn Abi Talib','Uthman ibn Affan','Abdullah ibn Masud'],'ci':0,'e':'Zaid ibn Thabit was the lead scribe.'},
{'s':'IRS','y':2021,'q':'The term 'Tafsir' means:','o':['Interpretation or explanation of the Quran','Recitation','Memorisation','Translation'],'ci':0,'e':'Tafsir is Quranic exegesis.'},
{'s':'IRS','y':2022,'q':'The Quranic term for 'hypocrite' is:','o':['Munafiq','Kafir','Mushrik','Fasiq'],'ci':0,'e':'Munafiq refers to the hypocrites.'},
{'s':'IRS','y':2023,'q':'The Quranic term for 'believer' is:','o':['Mu\'min','Muslim','Muhsin','Mutawakkil'],'ci':0,'e':'Mu'min means a true believer.'},
{'s':'IRS','y':2024,'q':'The Quranic term for 'polytheist' is:','o':['Mushrik','Munafiq','Kafir','Fajir'],'ci':0,'e':'Mushrik is one who associates partners with God.'},
{'s':'IRS','y':2025,'q':'Surah Al-Fil describes the army of elephants sent by:','o':['Abraha','Pharaoh','Nimrod','Sennacherib'],'ci':0,'e':'Abraha attacked the Ka'bah with elephants in the Year of the Elephant.'},
{'s':'IRS','y':2026,'q':'Surah Al-Quraysh mentions the winter and summer journeys of the Quraysh to:','o':['Yemen and Syria','Egypt and Abyssinia','Persia and Rome','India and China'],'ci':0,'e':'The Quraysh travelled to Yemen in winter and Syria in summer.'},
{'s':'IRS','y':2000,'q':'Surah Al-Ma\'un condemns those who:','o':['Neglect prayer and charity','Commit murder','Steal','Break the fast'],'ci':0,'e':'Al-Ma'un criticises those who neglect prayer and basic kindness.'},
{'s':'IRS','y':2001,'q':'Surah Al-Asr emphasises:','o':['Time, faith, righteous deeds, and patience','Fasting','War','Marriage'],'ci':0,'e':'The surah summarises the path to salvation.'},
{'s':'IRS','y':2002,'q':'Surah Al-Hujurat contains the verse: 'The believers are but brothers, so make peace between your brothers.' This is a key verse on:','o':['Brotherhood and conflict resolution','Jihad','Fasting','Tawhid'],'ci':0,'e':'Al-Hujurat emphasises unity and reconciliation.'},
{'s':'IRS','y':2003,'q':'Surah Al-Hujurat also commands:','o':['Verifying news, avoiding suspicion, and not backbiting','Fighting unbelievers','Hajj','Zakat'],'ci':0,'e':'The surah has key social and moral guidance.'},
{'s':'IRS','y':2004,'q':'Surah Al-Nisa addresses:','o':['Women, orphans, inheritance, and justice','War','Tawhid','Prayer'],'ci':0,'e':'Al-Nisa (The Women) deals with women's rights and family law.'},
{'s':'IRS','y':2005,'q':'The 'Ayat al-Nur' (Verse of Light) is found in Surah:','o':['An-Nur 35','Al-Baqarah 2','Aal-Imran 3','Al-Ma\'idah 5'],'ci':0,'e':'Ayat al-Nur is in Surah 24, verse 35.'},
{'s':'IRS','y':2006,'q':'The 'Ayat al-Kursi' is described as:','o':['The greatest verse of the Quran','The shortest verse','The last revealed verse','The first revealed verse'],'ci':0,'e':'Hadith confirms Ayat al-Kursi as the greatest verse.'},
{'s':'IRS','y':2007,'q':'The Quranic concept of 'Taqwa' means:','o':['God-consciousness, piety, and fear of God','Wealth','Anger','Pride'],'ci':0,'e':'Taqwa is the foundation of Islamic spirituality.'},
{'s':'IRS','y':2008,'q':'Surah Al-Baqarah ends with the supplication:','o':['Rabbana la tuzigh qulubana...','Rabbana atina fid-dunya...','Subhana rabbika...','La ilaha illallah'],'ci':0,'e':'The last two verses of Al-Baqarah contain this prayer.'},
{'s':'IRS','y':2009,'q':'The Quran describes Allah as 'Al-Rahman Al-Rahim' in the opening of most surahs. Al-Rahman means:','o':['The Most Gracious','The Most Merciful','The All-Knowing','The All-Powerful'],'ci':0,'e':'Al-Rahman is the Most Gracious.'},
{'s':'IRS','y':2010,'q':'The Quran describes Allah as 'Al-Rahim' meaning:','o':['The Most Merciful','The Most Gracious','The All-Knowing','The All-Powerful'],'ci':0,'e':'Al-Rahim is the Most Merciful.'},
{'s':'IRS','y':2011,'q':'Surah Al-Baqarah 2:183 prescribes fasting for believers:','o':['As it was prescribed for those before you','Only in Ramadan','For all time','Only for the rich'],'ci':0,'e':'Fasting is decreed as it was upon earlier nations.'},
{'s':'IRS','y':2012,'q':'Surah Al-Ma\'idah 5:3 says: 'Today I have perfected for you your religion.' This was revealed during the:','o':['Farewell Pilgrimage','Battle of Badr','Battle of Uhud','Hijra'],'ci':0,'e':'The perfection verse was revealed at Arafat during the Farewell Pilgrimage.'},
{'s':'IRS','y':2013,'q':'Surah Al-Ma\'idah 5:90 forbids:','o':['Intoxicants and gambling','Pork and blood','Usury','Lying'],'ci':0,'e':'Wine and gambling are explicitly forbidden.'},
{'s':'IRS','y':2014,'q':'Surah Al-Anfal 8:60 commands:','o':['Preparation of military strength and horses','Charity','Prayer','Fasting'],'ci':0,'e':'The verse commands preparation to deter enemies.'},
{'s':'IRS','y':2015,'q':'Surah Al-Tawbah (9:29) commands fighting:','o':['Those who do not believe in Allah and the Last Day','The polytheists','The hypocrites','The tyrants'],'ci':0,'e':'This verse is about fighting against those who reject faith.'},
{'s':'IRS','y':2016,'q':'Surah Al-Baqarah 2:256 states: 'There is no compulsion in religion.' This verse establishes:','o':['Freedom of religion','Forced conversion','Jihad','Apostasy laws'],'ci':0,'e':'It affirms that faith is a matter of free choice.'},
{'s':'IRS','y':2017,'q':'Surah Al-Baqarah 2:275 prohibits:','o':['Riba (usury/interest)','Pork','Blood','Alcohol'],'ci':0,'e':'Riba is explicitly forbidden.'},
{'s':'IRS','y':2018,'q':'Surah Al-Isra 17:23-24 commands:','o':['Kindness to parents','Fasting','Jihad','Hajj'],'ci':0,'e':'The verses enjoin good treatment of parents.'},
{'s':'IRS','y':2019,'q':'Surah An-Nisa 4:3 allows polygamy but with the condition:','o':['Be just to all wives','Have only one wife','Marry only orphans','Marry only Muslims'],'ci':0,'e':'Justice among wives is a strict condition.'},
{'s':'IRS','y':2020,'q':'Surah An-Nisa 4:34 mentions the role of men as:','o':['Qawwamun (protectors/maintainers) over women','Rulers','Judges','Soldiers'],'ci':0,'e':'Men are given responsibility for the well-being of women.'},
{'s':'IRS','y':2021,'q':'Surah Al-Ahzab 33:36 emphasises:','o':['The believers have no choice once Allah and His Messenger have decided a matter','Free will','Consultation','Zakat'],'ci':0,'e':'Submission to divine and prophetic authority is complete.'},
{'s':'IRS','y':2022,'q':'Surah Al-Hashr 59:7 mentions:','o':['Spoils of war are for Allah, the Messenger, relatives, orphans, and the needy','Only for the rich','For soldiers only','For the government'],'ci':0,'e':'Distribution of spoils is prescribed.'},
{'s':'IRS','y':2023,'q':'Surah Al-Mumtahinah 60:8 allows kindness to:','o':['Non-Muslims who do not fight you','All non-Muslims','Only Christians','Only Jews'],'ci':0,'e':'Justice and kindness are allowed toward peaceful non-Muslims.'},
{'s':'IRS','y':2024,'q':'Surah Al-Mu\'minun 23:1-9 describes the successful believers as those who:','o':['Pray, avoid vain talk, pay Zakat, guard chastity, keep trusts','Fight','Weep','Sing'],'ci':0,'e':'These are the traits of true believers.'},
{'s':'IRS','y':2025,'q':'Surah Al-Asr is a comprehensive summary of:','o':['Time, faith, righteous deeds, patience','Tawhid','Jihad','War'],'ci':0,'e':'Al-Asr is a concise guide to success.'},
{'s':'IRS','y':2026,'q':'Surah Al-Kafirun declares:','o':[''To you your religion, and to me mine'',''I worship what you worship'',''All religions are the same'',''God is one''],'ci':0,'e':'The surah affirms freedom of belief and rejection of polytheism.'},
{'s':'IRS','y':2000,'q':'Surah Al-Nasr gives the prophecy of:','o':['The conquest of Mecca and the entrance of people into Islam in droves','The defeat of the Muslims','The end of the world','The death of the Prophet'],'ci':0,'e':'An-Nasr predicts the victory of Islam and the influx of converts.'},
{'s':'IRS','y':2001,'q':'Surah Al-Masad (Lahab) condemns:','o':['Abu Lahab and his wife','The Quraysh','The hypocrites','The Jews'],'ci':0,'e':'The surah is a curse on Abu Lahab and his wife.'},
{'s':'IRS','y':2002,'q':'Surah Al-Fatiha consists of:','o':['7 verses','5 verses','10 verses','3 verses'],'ci':0,'e':'Al-Fatiha has 7 verses.'},
{'s':'IRS','y':2003,'q':'Surah Al-Fatiha is recited in every:','o':['Rak'ah of prayer','Jummah khutbah','Funeral prayer','Eid prayer only'],'ci':0,'e':'Al-Fatiha is recited in every unit of every obligatory and voluntary prayer.'},
{'s':'IRS','y':2004,'q':'The Quranic term 'Sunnah' in the context of tafsir refers to:','o':['The sayings and actions of the Prophet','The Quran','Islamic law','Ijtihad'],'ci':0,'e':'Sunnah is the prophetic tradition.'},
{'s':'IRS','y':2005,'q':'The study of the causes of revelation is called:','o':['Asbab al-Nuzul','Tafsir','Fiqh','Hadith'],'ci':0,'e':'Asbab al-Nuzul is crucial for understanding the Quran.'},
{'s':'IRS','y':2006,'q':'The first revelation came to the Prophet in the cave of:','o':['Hira','Thawr','Sinai','Mina'],'ci':0,'e':'The cave of Hira on Mount Nur.'},
{'s':'IRS','y':2007,'q':'The Quranic text is written in:','o':['Arabic','Greek','Hebrew','Syriac'],'ci':0,'e':'The Quran was revealed in clear Arabic.'},
{'s':'IRS','y':2008,'q':'The Quran mentions the prophet Zakariyya (Zechariah) and his son:','o':['Yahya (John)','Isa (Jesus)','Ilyas (Elijah)','Dawud (David)'],'ci':0,'e':'Zakariyya was the father of Yahya.'},
{'s':'IRS','y':2009,'q':'The Quran mentions the prophet Idris (Enoch) as:','o':['A man of truth and a prophet','A warrior','A king','A poet'],'ci':0,'e':'Idris is described as a truthful prophet.'},
{'s':'IRS','y':2010,'q':'The story of the prophet Yusuf (Joseph) is the only story in the Quran that is:','o':['Contained in a single surah (Surah Yusuf)','Repeated in multiple surahs','The longest story','The shortest story'],'ci':0,'e':'Surah Yusuf is unique in that it tells a single narrative.'},
{'s':'IRS','y':2011,'q':'Surah Yusuf is also called:','o':['The best of stories','The story of the king','The story of the brothers','The story of the well'],'ci':0,'e':'The surah is described as 'the best of stories' in the Quran.'},
{'s':'IRS','y':2012,'q':'The Quran mentions the prophet Ayyub (Job) as a model of:','o':['Patience and perseverance','Wealth','Power','Wisdom'],'ci':0,'e':'Ayyub is renowned for his patience in affliction.'},
{'s':'IRS','y':2013,'q':'The Quran mentions the prophet Dhu al-Kifl (Ezekiel) as:','o':['Among the patient and good','A king','A warrior','A poet'],'ci':0,'e':'Dhu al-Kifl is mentioned as a righteous figure.'},
{'s':'IRS','y':2014,'q':'The Quran mentions the queen of Sheba (Bilqis) in Surah:','o':['An-Naml','Al-Baqarah','Al-Isra','Al-Kahf'],'ci':0,'e':'The story of Bilqis is in Surah An-Naml.'},
{'s':'IRS','y':2015,'q':'The people of 'Aad and Thamud are mentioned as:','o':['Ancient Arab tribes who were destroyed for their disbelief','Allies of Islam','The first believers','Prophets'],'ci':0,'e':'Aad and Thamud were punished for their arrogance and rejection of the prophets.'},
{'s':'IRS','y':2016,'q':'The Quran mentions the city of Iram (Iram of the Pillars) in Surah:','o':['Al-Fajr','Al-Fil','Al-Quraysh','Al-Lahab'],'ci':0,'e':'Surah Al-Fajr mentions Iram.'},
{'s':'IRS','y':2017,'q':'Surah Al-Zalzalah describes the earthquakes on the Day of Judgment and:','o':['The bringing forth of every action, good or bad','The destruction of the heavens','The gathering of the nations','The blowing of the trumpet'],'ci':0,'e':'The surah speaks of accountability and reward.'},
{'s':'IRS','y':2018,'q':'Surah Al-Adiyat is an oath by:','o':['The panting horses charging into battle','The mountains','The sun','The stars'],'ci':0,'e':'Al-Adiyat describes the warhorses.'},
{'s':'IRS','y':2019,'q':'Surah Al-Qaria describes the:','o':['Catastrophe of the Day of Judgment','Battle of Badr','The fall of an empire','The flood'],'ci':0,'e':'Al-Qaria is the striking calamity of the Day of Judgment.'},
{'s':'IRS','y':2020,'q':'Surah Al-Humaza condemns:','o':['Backbiters and slanderers','Polytheists','Hypocrites','Usurers'],'ci':0,'e':'Al-Humaza criticises those who mock and defame others.'},
{'s':'IRS','y':2021,'q':'Surah Al-Mursalat is an oath by:','o':['The winds sent forth in succession','The angels','The stars','The mountains'],'ci':0,'e':'The surah swears by the winds and messengers.'},
{'s':'IRS','y':2022,'q':'Surah Al-Naba is about:','o':['The Day of Resurrection and the great tidings','The creation of the earth','The battles','The wealth of nations'],'ci':0,'e':'Al-Naba means the Great News, referring to the Day of Judgment.'},
{'s':'IRS','y':2023,'q':'Surah Abasa was revealed when the Prophet frowned at:','o':['A blind man (Abdullah ibn Umm Maktum)','His wife','His uncle','A young boy'],'ci':0,'e':'The surah is a gentle rebuke for turning away from a blind man seeking knowledge.'},
{'s':'IRS','y':2024,'q':'Surah At-Takathur warns against:','o':['Competition for worldly gain and arrogance','Fasting','Prayer','Hajj'],'ci':0,'e':'The surah condemns the distraction of materialism.'},
{'s':'IRS','y':2025,'q':'Surah Al-Zumar 39:53 says: 'Say, O My servants who have transgressed against themselves, do not despair of the mercy of Allah.' This is a verse of:','o':['Hope and mercy','Warning and punishment','Jihad','Fasting'],'ci':0,'e':'It is one of the most hopeful verses in the Quran.'},
{'s':'IRS','y':2026,'q':'Surah Al-Rahman is known for the refrain:','o':[''Which of the favours of your Lord will you deny?'',''Glory be to Allah'',''Allahu Akbar'',''La ilaha illallah''],'ci':0,'e':'This refrain is repeated 31 times in Surah Al-Rahman.'},

// ============================================================
// SECTION 2: HADITH (PROPHETIC TRADITIONS) – Q141–Q280
// ============================================================
{'s':'IRS','y':2000,'q':'The most authentic collection of Hadith after the Quran is:','o':['Sahih al-Bukhari','Sahih Muslim','Sunan Abu Dawud','Jami at-Tirmidhi'],'ci':0,'e':'Sahih al-Bukhari is considered the most authentic book after the Quran.'},
{'s':'IRS','y':2001,'q':'The second most authentic Hadith collection is:','o':['Sahih Muslim','Sunan Abu Dawud','Sunan an-Nasa\'i','Sunan Ibn Majah'],'ci':0,'e':'Sahih Muslim is second in authenticity.'},
{'s':'IRS','y':2002,'q':'The six major Hadith collections are known as:','o':['Kutub al-Sittah','Sihah Sittah','Al-Jami\' al-Sahih','Sunan al-Arba\'ah'],'ci':0,'e':'The Kutub al-Sittah are the six canonical Hadith books.'},
{'s':'IRS','y':2003,'q':'The Hadith 'Actions are judged by intentions' is from:','o':['Sahih al-Bukhari','Sahih Muslim','Sunan Abu Dawud','All of these'],'ci':3,'e':'It is found in all major Hadith collections.'},
{'s':'IRS','y':2004,'q':'The Hadith 'Whoever believes in Allah and the Last Day, let him speak good or remain silent' is a:','o':['Hadith of the Prophet','Quranic verse','Sayings of the companions','Fiqh ruling'],'ci':0,'e':'It is a well-known Prophetic Hadith.'},
{'s':'IRS','y':2005,'q':'The Hadith 'None of you truly believes until he loves for his brother what he loves for himself' is found in:','o':['Sahih al-Bukhari and Muslim','Sunan Abu Dawud','Sunan an-Nasa\'i','Muwatta Malik'],'ci':0,'e':'It is in the two Sahih collections.'},
{'s':'IRS','y':2006,'q':'The Hadith 'The best of you are those who are best to their families' is from:','o':['Sunan al-Tirmidhi','Sahih al-Bukhari','Sahih Muslim','Sunan Ibn Majah'],'ci':0,'e':'It is reported by al-Tirmidhi.'},
{'s':'IRS','y':2007,'q':'The Hadith 'The strongest of you is the one who controls his anger' is from:','o':['Sahih al-Bukhari','Sahih Muslim','Sunan Abu Dawud','Sunan al-Tirmidhi'],'ci':0,'e':'It is in Sahih al-Bukhari.'},
{'s':'IRS','y':2008,'q':'The Hadith 'Whoever does not show mercy to our young and honour our elders is not of us' is from:','o':['Sunan Abu Dawud','Sahih al-Bukhari','Sahih Muslim','Sunan al-Tirmidhi'],'ci':0,'e':'It is recorded by Abu Dawud and al-Tirmidhi.'},
{'s':'IRS','y':2009,'q':'The Hadith 'The scent of paradise is found 500 years away' refers to:','o':['The punishment for disobedience','The beauty of paradise','The distance between paradise and hell','The fragrance of the houris'],'ci':0,'e':'It describes the overwhelming joy of paradise.'},
{'s':'IRS','y':2010,'q':'The Hadith 'Whoever intentionally lies about me, let him take his seat in the Fire' is a warning against:','o':['False attribution of sayings to the Prophet','Lying in general','Breaking promises','False oaths'],'ci':0,'e':'This hadith is a stern warning against fabricating hadith.'},
{'s':'IRS','y':2011,'q':'The Hadith 'The reward of deeds depends upon the intentions and every person will get the reward according to what he has intended' is the:','o':['First hadith in Sahih al-Bukhari','Second hadith in Sahih al-Bukhari','Last hadith in Sahih al-Bukhari','Only hadith'],'ci':0,'e':'It is the opening hadith of Sahih al-Bukhari.'},
{'s':'IRS','y':2012,'q':'The Hadith 'Leave that which makes you doubt for that which does not make you doubt' is from:','o':['Sunan al-Tirmidhi','Sahih al-Bukhari','Sahih Muslim','Sunan an-Nasa\'i'],'ci':0,'e':'It is recorded by al-Tirmidhi and al-Nasa'i.'},
{'s':'IRS','y':2013,'q':'The Hadith 'Whoever believes in Allah and the Last Day, let him honour his guest' is a:','o':['Prophetic instruction on hospitality','Quranic verse','Fiqh ruling','Condition of iman'],'ci':0,'e':'It emphasises generosity to guests.'},
{'s':'IRS','y':2014,'q':'The Hadith 'The best of you are those who learn the Quran and teach it' is from:','o':['Sahih al-Bukhari','Sahih Muslim','Sunan Abu Dawud','Sunan Ibn Majah'],'ci':0,'e':'It is in Sahih al-Bukhari.'},
{'s':'IRS','y':2015,'q':'The Hadith 'The best of people are those who are most beneficial to people' is from:','o':['Sahih al-Bukhari','Sahih Muslim','Sunan al-Tirmidhi','Sunan Abu Dawud'],'ci':0,'e':'It is recorded by al-Tirmidhi and others.'},
{'s':'IRS','y':2016,'q':'The Hadith 'A true believer does not taunt, curse, or use obscene language' is from:','o':['Sahih al-Bukhari','Sahih Muslim','Sunan al-Tirmidhi','Sunan Ibn Majah'],'ci':0,'e':'It is found in Sahih al-Bukhari.'},
{'s':'IRS','y':2017,'q':'The Hadith 'Allah is beautiful and He loves beauty' is from:','o':['Sahih Muslim','Sahih al-Bukhari','Sunan Abu Dawud','Sunan al-Tirmidhi'],'ci':0,'e':'It is in Sahih Muslim.'},
{'s':'IRS','y':2018,'q':'The Hadith 'Do not ask for a position of authority, because if you are given it without asking, you will be helped; if you are given it through asking, you will be left to it' is from:','o':['Sahih al-Bukhari','Sahih Muslim','Sunan Abu Dawud','Sunan al-Tirmidhi'],'ci':0,'e':'It is in Sahih al-Bukhari and Muslim.'},
{'s':'IRS','y':2019,'q':'The Hadith 'Whoever builds a mosque for Allah, Allah will build for him a house in Paradise' is from:','o':['Sahih al-Bukhari','Sahih Muslim','Sunan Abu Dawud','Muwatta Malik'],'ci':0,'e':'It is in Sahih al-Bukhari and Muslim.'},
{'s':'IRS','y':2020,'q':'The Hadith 'The best of people are the most beneficial to people' is a:','o':['Prophetic maxim','Quranic verse','Fiqh ruling','Moral philosophy'],'ci':0,'e':'It is a Prophetic saying.'},
{'s':'IRS','y':2021,'q':'The Hadith 'A person is not a believer who eats his fill while his neighbour is hungry' is from:','o':['Sahih al-Bukhari','Sahih Muslim','Sunan al-Tirmidhi','Sunan Ibn Majah'],'ci':0,'e':'It is in Sahih al-Bukhari.'},
{'s':'IRS','y':2022,'q':'The Hadith 'Modesty is part of faith' is from:','o':['Sahih al-Bukhari','Sahih Muslim','Sunan Abu Dawud','All of these'],'ci':3,'e':'It is reported in multiple collections.'},
{'s':'IRS','y':2023,'q':'The Hadith 'Religion is sincerity (nasihah)' was said in response to a question about:','o':['The meaning of religion','The nature of faith','The Day of Judgment','The law'],'ci':0,'e':'The companion asked about the essence of religion.'},
{'s':'IRS','y':2024,'q':'The Hadith 'Whoever fasts the month of Ramadan and then follows it with six days of Shawwal, it is as if he fasted the whole year' is from:','o':['Sahih Muslim','Sahih al-Bukhari','Sunan Abu Dawud','Sunan Ibn Majah'],'ci':0,'e':'It is in Sahih Muslim.'},
{'s':'IRS','y':2025,'q':'The Hadith 'The first to be judged on the Day of Resurrection is the martyr' warns against:','o':['Showing off and seeking fame in deeds','Fearing death','Loving the world','Disobeying parents'],'ci':0,'e':'The hadith warns that martyrs who fought for fame will be punished.'},
{'s':'IRS','y':2026,'q':'The Hadith 'There should be no harm nor reciprocating harm' is a:','o':['Legal principle (la darar wa la dirar)','Moral teaching','Quranic verse','Fiqh ruling'],'ci':0,'e':'It is a foundational hadith in Islamic jurisprudence.'},
{'s':'IRS','y':2000,'q':'The Hadith 'The ink of the scholar is more sacred than the blood of the martyr' is:','o':['A weak or fabricated hadith','A sahih hadith','A Quranic verse','A saying of the companions'],'ci':0,'e':'This is a well-known but weak/fabricated hadith.'},
{'s':'IRS','y':2001,'q':'The Hadith 'Whoever reads one letter of the Quran, he will have one good deed, and each good deed is multiplied by ten' is from:','o':['Sunan al-Tirmidhi','Sahih al-Bukhari','Sahih Muslim','Sunan Abu Dawud'],'ci':0,'e':'It is recorded by al-Tirmidhi.'},
{'s':'IRS','y':2002,'q':'The Hadith 'The Prophet said: 'The best of you are those who are best to their wives'' is from:','o':['Sahih al-Bukhari','Sahih Muslim','Sunan al-Tirmidhi','Sunan Ibn Majah'],'ci':0,'e':'It is in Sahih al-Bukhari.'},
{'s':'IRS','y':2003,'q':'The Hadith 'The month of Ramadan is a month whose beginning is mercy, middle is forgiveness, and end is freedom from the Fire' is:','o':['A well-known but weak hadith','A sahih hadith','A fabricated hadith','A verse of the Quran'],'ci':0,'e':'This hadith is often quoted but its chain is weak.'},
{'s':'IRS','y':2004,'q':'The Hadith 'Whoever walks to the Friday prayer, Allah will write for him the reward of a year of fasting and prayer for every step' is:','o':['A weak hadith','A sahih hadith','A fabricated hadith','A Quranic verse'],'ci':0,'e':'This is not a sahih hadith.'},
{'s':'IRS','y':2005,'q':'The Hadith 'Three things are from the nature (fitrah): circumcision, clipping the nails, and trimming the moustache' is from:','o':['Sahih al-Bukhari','Sahih Muslim','Sunan Abu Dawud','Sunan Ibn Majah'],'ci':0,'e':'It is in Sahih al-Bukhari and Muslim.'},
{'s':'IRS','y':2006,'q':'The Hadith 'If a Muslim plants a tree and whatever is eaten from it is charity, whatever is stolen from it is charity...' is from:','o':['Sahih Muslim','Sahih al-Bukhari','Sunan Abu Dawud','Sunan al-Tirmidhi'],'ci':0,'e':'It is in Sahih Muslim.'},
{'s':'IRS','y':2007,'q':'The Hadith 'Whoever is not merciful to others, Allah will not be merciful to him' is from:','o':['Sahih al-Bukhari','Sahih Muslim','Sunan al-Tirmidhi','Sunan Abu Dawud'],'ci':0,'e':'It is in Sahih al-Bukhari.'},
{'s':'IRS','y':2008,'q':'The Hadith 'A good word is charity' is from:','o':['Sahih al-Bukhari','Sahih Muslim','Sunan al-Tirmidhi','All of these'],'ci':3,'e':'It is reported in multiple collections.'},
{'s':'IRS','y':2009,'q':'The Hadith 'The strong is not the one who wrestles, but the strong is the one who controls himself at the time of anger' is from:','o':['Sahih al-Bukhari','Sahih Muslim','Sunan Abu Dawud','Sunan al-Tirmidhi'],'ci':0,'e':'It is in Sahih al-Bukhari.'},
{'s':'IRS','y':2010,'q':'The Hadith 'Beware of jealousy, for jealousy consumes good deeds just as fire consumes wood' is from:','o':['Sunan Abu Dawud','Sahih al-Bukhari','Sahih Muslim','Sunan Ibn Majah'],'ci':0,'e':'It is recorded by Abu Dawud.'},
{'s':'IRS','y':2011,'q':'The Hadith 'The best of you are those who are the most beneficial to people' is a:','o':['Prophetic tradition','Quranic verse','Fiqh principle','Saying of Abu Bakr'],'ci':0,'e':'It is a hadith.'},
{'s':'IRS','y':2012,'q':'The Hadith 'Whoever believes in Allah and the Last Day, let him not harm his neighbour' is from:','o':['Sahih al-Bukhari','Sahih Muslim','Sunan al-Tirmidhi','All of these'],'ci':3,'e':'It is in multiple collections.'},
{'s':'IRS','y':2013,'q':'The Hadith 'The believer is not the one who eats his fill while his neighbour is hungry' is from:','o':['Sahih al-Bukhari','Sahih Muslim','Sunan al-Tirmidhi','Sunan Ibn Majah'],'ci':0,'e':'It is in Sahih al-Bukhari.'},
{'s':'IRS','y':2014,'q':'The Hadith 'The best of the Muslims is he from whose tongue and hands the Muslims are safe' is from:','o':['Sahih al-Bukhari','Sahih Muslim','Sunan al-Tirmidhi','Sunan Abu Dawud'],'ci':0,'e':'It is in Sahih al-Bukhari.'},
{'s':'IRS','y':2015,'q':'The Hadith 'The prayer of a person in congregation is multiplied by 27 times more than his prayer alone' is from:','o':['Sahih al-Bukhari','Sahih Muslim','Sunan Abu Dawud','All of these'],'ci':3,'e':'It is reported in multiple collections.'},
{'s':'IRS','y':2016,'q':'The Hadith 'Whoever performs wudu perfectly, his sins will exit from his body until they exit from under his nails' is from:','o':['Sahih Muslim','Sahih al-Bukhari','Sunan Abu Dawud','Sunan al-Tirmidhi'],'ci':0,'e':'It is in Sahih Muslim.'},
{'s':'IRS','y':2017,'q':'The Hadith 'The Prophet (SAW) said: 'The best of days is Friday'' is from:','o':['Sahih Muslim','Sahih al-Bukhari','Sunan Abu Dawud','Sunan al-Tirmidhi'],'ci':0,'e':'It is in Sahih Muslim.'},
{'s':'IRS','y':2018,'q':'The Hadith 'Whoever recites Surah Al-Kahf on Friday, Allah will light for him light between the two Fridays' is from:','o':['Sunan al-Tirmidhi','Sahih al-Bukhari','Sahih Muslim','Sunan Abu Dawud'],'ci':0,'e':'It is recorded by al-Tirmidhi.'},
{'s':'IRS','y':2019,'q':'The Hadith 'The Prophet (SAW) said: 'Seeking knowledge is an obligation upon every Muslim'' is from:','o':['Sunan Ibn Majah','Sahih al-Bukhari','Sahih Muslim','Sunan Abu Dawud'],'ci':0,'e':'It is recorded by Ibn Majah.'},
{'s':'IRS','y':2020,'q':'The Hadith 'Whoever travels a path seeking knowledge, Allah will make easy for him a path to Paradise' is from:','o':['Sahih Muslim','Sahih al-Bukhari','Sunan al-Tirmidhi','Sunan Abu Dawud'],'ci':0,'e':'It is in Sahih Muslim.'},
{'s':'IRS','y':2021,'q':'The Hadith 'The Prophet (SAW) said: 'The best of you is the one who learns the Quran and teaches it'' is from:','o':['Sahih al-Bukhari','Sahih Muslim','Sunan al-Tirmidhi','Sunan Abu Dawud'],'ci':0,'e':'It is in Sahih al-Bukhari.'},
{'s':'IRS','y':2022,'q':'The Hadith 'Whoever does not abandon false speech and acting upon it, Allah has no need of him abandoning his food and drink' is from:','o':['Sahih al-Bukhari','Sahih Muslim','Sunan Abu Dawud','Sunan al-Tirmidhi'],'ci':0,'e':'It is in Sahih al-Bukhari.'},
{'s':'IRS','y':2023,'q':'The Hadith 'The Prophet (SAW) said: 'The worst of people are those who are two-faced'' is from:','o':['Sahih al-Bukhari','Sahih Muslim','Sunan Abu Dawud','Sunan al-Tirmidhi'],'ci':0,'e':'It is in Sahih al-Bukhari.'},
{'s':'IRS','y':2024,'q':'The Hadith 'Whoever believes in Allah and the Last Day, let him say good or remain silent' is from:','o':['Sahih al-Bukhari','Sahih Muslim','Sunan al-Tirmidhi','Sunan Abu Dawud'],'ci':0,'e':'It is in Sahih al-Bukhari.'},
{'s':'IRS','y':2025,'q':'The Hadith 'The Prophet (SAW) said: 'Modesty is part of faith'' is from:','o':['Sahih al-Bukhari','Sahih Muslim','Sunan al-Tirmidhi','All of these'],'ci':3,'e':'It is found in multiple collections.'},
{'s':'IRS','y':2026,'q':'The Hadith 'Whoever believes in Allah and the Last Day, let him honour his guest' is from:','o':['Sahih al-Bukhari','Sahih Muslim','Sunan al-Tirmidhi','Sunan Abu Dawud'],'ci':0,'e':'It is in Sahih al-Bukhari.'},

// ============================================================
// SECTION 3: PILLARS OF ISLAM – IMAN, SALAT, ZAKAT, SAWM, HAJJ (Q281–Q420)
// ============================================================
{'s':'IRS','y':2000,'q':'The five pillars of Islam are:','o':['Shahadah, Salah, Zakat, Sawm, Hajj','Shahadah, Salah, Zakat, Sawm, Jihad','Shahadah, Salah, Zakat, Hajj, Umrah','Shahadah, Salah, Zakat, Sawm, Ihsan'],'ci':0,'e':'These are the five pillars.'},
{'s':'IRS','y':2001,'q':'The testimony of faith (Shahadah) is:','o':[''La ilaha illallah, Muhammadur Rasulullah'',''Allahu Akbar'',''Subhanallah'',''Alhamdulillah''],'ci':0,'e':'The Shahadah is the declaration of faith.'},
{'s':'IRS','y':2002,'q':'The five daily prayers are:','o':['Fajr, Dhuhr, Asr, Maghrib, Isha','Fajr, Dhuhr, Asr, Maghrib, Witr','Fajr, Dhuhr, Asr, Maghrib, Tahajjud','Dhuhr, Asr, Maghrib, Isha, Witr'],'ci':0,'e':'These are the five obligatory daily prayers.'},
{'s':'IRS','y':2003,'q':'The number of rak\'ahs in Fajr prayer is:','o':['2','3','4','1'],'ci':0,'e':'Fajr has 2 rak'ahs sunnah (mu'akkadah) and 2 fard, but the fard is 2.'},
{'s':'IRS','y':2004,'q':'The number of rak\'ahs in Dhuhr prayer is:','o':['4 fard (plus sunnah)','3','2','5'],'ci':0,'e':'Dhuhr has 4 fard rak'ahs.'},
{'s':'IRS','y':2005,'q':'The number of rak\'ahs in Asr prayer is:','o':['4','3','2','1'],'ci':0,'e':'Asr has 4 fard rak'ahs.'},
{'s':'IRS','y':2006,'q':'The number of rak\'ahs in Maghrib prayer is:','o':['3','4','2','5'],'ci':0,'e':'Maghrib has 3 fard rak'ahs.'},
{'s':'IRS','y':2007,'q':'The number of rak\'ahs in Isha prayer is:','o':['4','3','2','5'],'ci':0,'e':'Isha has 4 fard rak'ahs.'},
{'s':'IRS','y':2008,'q':'Zakat is obligatory on:','o':['Wealth exceeding the Nisab (minimum threshold)','All income','Land only','Houses only'],'ci':0,'e':'Zakat is due on wealth above the Nisab.'},
{'s':'IRS','y':2009,'q':'The Nisab (minimum threshold) for gold is:','o':['85 grams','20 grams','50 grams','100 grams'],'ci':0,'e':'85 grams of gold is the Nisab.'},
{'s':'IRS','y':2010,'q':'The Nisab for silver is:','o':['595 grams','200 grams','500 grams','1000 grams'],'ci':0,'e':'595 grams of silver is the Nisab.'},
{'s':'IRS','y':2011,'q':'The rate of Zakat on money and gold is:','o':['2.5% (1/40)','5%','10%','20%'],'ci':0,'e':'Zakat is 2.5% of wealth.'},
{'s':'IRS','y':2012,'q':'Zakat al-Fitr is given before:','o':['Eid al-Fitr prayer','Ramadan','Hajj','Eid al-Adha'],'ci':0,'e':'Zakat al-Fitr is paid before the Eid prayer.'},
{'s':'IRS','y':2013,'q':'The amount of Zakat al-Fitr is:','o':['One sa\' of food','One gold coin','One silver coin','2.5% of wealth'],'ci':0,'e':'It is typically one sa' (approx 2.5-3 kg) of staple food.'},
{'s':'IRS','y':2014,'q':'Fasting (Sawm) in Ramadan is obligatory on:','o':['Every sane, adult Muslim','Children','The sick','The elderly'],'ci':0,'e':'Fasting is obligatory on all sane, adult Muslims who are able.'},
{'s':'IRS','y':2015,'q':'Who is exempted from fasting in Ramadan?','o':['The sick, travelers, menstruating women, and the aged','Only children','Only the sick','Only travelers'],'ci':0,'e':'These groups are exempted and must make up or pay.'},
{'s':'IRS','y':2016,'q':'The month of Ramadan is the month in which:','o':['The Quran was revealed','The Prophet was born','The Hijra began','The Ka'bah was built'],'ci':0,'e':'The Quran was revealed in Ramadan.'},
{'s':'IRS','y':2017,'q':'The Night of Decree (Laylat al-Qadr) is better than:','o':['1000 months','1 year','100 years','10 years'],'ci':0,'e':'Laylat al-Qadr is worth more than 1000 months.'},
{'s':'IRS','y':2018,'q':'Laylat al-Qadr is found in the last:','o':['10 nights of Ramadan','7 nights','5 nights','3 nights'],'ci':0,'e':'It is sought in the last 10 nights.'},
{'s':'IRS','y':2019,'q':'Hajj is obligatory on every Muslim who is:','o':['Physically and financially able','Able to walk','Wealthy only','Healthy only'],'ci':0,'e':'Hajj is required for those with the means and ability.'},
{'s':'IRS','y':2020,'q':'Hajj is performed in the month of:','o':['Dhul-Hijjah','Ramadan','Muharram','Rajab'],'ci':0,'e':'Hajj occurs in the month of Dhul-Hijjah.'},
{'s':'IRS','y':2021,'q':'The most important ritual of Hajj is:','o':['Standing at Arafat','Tawaf','Sa\'i','Stoning the Jamarat'],'ci':0,'e':'Wuquf at Arafat is the central rite.'},
{'s':'IRS','y':2022,'q':'The Hajj is also known as:','o':['The fifth pillar','The fourth pillar','The second pillar','The third pillar'],'ci':0,'e':'Hajj is the fifth pillar of Islam.'},
{'s':'IRS','y':2023,'q':'Umrah is often called the:','o':['Minor pilgrimage','Major pilgrimage','Fifth pillar','Mandatory pilgrimage'],'ci':0,'e':'Umrah is the minor pilgrimage.'},
{'s':'IRS','y':2024,'q':'The Ka\'bah is located in:','o':['Mecca','Medina','Jerusalem','Najd'],'ci':0,'e':'The Ka'bah is in Mecca.'},
{'s':'IRS','y':2025,'q':'The Black Stone (Al-Hajar al-Aswad) is:','o':['Set in the eastern corner of the Ka\'bah','Set in the western corner','Set in the northern corner','Set in the southern corner'],'ci':0,'e':'The Black Stone is in the eastern corner.'},
{'s':'IRS','y':2026,'q':'The three types of Hajj are:','o':['Ifrad, Qiran, Tamattu\'','Ifrad, Qiran, Tawaf','Tamattu, Tawaf, Qiran','Sai, Tawaf, Wuquf'],'ci':0,'e':'These are the three forms of Hajj.'},

// ============================================================
// SECTION 4: Tawhid, Aqidah & Islamic Theology (Q421–Q530)
// ============================================================
{'s':'IRS','y':2000,'q':'The term 'Tawhid' means:','o':['Oneness of God','Prophethood','Judgment Day','Angels'],'ci':0,'e':'Tawhid is the belief in the absolute oneness of Allah.'},
{'s':'IRS','y':2001,'q':'The opposite of Tawhid is:','o':['Shirk (associating partners with Allah)','Kufr','Nifaq','Fisq'],'ci':0,'e':'Shirk is the gravest sin in Islam.'},
{'s':'IRS','y':2002,'q':'The concept of 'Tawhid al-Rububiyyah' refers to:','o':['Belief that Allah is the sole Creator and Sustainer','Belief in the oneness of worship','Belief in Allah\'s names and attributes','Belief in the Prophets'],'ci':0,'e':'Rububiyyah is lordship – Allah as the sole Creator and Sustainer.'},
{'s':'IRS','y':2003,'q':'The concept of 'Tawhid al-Uluhiyyah' refers to:','o':['Belief that Allah alone is worthy of worship','Belief in Allah\'s lordship','Belief in Allah\'s names and attributes','Belief in the Prophets'],'ci':0,'e':'Uluhiyyah is the oneness of worship.'},
{'s':'IRS','y':2004,'q':'The concept of 'Tawhid al-Asma wa al-Sifat' refers to:','o':['Belief in Allah\'s names and attributes as revealed','Belief in Allah\'s lordship','Belief in Allah\'s worship','Belief in the Prophets'],'ci':0,'e':'This is the third category of Tawhid.'},
{'s':'IRS','y':2005,'q':'The name 'Al-Quddus' means:','o':['The Most Holy','The Most Merciful','The All-Knowing','The All-Powerful'],'ci':0,'e':'Al-Quddus is the Most Holy.'},
{'s':'IRS','y':2006,'q':'The name 'Al-Ahad' means:','o':['The One','The Absolute','The Eternal','The Unique'],'ci':0,'e':'Al-Ahad means the One.'},
{'s':'IRS','y':2007,'q':'The name 'Al-Samad' means:','o':['The Eternal, Self-Sufficient','The All-Hearing','The All-Seeing','The Most Great'],'ci':0,'e':'Al-Samad is the Eternal and Self-Sufficient.'},
{'s':'IRS','y':2008,'q':'The angels are created from:','o':['Light','Fire','Clay','Water'],'ci':0,'e':'Angels are created from light (nur).'},
{'s':'IRS','y':2009,'q':'Jinn are created from:','o':['Smokeless fire','Clay','Water','Light'],'ci':0,'e':'Jinn are created from smokeless fire.'},
{'s':'IRS','y':2010,'q':'The first creature created by Allah was:','o':['The Pen (Al-Qalam)','The Throne','Angels','Adam'],'ci':0,'e':'The Pen was the first creation.'},
{'s':'IRS','y':2011,'q':'The Day of Judgment is known in Arabic as:','o':['Yawm al-Qiyamah','Yawm al-Jum\'ah','Yawm al-Arafah','Yawm al-Nahr'],'ci':0,'e':'Yawm al-Qiyamah is the Day of Resurrection.'},
{'s':'IRS','y':2012,'q':'The signs of the Day of Judgment include:','o':['The appearance of Dajjal, Ya\'juj and Ma\'juj, the Beast','The sun rising from the West','The smoke','All of these'],'ci':3,'e':'All are major signs.'},
{'s':'IRS','y':2013,'q':'The Angel of Death is:','o':['Malak al-Mawt (Azrael)','Jibreel','Mika\'il','Israfil'],'ci':0,'e':'Azrael is the Angel of Death.'},
{'s':'IRS','y':2014,'q':'The Angel who is responsible for revelation is:','o':['Jibreel (Gabriel)','Mika\'il (Michael)','Israfil','Malak al-Mawt'],'ci':0,'e':'Jibreel brought the revelation.'},
{'s':'IRS','y':2015,'q':'The Angel responsible for blowing the Trumpet is:','o':['Israfil','Jibreel','Mika\'il','Ridwan'],'ci':0,'e':'Israfil will blow the Trumpet.'},
{'s':'IRS','y':2016,'q':'The Angel responsible for rain and sustenance is:','o':['Mika\'il','Jibreel','Israfil','Malak al-Mawt'],'ci':0,'e':'Mika'il is responsible for provisions.'},
{'s':'IRS','y':2017,'q':'The concept of 'Qadar' in Islam means:','o':['Divine predestination and decree','Free will','Human choice','Fate only'],'ci':0,'e':'Qadar is Allah's complete knowledge and decree.'},
{'s':'IRS','y':2018,'q':'Belief in Qadar is one of the pillars of:','o':['Iman (faith)','Islam','Ihsan','Tawhid'],'ci':0,'e':'It is the sixth pillar of iman.'},
{'s':'IRS','y':2019,'q':'The six pillars of Iman are:','o':['Belief in Allah, angels, books, messengers, the Last Day, and divine decree','Belief in Allah, angels, books, messengers, jihad, and divine decree','Belief in Allah, angels, books, prophets, imams, and divine decree','Belief in Allah, angels, books, prophets, the Last Day, and paradise'],'ci':0,'e':'These are the six articles of faith.'},
{'s':'IRS','y':2020,'q':'The Four Rightly Guided Caliphs are:','o':['Abu Bakr, Umar, Uthman, Ali','Abu Bakr, Umar, Uthman, Mu\'awiyah','Abu Bakr, Umar, Uthman, Abu Ubaidah','Abu Bakr, Umar, Uthman, Talha'],'ci':0,'e':'These are the Rashidun Caliphs.'},
{'s':'IRS','y':2021,'q':'The first caliph after the Prophet was:','o':['Abu Bakr as-Siddiq','Umar ibn al-Khattab','Uthman ibn Affan','Ali ibn Abi Talib'],'ci':0,'e':'Abu Bakr was elected as the first caliph.'},
{'s':'IRS','y':2022,'q':'The second caliph was:','o':['Umar ibn al-Khattab','Abu Bakr','Uthman','Ali'],'ci':0,'e':'Umar succeeded Abu Bakr.'},
{'s':'IRS','y':2023,'q':'The third caliph was:','o':['Uthman ibn Affan','Umar','Ali','Abu Bakr'],'ci':0,'e':'Uthman was the third caliph.'},
{'s':'IRS','y':2024,'q':'The fourth caliph was:','o':['Ali ibn Abi Talib','Uthman','Umar','Abu Bakr'],'ci':0,'e':'Ali was the fourth caliph.'},
{'s':'IRS','y':2025,'q':'The caliph known as 'Al-Faruq' (the distinguisher between truth and falsehood) is:','o':['Umar ibn al-Khattab','Abu Bakr','Uthman','Ali'],'ci':0,'e':'Umar was given this title.'},
{'s':'IRS','y':2026,'q':'The caliph who compiled the Quran into one Mushaf was:','o':['Abu Bakr','Umar','Uthman','Ali'],'ci':0,'e':'Abu Bakr ordered the compilation.'},

// ============================================================
// SECTION 5: PROPHETS & MESSENGERS (Q531–Q620)
// ============================================================
{'s':'IRS','y':2000,'q':'The first prophet was:','o':['Adam','Idris','Nuh','Ibrahim'],'ci':0,'e':'Adam was the first prophet.'},
{'s':'IRS','y':2001,'q':'The last prophet is:','o':['Muhammad (SAW)','Isa (AS)','Musa (AS)','Ibrahim (AS)'],'ci':0,'e':'Muhammad is the Seal of the Prophets.'},
{'s':'IRS','y':2002,'q':'The prophet who built the Ka\'bah with his son Ismail was:','o':['Ibrahim','Ishaq','Ya\'qub','Nuh'],'ci':0,'e':'Ibrahim and Ismail rebuilt the Ka'bah.'},
{'s':'IRS','y':2003,'q':'The prophet known as the 'Friend of Allah' (Khalilullah) is:','o':['Ibrahim','Musa','Isa','Muhammad'],'ci':0,'e':'Ibrahim is called Khalilullah.'},
{'s':'IRS','y':2004,'q':'The prophet who spoke to Allah directly is:','o':['Musa (Moses)','Isa (Jesus)','Ibrahim','Muhammad'],'ci':0,'e':'Musa was kalimullah (one who spoke to Allah).'},
{'s':'IRS','y':2005,'q':'The prophet who was born miraculously without a father is:','o':['Isa (Jesus)','Adam','Yahya','Idris'],'ci':0,'e':'Isa (AS) was born without a father.'},
{'s':'IRS','y':2006,'q':'The prophet who was given the Zabur (Psalms) is:','o':['Dawud (David)','Musa (Moses)','Isa (Jesus)','Sulayman (Solomon)'],'ci':0,'e':'Dawud received the Zabur.'},
{'s':'IRS','y':2007,'q':'The prophet who was given the Tawrat (Torah) is:','o':['Musa (Moses)','Isa (Jesus)','Dawud (David)','Muhammad'],'ci':0,'e':'Musa received the Tawrat.'},
{'s':'IRS','y':2008,'q':'The prophet who was given the Injil (Gospel) is:','o':['Isa (Jesus)','Musa','Dawud','Ibrahim'],'ci':0,'e':'Isa received the Injil.'},
{'s':'IRS','y':2009,'q':'The prophet who was given the Quran is:','o':['Muhammad (SAW)','Musa','Isa','Dawud'],'ci':0,'e':'Muhammad received the Quran.'},
{'s':'IRS','y':2010,'q':'The prophet who is known for his wisdom and ruling over the jinn is:','o':['Sulayman (Solomon)','Dawud (David)','Musa','Isa'],'ci':0,'e':'Sulayman had authority over the jinn.'},
{'s':'IRS','y':2011,'q':'The prophet who is known for his patience in severe illness is:','o':['Ayyub (Job)','Yunus (Jonah)','Yusuf (Joseph)','Ibrahim'],'ci':0,'e':'Ayyub is the model of patience.'},
{'s':'IRS','y':2012,'q':'The prophet who was swallowed by a whale is:','o':['Yunus (Jonah)','Musa','Yusuf','Ibrahim'],'ci':0,'e':'Yunus was swallowed by the whale.'},
{'s':'IRS','y':2013,'q':'The prophet who interpreted dreams and was sold into slavery is:','o':['Yusuf (Joseph)','Ya\'qub (Jacob)','Ibrahim','Ishaq'],'ci':0,'e':'Yusuf was the dream interpreter.'},
{'s':'IRS','y':2014,'q':'The prophet who led the Israelites out of Egypt is:','o':['Musa (Moses)','Yusuf','Ibrahim','Harun'],'ci':0,'e':'Musa led the Exodus.'},
{'s':'IRS','y':2015,'q':'The prophet who was the father of prophets and built the Ka\'bah is:','o':['Ibrahim','Nuh','Adam','Musa'],'ci':0,'e':'Ibrahim is the father of many prophets.'},
{'s':'IRS','y':2016,'q':'The prophet who was sent to the people of 'Aad is:','o':['Hud','Salih','Nuh','Shu\'ayb'],'ci':0,'e':'Hud was sent to 'Aad.'},
{'s':'IRS','y':2017,'q':'The prophet who was sent to the people of Thamud is:','o':['Salih','Hud','Nuh','Shu\'ayb'],'ci':0,'e':'Salih was sent to Thamud.'},
{'s':'IRS','y':2018,'q':'The prophet who was sent to the people of Madyan is:','o':['Shu\'ayb','Hud','Salih','Nuh'],'ci':0,'e':'Shu'ayb was sent to Madyan.'},
{'s':'IRS','y':2019,'q':'The prophet who was sent to the people of Lut (Lot) is:','o':['Lut','Ibrahim','Musa','Yunus'],'ci':0,'e':'Lut was sent to the people of Sodom.'},
{'s':'IRS','y':2020,'q':'The number of prophets mentioned by name in the Quran is:','o':['25','15','30','20'],'ci':0,'e':'The Quran mentions 25 prophets by name.'},
{'s':'IRS','y':2021,'q':'The number of messengers mentioned in the Quran is:','o':['25','15','30','20'],'ci':0,'e':'All prophets are messengers, but some are specifically named.'},
{'s':'IRS','y':2022,'q':'The term 'Nabi' in Arabic means:','o':['Prophet','Messenger','King','Scholar'],'ci':0,'e':'Nabi is a prophet who receives revelation.'},
{'s':'IRS','y':2023,'q':'The term 'Rasul' in Arabic means:','o':['Messenger (who is sent with a new scripture)','Prophet','King','Scholar'],'ci':0,'e':'Rasul is a messenger with a new book.'},
{'s':'IRS','y':2024,'q':'All messengers are prophets, but not all prophets are messengers.','o':['True','False','Sometimes','Never'],'ci':0,'e':'This is a correct theological distinction.'},
{'s':'IRS','y':2025,'q':'The prophet who was raised to heaven alive is:','o':['Idris (Enoch)','Isa (Jesus)','Ilyas (Elijah)','All of these'],'ci':3,'e':'Idris, Isa, and Ilyas are mentioned as being raised.'},
{'s':'IRS','y':2026,'q':'The prophet who was taken alive to heaven and will return is:','o':['Isa (Jesus)','Idris','Ilyas','Muhammad'],'ci':0,'e':'Isa will return before the Day of Judgment.'},

// ============================================================
// SECTION 6: FIQH (ISLAMIC JURISPRUDENCE) – Q621–Q700
// ============================================================
{'s':'IRS','y':2000,'q':'Fiqh means:','o':['Islamic jurisprudence','Islamic theology','Islamic history','Islamic philosophy'],'ci':0,'e':'Fiqh is the understanding of Islamic law.'},
{'s':'IRS','y':2001,'q':'The four major schools of Fiqh are:','o':['Hanafi, Maliki, Shafi\'i, Hanbali','Hanafi, Maliki, Shafi\'i, Ja\'fari','Hanafi, Hanbali, Maliki, Zahiri','Shafi\'i, Maliki, Hanafi, Zaydi'],'ci':0,'e':'These are the four Sunni madhabs.'},
{'s':'IRS','y':2002,'q':'The founder of the Hanafi school is:','o':['Abu Hanifah','Malik ibn Anas','Al-Shafi\'i','Ahmad ibn Hanbal'],'ci':0,'e':'Abu Hanifah founded the Hanafi school.'},
{'s':'IRS','y':2003,'q':'The founder of the Maliki school is:','o':['Malik ibn Anas','Abu Hanifah','Al-Shafi\'i','Ahmad ibn Hanbal'],'ci':0,'e':'Malik ibn Anas founded the Maliki school.'},
{'s':'IRS','y':2004,'q':'The founder of the Shafi\'i school is:','o':['Al-Shafi\'i','Abu Hanifah','Malik','Ahmad ibn Hanbal'],'ci':0,'e':'Al-Shafi\'i is the founder.'},
{'s':'IRS','y':2005,'q':'The founder of the Hanbali school is:','o':['Ahmad ibn Hanbal','Abu Hanifah','Malik','Al-Shafi\'i'],'ci':0,'e':'Ahmad ibn Hanbal founded the Hanbali school.'},
{'s':'IRS','y':2006,'q':'The primary source of Islamic law (Shariah) is:','o':['The Quran','Hadith','Ijma (consensus)','Qiyas (analogy)'],'ci':0,'e':'The Quran is the first source.'},
{'s':'IRS','y':2007,'q':'The second source of Islamic law is:','o':['Sunnah/Hadith','Ijma','Qiyas','Ijtihad'],'ci':0,'e':'The Sunnah is the second source.'},
{'s':'IRS','y':2008,'q':'The third source of Islamic law is:','o':['Ijma (consensus)','Qiyas (analogy)','Ijtihad','Istihsan'],'ci':0,'e':'Ijma is the third source.'},
{'s':'IRS','y':2009,'q':'The fourth source of Islamic law is:','o':['Qiyas (analogy)','Ijma','Istihsan','Urf'],'ci':0,'e':'Qiyas is the fourth source.'},
{'s':'IRS','y':2010,'q':'Ijtihad is:','o':['Independent legal reasoning to derive rulings','Consensus','Analogy','Tradition'],'ci':0,'e':'Ijtihad is the effort of qualified jurists.'},
{'s':'IRS','y':2011,'q':'The concept of 'Halal' in Islamic law means:','o':['Permissible','Forbidden','Obligatory','Recommended'],'ci':0,'e':'Halal is lawful and permissible.'},
{'s':'IRS','y':2012,'q':'The concept of 'Haram' means:','o':['Forbidden','Permissible','Obligatory','Recommended'],'ci':0,'e':'Haram is prohibited.'},
{'s':'IRS','y':2013,'q':'The concept of 'Wajib' means:','o':['Obligatory','Forbidden','Recommended','Permissible'],'ci':0,'e':'Wajib is compulsory.'},
{'s':'IRS','y':2014,'q':'The concept of 'Makruh' means:','o':['Disliked or discouraged','Forbidden','Obligatory','Permissible'],'ci':0,'e':'Makruh is reprehensible but not sinful.'},
{'s':'IRS','y':2015,'q':'The concept of 'Mustahabb' means:','o':['Recommended (rewardable but not obligatory)','Obligatory','Forbidden','Permissible'],'ci':0,'e':'Mustahabb is supererogatory.'},
{'s':'IRS','y':2016,'q':'The concept of 'Mubah' means:','o':['Permissible','Obligatory','Forbidden','Recommended'],'ci':0,'e':'Mubah is neutral.'},
{'s':'IRS','y':2017,'q':'Riba (usury/interest) is:','o':['Haram (forbidden)','Halal (permissible)','Makruh (disliked)','Wajib (obligatory)'],'ci':0,'e':'Riba is strictly forbidden.'},
{'s':'IRS','y':2018,'q':'Gambling (Maysir) is:','o':['Haram','Halal','Makruh','Mustahabb'],'ci':0,'e':'Gambling is explicitly forbidden.'},
{'s':'IRS','y':2019,'q':'Consumption of pork is:','o':['Haram','Halal','Makruh','Mustahabb'],'ci':0,'e':'Pork is forbidden.'},
{'s':'IRS','y':2020,'q':'Consumption of alcohol (khamr) is:','o':['Haram','Halal','Makruh','Mustahabb'],'ci':0,'e':'Alcohol is strictly forbidden.'},
{'s':'IRS','y':2021,'q':'The punishment for theft in Islamic law (hadd) is:','o':['Amputation of the hand','Flogging','Imprisonment','Fines'],'ci':0,'e':'The hadd for theft is hand amputation.'},
{'s':'IRS','y':2022,'q':'The punishment for adultery (zina) for unmarried persons is:','o':['100 lashes','Stoning to death','Imprisonment','Fines'],'ci':0,'e':'For unmarried, 100 lashes; for married, stoning.'},
{'s':'IRS','y':2023,'q':'The punishment for false accusation of adultery (qadhf) is:','o':['80 lashes','100 lashes','Stoning','Imprisonment'],'ci':0,'e':'Qadhf carries 80 lashes.'},
{'s':'IRS','y':2024,'q':'Islamic inheritance (fara\'id) is based on fixed shares assigned in:','o':['Surah An-Nisa','Surah Al-Baqarah','Surah Al-Ma\'idah','Surah Al-Anfal'],'ci':0,'e':'Surah An-Nisa contains the inheritance verses.'},
{'s':'IRS','y':2025,'q':'The male heir gets twice the share of a female in many cases due to:','o':['The economic responsibility of men','Superiority','Injustice','Tradition'],'ci':0,'e':'Men are financially responsible for women.'},
{'s':'IRS','y':2026,'q':'A will (wasiyyah) in Islam is limited to:','o':['One third of the estate','Half of the estate','All of the estate','A fixed amount'],'ci':0,'e':'A will cannot exceed one-third after debts and funeral expenses.'},
{'s':'IRS','y':2000,'q':'Marriage (nikah) in Islam is:','o':['A contract','A sacrament','A social arrangement','A political alliance'],'ci':0,'e':'Marriage is a solemn contract.'},
{'s':'IRS','y':2001,'q':'The minimum dowry (mahr) required for marriage is:','o':['Anything of value agreed upon','A specific amount of gold','A specific amount of silver','Ten dinars'],'ci':0,'e':'Mahr can be any agreed sum.'},
{'s':'IRS','y':2002,'q':'The maximum number of wives in Islam is:','o':['4','2','3','5'],'ci':0,'e':'Polygyny is limited to four.'},
{'s':'IRS','y':2003,'q':'The condition for polygyny is:','o':['Justice among wives','Wealth','Children','Permission of the first wife'],'ci':0,'e':'Justice is mandatory.'},
{'s':'IRS','y':2004,'q':'Divorce (talaq) in Islam is:','o':['Permissible but most disliked among halal things','Encouraged','Obligatory','Forbidden'],'ci':0,'e':'Talaq is permissible but hated by Allah.'},
{'s':'IRS','y':2005,'q':'The 'iddah (waiting period) for a divorced woman is:','o':['Three menstrual cycles','One month','Three months','One year'],'ci':0,'e':'Iddah is three cycles or three months if no menstruation.'},
{'s':'IRS','y':2006,'q':'The iddah for a widow is:','o':['Four months and ten days','Three months','One year','Two years'],'ci':0,'e':'Iddah for widow is 4 months and 10 days.'},
{'s':'IRS','y':2007,'q':'The Islamic contract of sale requires:','o':['Offer and acceptance (Ijab and Qabul)','Written document','Witnesses','Registration'],'ci':0,'e':'Ijab and Qabul are essential.'},
{'s':'IRS','y':2008,'q':'The prohibition of Riba applies to:','o':['Usury in loans and certain sales','Only loans','Only sales','All financial transactions'],'ci':0,'e':'Riba is forbidden in both loans and sales.'},
{'s':'IRS','y':2009,'q':'Islamic banking operates on the principle of:','o':['Profit and loss sharing (PLS) and interest-free transactions','Interest-based lending','Usury','Speculation'],'ci':0,'e':'Islamic banking avoids Riba.'},
{'s':'IRS','y':2010,'q':'Mudarabah is a form of:','o':['Partnership where one provides capital and the other expertise','Loan','Sale','Rent'],'ci':0,'e':'Mudarabah is a trust financing contract.'},
{'s':'IRS','y':2011,'q':'Musharakah is a:','o':['Joint partnership where all parties contribute capital','Loan','Sale','Rent'],'ci':0,'e':'Musharakah is a partnership.'},
{'s':'IRS','y':2012,'q':'Ijarah is a:','o':['Leasing contract','Sale contract','Partnership','Loan'],'ci':0,'e':'Ijarah is leasing.'},
{'s':'IRS','y':2013,'q':'Salam is a:','o':['Forward sale contract for commodities','Spot sale','Lease','Partnership'],'ci':0,'e':'Salam is a futures contract.'},
{'s':'IRS','y':2014,'q':'Istisna is a:','o':['Manufacturing contract','Lease','Sale','Partnership'],'ci':0,'e':'Istisna is a contract to manufacture.'},
{'s':'IRS','y':2015,'q':'Zakat is one of the:','o':['Pillars of Islam','Pillars of Iman','Branches of Iman','Categories of worship'],'ci':0,'e':'Zakat is a pillar of Islam.'},
{'s':'IRS','y':2016,'q':'The recipients of Zakat are mentioned in:','o':['Surah At-Tawbah 9:60','Surah Al-Baqarah','Surah Al-Isra','Surah An-Nisa'],'ci':0,'e':'The eight categories are in Surah At-Tawbah.'},
{'s':'IRS','y':2017,'q':'The eight categories of Zakat recipients are:','o':['The poor, needy, zakat collectors, those whose hearts are to be reconciled, captives, debtors, for the cause of Allah, and the wayfarer','Only the poor','Only the needy','Only the poor and needy'],'ci':0,'e':'These are the eight categories.'},
{'s':'IRS','y':2018,'q':'Sadaqah is:','o':['Voluntary charity','Obligatory charity','Zakat','Waqf'],'ci':0,'e':'Sadaqah is voluntary charity.'},
{'s':'IRS','y':2019,'q':'Waqf is:','o':['An endowment (charitable trust)','A loan','A sale','A gift'],'ci':0,'e':'Waqf is a perpetual charity.'},
{'s':'IRS','y':2020,'q':'The first mosque built by the Prophet (SAW) in Madinah was:','o':['Masjid Quba','Masjid Nabawi','Masjid al-Haram','Masjid al-Aqsa'],'ci':0,'e':'Masjid Quba was the first mosque built.'},
{'s':'IRS','y':2021,'q':'The Prophet (SAW) migrated from Mecca to Madinah in the year:','o':['622 CE','610 CE','632 CE','614 CE'],'ci':0,'e':'The Hijra occurred in 622 CE.'},
{'s':'IRS','y':2022,'q':'The Hijri calendar is based on:','o':['Lunar cycles','Solar cycles','The migration of the Prophet','The death of the Prophet'],'ci':0,'e':'The Islamic calendar is lunar.'},
{'s':'IRS','y':2023,'q':'The first month of the Hijri calendar is:','o':['Muharram','Ramadan','Dhul-Hijjah','Safar'],'ci':0,'e':'Muharram is the first month.'},
{'s':'IRS','y':2024,'q':'The Battle of Badr took place in the year:','o':['2 AH','1 AH','3 AH','4 AH'],'ci':0,'e':'Badr was in 2 AH.'},
{'s':'IRS','y':2025,'q':'The Battle of Uhud took place in:','o':['3 AH','2 AH','4 AH','5 AH'],'ci':0,'e':'Uhud was in 3 AH.'},
{'s':'IRS','y':2026,'q':'The Conquest of Mecca (Fath al-Makkah) took place in:','o':['8 AH','7 AH','9 AH','10 AH'],'ci':0,'e':'The conquest was in 8 AH.'},
];
