// lib/questions_irs.dart
//
// Islamic Religious Studies (IRS) question bank — 100 questions.
// Topics: Quranic Studies, Five Pillars, Islamic History, Fiqh, Aqeedah,
// Prophets, Ethics, Family, Worship, General Knowledge.
// Year cycle: 2000–2026. Explanations in English.

final List<Map<String, dynamic>> irsQuestions = [
  // ---- Quranic Studies ----
  {'subject': 'IRS', 'year': 2000, 'question': 'How many chapters (surahs) are there in the Quran?', 'options': ['99', '114', '150', '120'], 'correctIndex': 1, 'explanation': 'The Quran has 114 surahs (chapters).'},
  {'subject': 'IRS', 'year': 2001, 'question': 'How many verses (ayahs) are in the Quran approximately?', 'options': ['2000', '4000', '6000', '8000'], 'correctIndex': 2, 'explanation': 'The Quran contains approximately 6,236 verses.'},
  {'subject': 'IRS', 'year': 2002, 'question': 'Which surah is the longest in the Quran?', 'options': ['Surah Al-Baqarah', 'Surah Al-Imran', 'Surah An-Nisa', 'Surah Al-Maaidah'], 'correctIndex': 0, 'explanation': 'Surah Al-Baqarah (The Cow) is the longest surah with 286 verses.'},
  {'subject': 'IRS', 'year': 2003, 'question': 'Which surah is the shortest in the Quran?', 'options': ['Surah Al-Kawthar', 'Surah Al-Ikhlas', 'Surah Al-Asr', 'Surah Al-Fil'], 'correctIndex': 0, 'explanation': 'Surah Al-Kawthar is the shortest with only 3 verses.'},
  {'subject': 'IRS', 'year': 2004, 'question': 'What is the first surah of the Quran?', 'options': ['Surah Al-Asr', 'Surah Al-Fatiha', 'Surah Al-Baqarah', 'Surah Yunus'], 'correctIndex': 1, 'explanation': 'Surah Al-Fatiha (The Opening) is the first surah of the Quran.'},
  {'subject': 'IRS', 'year': 2005, 'question': 'What is the last surah of the Quran?', 'options': ['Surah An-Nas', 'Surah Al-Ikhlas', 'Surah Al-Kawthar', 'Surah Al-Masad'], 'correctIndex': 0, 'explanation': 'Surah An-Nas (Mankind) is the last surah of the Quran.'},
  {'subject': 'IRS', 'year': 2006, 'question': 'What is the significance of Juz in the Quran?', 'options': ['A chapter', 'A verse', 'One of 30 equal parts', 'A section of a surah'], 'correctIndex': 2, 'explanation': 'Juz refers to one of the 30 equal parts of the Quran for reading.'},
  {'subject': 'IRS', 'year': 2007, 'question': 'Which city was the Quran mostly revealed in?', 'options': ['Madinah', 'Makkah', 'Medina', 'Taif'], 'correctIndex': 1, 'explanation': 'Most of the Quran was revealed in Makkah during the first period of revelation.'},
  {'subject': 'IRS', 'year': 2008, 'question': "What does 'Makki' refer to in Quranic studies?", 'options': ['Verses revealed in Madinah', 'Verses revealed in Makkah', 'Verses about trade', 'Verses about war'], 'correctIndex': 1, 'explanation': 'Makki refers to chapters revealed in Makkah before the Hijrah.'},
  {'subject': 'IRS', 'year': 2009, 'question': "What does 'Madani' refer to in Quranic studies?", 'options': ['Verses revealed in Makkah', 'Verses revealed in Madinah', 'Verses about prayer', 'Verses about charity'], 'correctIndex': 1, 'explanation': 'Madani refers to chapters revealed in Madinah after the Hijrah.'},

  // ---- Five Pillars of Islam ----
  {'subject': 'IRS', 'year': 2010, 'question': 'How many daily prayers are required in Islam?', 'options': ['3', '4', '5', '6'], 'correctIndex': 2, 'explanation': 'Muslims are required to perform 5 daily prayers (Salat).'},
  {'subject': 'IRS', 'year': 2011, 'question': 'What is the Islamic month of fasting called?', 'options': ['Muharram', 'Ramadan', 'Shawwal', 'Hajj'], 'correctIndex': 1, 'explanation': 'Ramadan is the month of fasting in the Islamic calendar.'},
  {'subject': 'IRS', 'year': 2012, 'question': 'What is the minimum amount of charity (Zakat) in Islamic law?', 'options': ['1%', '2%', '2.5%', '5%'], 'correctIndex': 2, 'explanation': 'Zakat is 2.5% of saved wealth given to the poor and needy.'},
  {'subject': 'IRS', 'year': 2013, 'question': 'At what age is the Hajj (pilgrimage) obligatory for Muslims?', 'options': ['18 years', '25 years', 'Anytime after puberty', 'After retirement'], 'correctIndex': 2, 'explanation': 'Hajj is obligatory for all Muslims who are physically and financially able.'},
  {'subject': 'IRS', 'year': 2014, 'question': 'What is the Islamic declaration of faith called?', 'options': ['Salat', 'Shahada', 'Zakat', 'Hajj'], 'correctIndex': 1, 'explanation': "The Shahada is the declaration: 'There is no god but Allah, and Muhammad is His messenger.'"},
  {'subject': 'IRS', 'year': 2015, 'question': 'Which pillar of Islam emphasizes belief in Allah and His oneness?', 'options': ['Salat', 'Zakat', 'Shahada', 'Hajj'], 'correctIndex': 2, 'explanation': "The Shahada is the foundation, declaring belief in Allah's oneness and Muhammad as His messenger."},
  {'subject': 'IRS', 'year': 2016, 'question': 'When is the Hajj performed during the Islamic calendar?', 'options': ['During Ramadan', 'During Muharram', 'During the month of Dhul-Hijjah', 'During Safar'], 'correctIndex': 2, 'explanation': 'The Hajj is performed in the month of Dhul-Hijjah, the 12th month.'},
  {'subject': 'IRS', 'year': 2017, 'question': 'What is the night of power (Laylat al-Qadr)?', 'options': ['The night of Hajj', 'The first night of Ramadan', 'The night when the Quran began revelation', 'The night of Eid'], 'correctIndex': 2, 'explanation': 'Laylat al-Qadr is the night when the Quran was first revealed to Prophet Muhammad.'},
  {'subject': 'IRS', 'year': 2018, 'question': 'What is Eid al-Fitr?', 'options': ['Celebration of Hajj', 'Celebration ending Ramadan', 'Celebration of Islamic New Year', 'Celebration of Mecca'], 'correctIndex': 1, 'explanation': 'Eid al-Fitr is the festival marking the end of Ramadan (the month of fasting).'},
  {'subject': 'IRS', 'year': 2019, 'question': 'What is Eid al-Adha?', 'options': ['Ending of Ramadan', "Celebration of Abraham's sacrifice", 'Islamic New Year', "Celebration of Prophet's birthday"], 'correctIndex': 1, 'explanation': "Eid al-Adha commemorates Prophet Ibrahim's willingness to sacrifice his son."},

  // ---- Islamic History ----
  {'subject': 'IRS', 'year': 2020, 'question': 'What is the Hijrah?', 'options': ['Pilgrimage to Mecca', 'Migration of Prophet Muhammad', 'Night journey', 'Battle'], 'correctIndex': 1, 'explanation': 'The Hijrah is the migration of Prophet Muhammad from Makkah to Madinah in 622 CE.'},
  {'subject': 'IRS', 'year': 2021, 'question': 'In what year did Prophet Muhammad start his prophethood?', 'options': ['570 CE', '610 CE', '630 CE', '650 CE'], 'correctIndex': 1, 'explanation': 'Prophet Muhammad received his first revelation at age 40 in 610 CE.'},
  {'subject': 'IRS', 'year': 2022, 'question': 'How many years did Prophet Muhammad live?', 'options': ['50 years', '60 years', '63 years', '70 years'], 'correctIndex': 2, 'explanation': 'Prophet Muhammad lived for 63 years (570-632 CE).'},
  {'subject': 'IRS', 'year': 2023, 'question': 'Who was the first Muslim?', 'options': ['Khadijah', 'Ali ibn Abi Talib', 'Abu Bakr', 'Prophet Muhammad'], 'correctIndex': 0, 'explanation': "Khadijah, the Prophet's wife, was the first to believe in Islam."},
  {'subject': 'IRS', 'year': 2024, 'question': 'Who was the first Caliph (leader) after Prophet Muhammad?', 'options': ['Umar ibn Al-Khattab', 'Ali ibn Abi Talib', 'Abu Bakr', 'Uthman ibn Affan'], 'correctIndex': 2, 'explanation': 'Abu Bakr As-Siddiq was the first Caliph of Islam.'},
  {'subject': 'IRS', 'year': 2025, 'question': 'What was the first battle in Islam?', 'options': ['Battle of Uhud', 'Battle of Badr', 'Battle of Khandaq', 'Battle of Khaybar'], 'correctIndex': 1, 'explanation': 'The Battle of Badr (624 CE) was the first battle in Islam.'},
  {'subject': 'IRS', 'year': 2026, 'question': 'How many wives did Prophet Muhammad have?', 'options': ['4', '6', '9', '11'], 'correctIndex': 3, 'explanation': 'Prophet Muhammad had 11 wives in total throughout his life.'},

  // ---- Islamic Law (Fiqh) ----
  {'subject': 'IRS', 'year': 2000, 'question': 'What is Halal?', 'options': ['Forbidden', 'Lawful in Islamic law', 'Neutral', 'Doubtful'], 'correctIndex': 1, 'explanation': 'Halal means permissible or lawful according to Islamic law.'},
  {'subject': 'IRS', 'year': 2001, 'question': 'What is Haram?', 'options': ['Lawful', 'Forbidden in Islamic law', 'Neutral', 'Recommended'], 'correctIndex': 1, 'explanation': 'Haram means forbidden or prohibited in Islamic law.'},
  {'subject': 'IRS', 'year': 2002, 'question': 'What is Istidlal in Islamic jurisprudence?', 'options': ['Following consensus', 'Using analogical reasoning', 'Personal opinion', 'Following tradition'], 'correctIndex': 1, 'explanation': 'Istidlal (Qiyas) is reasoning by analogy to derive Islamic rulings.'},
  {'subject': 'IRS', 'year': 2003, 'question': 'What is Ijma in Islamic jurisprudence?', 'options': ['Personal reasoning', 'Consensus of scholars', 'Following the Quran', 'Following Hadith'], 'correctIndex': 1, 'explanation': 'Ijma is the consensus of Muslim scholars on a religious matter.'},
  {'subject': 'IRS', 'year': 2004, 'question': 'What are the main sources of Islamic law?', 'options': ['Only the Quran', 'Quran and Hadith', 'Quran, Hadith, Ijma, and Qiyas', 'Only the Sunnah'], 'correctIndex': 2, 'explanation': 'The four primary sources are: Quran, Sunnah (Hadith), Ijma, and Qiyas.'},
  {'subject': 'IRS', 'year': 2005, 'question': 'What is Hudud in Islamic law?', 'options': ['Permitted actions', 'Forbidden boundaries', 'Fixed punishments for grave sins', 'Recommended deeds'], 'correctIndex': 2, 'explanation': 'Hudud refers to fixed punishments prescribed by Islamic law for specific crimes.'},
  {'subject': 'IRS', 'year': 2006, 'question': 'What is Wudu (ablution) in Islam?', 'options': ['Ritual bathing', 'Washing before prayer', 'Fasting', 'Praying'], 'correctIndex': 1, 'explanation': 'Wudu is the ritual washing of specific parts of the body before prayer.'},
  {'subject': 'IRS', 'year': 2007, 'question': 'What is Ghusl in Islam?', 'options': ['Partial washing', 'Complete ritual bathing', 'Praying', 'Fasting'], 'correctIndex': 1, 'explanation': 'Ghusl is the complete ritual washing of the entire body in Islamic practice.'},
  {'subject': 'IRS', 'year': 2008, 'question': 'Who was the greatest scholar of Hadith in Islam?', 'options': ['Ibn Malik', 'Imam Bukhari', 'At-Tirmidhi', 'Abu Dawood'], 'correctIndex': 1, 'explanation': 'Imam Bukhari compiled one of the most authentic Hadith collections.'},
  {'subject': 'IRS', 'year': 2009, 'question': 'What are the six major Hadith collections?', 'options': ['Sahih Bukhari, Muslim, and 4 others', 'Only Sahih Bukhari and Muslim', 'The 6 books of Fiqh', 'The Quranic chapters'], 'correctIndex': 0, 'explanation': 'The six authentic collections are by Bukhari, Muslim, Abu Dawood, At-Tirmidhi, An-Nasai, and Ibn Majah.'},

  // ---- Aqeedah (Belief) ----
  {'subject': 'IRS', 'year': 2010, 'question': 'What are the six articles of faith (Iman) in Islam?', 'options': ['Belief in Allah, Angels, Books, Prophets, Day of Judgment, Qadar', 'Only belief in Allah', 'Belief in Allah and Prophets only', 'The Five Pillars'], 'correctIndex': 0, 'explanation': 'The six articles of faith are belief in Allah, His Angels, His Books, His Prophets, the Day of Judgment, and Qadar (divine decree).'},
  {'subject': 'IRS', 'year': 2011, 'question': 'What is Tawheed in Islam?', 'options': ['Belief in many gods', 'Oneness of Allah', 'Prayer ritual', 'Charity system'], 'correctIndex': 1, 'explanation': 'Tawheed is the fundamental Islamic belief in the absolute oneness of Allah.'},
  {'subject': 'IRS', 'year': 2012, 'question': 'What is Shirk in Islam?', 'options': ['Charity', 'Associating partners with Allah', 'Fasting', 'Pilgrimage'], 'correctIndex': 1, 'explanation': 'Shirk is the sin of associating partners or equals with Allah, the gravest sin in Islam.'},
  {'subject': 'IRS', 'year': 2013, 'question': 'What is Qadar in Islamic belief?', 'options': ['Divine decree and predestination', 'Charity', 'Prayer times', 'Fasting rules'], 'correctIndex': 0, 'explanation': 'Qadar refers to belief in divine decree, that Allah has decreed all that happens.'},
  {'subject': 'IRS', 'year': 2014, 'question': 'What is the belief regarding angels in Islam?', 'options': ['They are created from light and do not disobey Allah', 'They are human-like beings', 'They can sin like humans', 'They are symbolic only'], 'correctIndex': 0, 'explanation': 'Angels are believed to be created from light, and they always obey Allah without disobedience.'},
  {'subject': 'IRS', 'year': 2015, 'question': 'Which angel is known for delivering revelation to prophets?', 'options': ['Israfil', 'Mikail', 'Jibril (Gabriel)', 'Malik'], 'correctIndex': 2, 'explanation': 'Angel Jibril (Gabriel) is known for delivering divine revelation to prophets, including Muhammad.'},
  {'subject': 'IRS', 'year': 2016, 'question': 'How many holy books are mentioned in Islamic belief?', 'options': ['2', '3', '4', '5'], 'correctIndex': 2, 'explanation': 'Four major holy books are mentioned: Torah, Zabur (Psalms), Injil (Gospel), and the Quran.'},
  {'subject': 'IRS', 'year': 2017, 'question': 'What is believed about the Day of Judgment in Islam?', 'options': ['It will never come', 'All humans will be resurrected and judged', 'Only Muslims will be judged', 'It already happened'], 'correctIndex': 1, 'explanation': 'Muslims believe all humans will be resurrected and judged by Allah on the Day of Judgment.'},
  {'subject': 'IRS', 'year': 2018, 'question': 'What is the concept of Akhirah in Islam?', 'options': ['The worldly life', 'The afterlife', 'Prayer time', 'A type of charity'], 'correctIndex': 1, 'explanation': 'Akhirah refers to the afterlife, which Muslims believe follows the Day of Judgment.'},
  {'subject': 'IRS', 'year': 2019, 'question': 'What does Iman mean in Islam?', 'options': ['Charity', 'Faith or belief', 'Pilgrimage', 'Fasting'], 'correctIndex': 1, 'explanation': 'Iman refers to faith or belief in the core tenets of Islam.'},

  // ---- Prophets in Islam ----
  {'subject': 'IRS', 'year': 2020, 'question': 'How many prophets are believed to have been sent by Allah?', 'options': ['25 named in the Quran, many more unnamed', 'Exactly 25', 'Exactly 100', 'Only 5'], 'correctIndex': 0, 'explanation': '25 prophets are named in the Quran, though tradition holds many more were sent throughout history.'},
  {'subject': 'IRS', 'year': 2021, 'question': 'Who is considered the father of prophets in Islam?', 'options': ['Adam', 'Ibrahim (Abraham)', 'Nuh (Noah)', 'Musa (Moses)'], 'correctIndex': 1, 'explanation': 'Ibrahim (Abraham) is called the father of prophets due to his descendants including many later prophets.'},
  {'subject': 'IRS', 'year': 2022, 'question': 'Which prophet built the ark to survive the flood?', 'options': ['Ibrahim', 'Nuh (Noah)', 'Musa', 'Yunus'], 'correctIndex': 1, 'explanation': 'Prophet Nuh (Noah) built the ark as commanded by Allah to survive the great flood.'},
  {'subject': 'IRS', 'year': 2023, 'question': 'Which prophet was swallowed by a whale?', 'options': ['Yunus (Jonah)', 'Musa', 'Isa', 'Dawud'], 'correctIndex': 0, 'explanation': 'Prophet Yunus (Jonah) was swallowed by a large fish/whale after leaving his people without permission.'},
  {'subject': 'IRS', 'year': 2024, 'question': 'Which prophet is known for parting the sea to escape Pharaoh?', 'options': ['Musa (Moses)', 'Isa (Jesus)', 'Ibrahim', 'Sulaiman'], 'correctIndex': 0, 'explanation': 'Prophet Musa (Moses) parted the sea with the help of Allah to escape Pharaoh and his army.'},
  {'subject': 'IRS', 'year': 2025, 'question': 'Which prophet is known for his wisdom and could speak to animals?', 'options': ['Dawud (David)', 'Sulaiman (Solomon)', 'Musa', 'Isa'], 'correctIndex': 1, 'explanation': 'Prophet Sulaiman (Solomon) was granted wisdom and the ability to understand and command animals.'},
  {'subject': 'IRS', 'year': 2026, 'question': 'Which prophet is believed to have been born without a father?', 'options': ['Isa (Jesus)', 'Adam', 'Musa', 'Yusuf'], 'correctIndex': 0, 'explanation': 'Prophet Isa (Jesus) is believed to have been born miraculously to Maryam without a father.'},
  {'subject': 'IRS', 'year': 2000, 'question': 'Who is considered the first human and first prophet in Islam?', 'options': ['Nuh', 'Adam', 'Ibrahim', 'Idris'], 'correctIndex': 1, 'explanation': 'Adam is regarded as the first human being and the first prophet in Islam.'},
  {'subject': 'IRS', 'year': 2001, 'question': 'Which prophet interpreted dreams and rose to power in Egypt?', 'options': ['Yusuf (Joseph)', 'Musa', 'Harun', 'Ayyub'], 'correctIndex': 0, 'explanation': 'Prophet Yusuf (Joseph) was known for interpreting dreams and later became a trusted official in Egypt.'},
  {'subject': 'IRS', 'year': 2002, 'question': 'Which prophet was tested with severe illness and loss but remained patient?', 'options': ['Ayyub (Job)', 'Ibrahim', 'Musa', 'Nuh'], 'correctIndex': 0, 'explanation': 'Prophet Ayyub (Job) is known in Islamic tradition for his extraordinary patience during severe trials.'},

  // ---- Islamic Ethics (Akhlaq) ----
  {'subject': 'IRS', 'year': 2003, 'question': 'What is the Islamic concept of Ihsan?', 'options': ['Excellence in worship and conduct, as if seeing Allah', 'Charity only', 'Fasting rules', 'Pilgrimage rites'], 'correctIndex': 0, 'explanation': 'Ihsan means striving for excellence in worship and behavior, worshipping Allah as though you see Him.'},
  {'subject': 'IRS', 'year': 2004, 'question': 'What does Islam teach about honesty (Sidq)?', 'options': ['It is optional', 'It is a core virtue required of Muslims', 'Only required in business', 'Only required with family'], 'correctIndex': 1, 'explanation': 'Honesty (Sidq) is emphasized as a core virtue in all aspects of a Muslim\'s life.'},
  {'subject': 'IRS', 'year': 2005, 'question': 'What is the Islamic teaching on kindness to parents?', 'options': ['Optional act of goodness', 'A major obligation, second only to worshipping Allah', 'Only required from sons', 'Not specifically mentioned'], 'correctIndex': 1, 'explanation': 'Kindness to parents is emphasized strongly in the Quran, often mentioned right after worship of Allah.'},
  {'subject': 'IRS', 'year': 2006, 'question': 'What virtue does Islam emphasize regarding patience during hardship?', 'options': ['Anger', 'Sabr (patience)', 'Revenge', 'Isolation'], 'correctIndex': 1, 'explanation': 'Sabr (patience) is highly regarded in Islam as a virtue during times of difficulty and hardship.'},
  {'subject': 'IRS', 'year': 2007, 'question': 'What does Islam say about backbiting (Gheebah)?', 'options': ['It is encouraged', 'It is strictly forbidden', 'It is neutral', 'It is only forbidden in Ramadan'], 'correctIndex': 1, 'explanation': 'Backbiting is strictly forbidden in Islam and is compared in the Quran to eating the flesh of a dead brother.'},
  {'subject': 'IRS', 'year': 2008, 'question': 'What is the Islamic view on humility (Tawadu)?', 'options': ['Discouraged', 'A praised character trait', 'Only for scholars', 'Sign of weakness'], 'correctIndex': 1, 'explanation': 'Humility is a highly praised character trait in Islam, exemplified by the Prophet himself.'},
  {'subject': 'IRS', 'year': 2009, 'question': 'What does Islam teach about honoring guests?', 'options': ['Optional courtesy', 'An important part of good character', 'Only for wealthy hosts', 'Discouraged'], 'correctIndex': 1, 'explanation': 'Honoring guests is considered an important sign of good character (Akhlaq) in Islamic teaching.'},
  {'subject': 'IRS', 'year': 2010, 'question': 'What is the Islamic teaching regarding trustworthiness (Amanah)?', 'options': ['Only applies to money', 'A core value expected of every Muslim', 'Only for leaders', 'Optional'], 'correctIndex': 1, 'explanation': 'Amanah (trustworthiness) is a core value expected in all dealings by every Muslim.'},
  {'subject': 'IRS', 'year': 2011, 'question': 'What is Islam\'s teaching on anger management?', 'options': ['Express anger freely', 'Control anger and seek forgiveness', 'Anger is always wrong to feel', 'No guidance given'], 'correctIndex': 1, 'explanation': 'Islam teaches Muslims to control anger, remain calm, and seek Allah\'s forgiveness in moments of anger.'},
  {'subject': 'IRS', 'year': 2012, 'question': 'What does Islam say about generosity?', 'options': ['Discouraged to avoid poverty', 'Highly encouraged as a virtue', 'Only required during Ramadan', 'Only for the wealthy'], 'correctIndex': 1, 'explanation': 'Generosity is highly encouraged in Islam as a reflection of good character and gratitude to Allah.'},

  // ---- Family & Social Issues ----
  {'subject': 'IRS', 'year': 2013, 'question': 'What is the Islamic view on marriage (Nikah)?', 'options': ['Discouraged', 'A recommended and important social institution', 'Forbidden for young people', 'Optional ritual only'], 'correctIndex': 1, 'explanation': 'Marriage (Nikah) is highly recommended in Islam as a foundation of family and society.'},
  {'subject': 'IRS', 'year': 2014, 'question': 'What is Mahr in an Islamic marriage?', 'options': ['A gift from bride to groom', 'A mandatory gift from groom to bride', 'A tax paid to the state', 'A type of divorce'], 'correctIndex': 1, 'explanation': 'Mahr is a mandatory gift given by the groom to the bride as part of the marriage contract.'},
  {'subject': 'IRS', 'year': 2015, 'question': 'What is Talaq in Islam?', 'options': ['Marriage contract', 'Divorce', 'Charity', 'Pilgrimage'], 'correctIndex': 1, 'explanation': 'Talaq refers to divorce in Islamic law, governed by specific rules and waiting periods.'},
  {'subject': 'IRS', 'year': 2016, 'question': 'What is the Islamic teaching on raising children?', 'options': ['Parents have no responsibility', 'Parents must raise children with faith and good conduct', 'Only mothers are responsible', 'Only fathers are responsible'], 'correctIndex': 1, 'explanation': 'Islam places great emphasis on both parents raising children with strong faith and moral character.'},
  {'subject': 'IRS', 'year': 2017, 'question': 'What does Islam teach about inheritance (Mirath)?', 'options': ['No fixed rules exist', 'Fixed shares are prescribed in the Quran', 'Only sons inherit', 'Only the eldest child inherits'], 'correctIndex': 1, 'explanation': 'The Quran prescribes specific fixed shares of inheritance for family members.'},
  {'subject': 'IRS', 'year': 2018, 'question': 'What is the Islamic ruling on interest (Riba)?', 'options': ['Encouraged in business', 'Strictly forbidden', 'Allowed in small amounts', 'Only forbidden for Muslims'], 'correctIndex': 1, 'explanation': 'Riba (interest/usury) is strictly forbidden in Islamic financial dealings.'},
  {'subject': 'IRS', 'year': 2019, 'question': 'What is the concept of Ummah in Islam?', 'options': ['A single family', 'The global community of Muslims', 'A local mosque', 'A charity organization'], 'correctIndex': 1, 'explanation': 'Ummah refers to the worldwide community of Muslims united by faith.'},
  {'subject': 'IRS', 'year': 2020, 'question': 'What does Islam teach about neighbors?', 'options': ['No special rights are given', 'Neighbors have rights and should be treated kindly', 'Only Muslim neighbors have rights', 'Neighbors should be avoided'], 'correctIndex': 1, 'explanation': 'Islam teaches that neighbors have rights and should be treated with kindness regardless of faith.'},
  {'subject': 'IRS', 'year': 2021, 'question': 'What is Sadaqah in Islam?', 'options': ['Obligatory charity', 'Voluntary charity', 'A type of prayer', 'A pilgrimage rite'], 'correctIndex': 1, 'explanation': 'Sadaqah refers to voluntary charity given beyond the obligatory Zakat.'},
  {'subject': 'IRS', 'year': 2022, 'question': 'What is the Islamic teaching regarding orphans?', 'options': ['They should be ignored', 'They should be cared for and their rights protected', 'Only relatives can help them', 'No specific teaching exists'], 'correctIndex': 1, 'explanation': 'Islam places strong emphasis on caring for orphans and protecting their rights and property.'},

  // ---- Worship (Salat details) ----
  {'subject': 'IRS', 'year': 2023, 'question': 'What is the direction Muslims face during prayer called?', 'options': ['Sunnah', 'Qibla', 'Adhan', 'Iqama'], 'correctIndex': 1, 'explanation': 'Qibla is the direction facing the Kaaba in Makkah, which Muslims face during prayer.'},
  {'subject': 'IRS', 'year': 2024, 'question': 'What is the call to prayer called in Islam?', 'options': ['Iqama', 'Adhan', 'Khutbah', 'Dua'], 'correctIndex': 1, 'explanation': 'Adhan is the call to prayer announced before each of the five daily prayers.'},
  {'subject': 'IRS', 'year': 2025, 'question': 'What is Jumuah in Islam?', 'options': ['Friday congregational prayer', 'Daily prayer', 'Fasting day', 'Charity collection'], 'correctIndex': 0, 'explanation': 'Jumuah is the Friday congregational prayer, considered highly important in Islam.'},
  {'subject': 'IRS', 'year': 2026, 'question': 'What is a Rakah in Islamic prayer?', 'options': ['A unit of prayer consisting of set movements and recitations', 'A charity payment', 'A pilgrimage stage', 'A fasting period'], 'correctIndex': 0, 'explanation': 'A Rakah is one complete unit of the Islamic prayer, including standing, bowing, and prostration.'},
  {'subject': 'IRS', 'year': 2000, 'question': 'What is Sujud in Islamic prayer?', 'options': ['Standing position', 'Bowing position', 'Prostration position', 'Sitting position'], 'correctIndex': 2, 'explanation': 'Sujud is the position of prostration, touching the forehead to the ground during prayer.'},
  {'subject': 'IRS', 'year': 2001, 'question': 'What is Tayammum in Islam?', 'options': ['Prayer with water', 'Dry ablution using sand or dust when water is unavailable', 'A type of fasting', 'A pilgrimage rite'], 'correctIndex': 1, 'explanation': 'Tayammum is a dry ritual purification using clean sand or dust when water is unavailable.'},
  {'subject': 'IRS', 'year': 2002, 'question': 'What breaks the fast during Ramadan?', 'options': ['Sleeping', 'Eating or drinking intentionally', 'Praying', 'Reading Quran'], 'correctIndex': 1, 'explanation': 'Intentionally eating or drinking during fasting hours breaks the fast in Ramadan.'},
  {'subject': 'IRS', 'year': 2003, 'question': 'What is Itikaf in Islam?', 'options': ['Charity giving', 'Spiritual retreat in the mosque, often during the last 10 days of Ramadan', 'Pilgrimage rite', 'Marriage ceremony'], 'correctIndex': 1, 'explanation': 'Itikaf is a spiritual retreat in the mosque, commonly practiced during the last ten days of Ramadan.'},
  {'subject': 'IRS', 'year': 2004, 'question': 'What is Dua in Islam?', 'options': ['Formal prayer', 'Personal supplication to Allah', 'Fasting', 'Charity'], 'correctIndex': 1, 'explanation': 'Dua refers to personal supplication or prayer made directly to Allah, outside formal prayer.'},
  {'subject': 'IRS', 'year': 2005, 'question': 'What is Tasbih in Islam?', 'options': ['A pilgrimage act', 'Glorifying Allah through repeated phrases, often using prayer beads', 'A charity fund', 'A type of fasting'], 'correctIndex': 1, 'explanation': 'Tasbih involves glorifying Allah by repeating phrases like SubhanAllah, often counted with prayer beads.'},

  // ---- General Islamic Knowledge ----
  {'subject': 'IRS', 'year': 2006, 'question': 'What is the Kaaba?', 'options': ['A mosque in Madinah', 'The sacred cube-shaped building in Makkah', 'A holy book', 'A prayer mat'], 'correctIndex': 1, 'explanation': 'The Kaaba is the sacred cube-shaped structure in Makkah that Muslims face during prayer.'},
  {'subject': 'IRS', 'year': 2007, 'question': 'What is the Islamic calendar based on?', 'options': ['The solar cycle', 'The lunar cycle', 'A fixed 365-day year', 'The Gregorian calendar'], 'correctIndex': 1, 'explanation': 'The Islamic (Hijri) calendar is based on the lunar cycle, with each month beginning at the new moon.'},
  {'subject': 'IRS', 'year': 2008, 'question': 'What is the first month of the Islamic calendar?', 'options': ['Ramadan', 'Muharram', 'Shawwal', 'Dhul-Hijjah'], 'correctIndex': 1, 'explanation': 'Muharram is the first month of the Islamic (Hijri) calendar.'},
  {'subject': 'IRS', 'year': 2009, 'question': 'What is the significance of the Black Stone at the Kaaba?', 'options': ['It marks the starting point for Tawaf (circling the Kaaba)', 'It is worshipped by Muslims', 'It has no significance', 'It marks the Qibla direction only'], 'correctIndex': 0, 'explanation': 'The Black Stone marks the starting and ending point for the ritual of Tawaf around the Kaaba.'},
  {'subject': 'IRS', 'year': 2010, 'question': 'What is Tawaf during Hajj?', 'options': ['Running between two hills', 'Circling the Kaaba seven times', 'Standing at Arafat', 'Throwing stones at pillars'], 'correctIndex': 1, 'explanation': 'Tawaf is the ritual of circling the Kaaba seven times during Hajj and Umrah.'},
  {'subject': 'IRS', 'year': 2011, 'question': 'What is Sa\'i during Hajj?', 'options': ['Circling the Kaaba', 'Running/walking between the hills of Safa and Marwah', 'Standing at Arafat', 'Sacrificing an animal'], 'correctIndex': 1, 'explanation': "Sa'i is the ritual of walking or running seven times between the hills of Safa and Marwah."},
  {'subject': 'IRS', 'year': 2012, 'question': 'What is Wuquf at Arafat during Hajj?', 'options': ['Standing at the plain of Arafat, a central rite of Hajj', 'A type of fasting', 'A charity act', 'A prayer time'], 'correctIndex': 0, 'explanation': 'Wuquf, standing at the plain of Arafat, is considered the most essential rite of Hajj.'},
  {'subject': 'IRS', 'year': 2013, 'question': 'What is the significance of Umrah compared to Hajj?', 'options': ['They are identical', 'Umrah is a minor pilgrimage that can be performed any time of year', 'Umrah is only performed by non-Muslims', 'Umrah replaces Hajj entirely'], 'correctIndex': 1, 'explanation': 'Umrah is a minor pilgrimage with fewer rites than Hajj and can be performed at any time of the year.'},
  {'subject': 'IRS', 'year': 2014, 'question': 'What language was the Quran revealed in?', 'options': ['Persian', 'Arabic', 'Turkish', 'Urdu'], 'correctIndex': 1, 'explanation': 'The Quran was revealed in Arabic to Prophet Muhammad.'},
  {'subject': 'IRS', 'year': 2015, 'question': 'What is the significance of the phrase Bismillah?', 'options': ['A greeting', "Beginning an action in the name of Allah", 'A farewell phrase', 'A charity announcement'], 'correctIndex': 1, 'explanation': 'Bismillah means "In the name of Allah" and is recited before beginning most actions.'},
  {'subject': 'IRS', 'year': 2016, 'question': 'What does the term Sunnah refer to?', 'options': ['The Quran itself', 'The sayings, actions, and approvals of Prophet Muhammad', 'A type of charity', 'A pilgrimage rite'], 'correctIndex': 1, 'explanation': 'Sunnah refers to the recorded sayings, actions, and approvals of Prophet Muhammad, second in authority to the Quran.'},
  {'subject': 'IRS', 'year': 2017, 'question': 'What is a Hadith?', 'options': ['A verse of the Quran', 'A recorded saying or action of Prophet Muhammad', 'A pilgrimage site', 'A charity fund'], 'correctIndex': 1, 'explanation': 'A Hadith is a recorded report of the sayings, actions, or approvals of Prophet Muhammad.'},
  {'subject': 'IRS', 'year': 2018, 'question': 'What is the Masjid al-Haram?', 'options': ['The mosque in Madinah', 'The Grand Mosque in Makkah surrounding the Kaaba', 'A mosque in Jerusalem', 'A small local mosque'], 'correctIndex': 1, 'explanation': 'Masjid al-Haram is the Grand Mosque in Makkah that surrounds the Kaaba.'},
];
