// lib/questions_irs.dart
//
// Islamic Religious Studies (IRS) question bank — 100 questions.
// Topics: Quranic Studies, Hadith, Islamic History, Islamic Law (Fiqh), Aqeedah (Belief).
// Year cycle: 2000–2026. Explanations in English.

final List<Map<String, dynamic>> irsQuestions = [
  // ---- Quranic Studies ----
  {'subject': 'IRS', 'year': 2000, 'question': 'How many chapters (surahs) are there in the Quran?', 'options': ['99', '114', '150', '120'], 'correctIndex': 1, 'explanation': 'The Quran has 114 surahs (chapters).'},
  {'subject': 'IRS', 'year': 2001, 'question': 'How many verses (ayahs) are in the Quran approximately?', 'options': ['2000', '4000', '6000', '8000'], 'correctIndex': 2, 'explanation': 'The Quran contains approximately 6,236 verses.'},
  {'subject': 'IRS', 'year': 2002, 'question': 'Which surah is the longest in the Quran?', 'options': ['Surah Al-Baqarah', 'Surah Al-Imran', 'Surah An-Nisa', 'Surah Al-Maaidah'], 'correctIndex': 0, 'explanation': 'Surah Al-Baqarah (The Cow) is the longest surah with 286 verses.'},
  {'subject': 'IRS', 'year': 2003, 'question': 'Which surah is the shortest in the Quran?', 'options': ['Surah Al-Kawthar', 'Surah Al-Ikhlas', 'Surah Al-Asr', 'Surah Al-Fil'], 'correctIndex': 0, 'explanation': 'Surah Al-Kawthar is the shortest with only 3 verses.'},
  {'subject': 'IRS', 'year': 2004, 'question': 'What is the first surah of the Quran?', 'options': ['Surah Al-Asr', 'Surah Al-Fatiha', 'Surah Al-Baqarah', 'Surah Yunus'], 'correctIndex': 1, 'explanation': 'Surah Al-Fatiha (The Opening) is the first surah of the Quran.'},
  {'subject': 'IRS', 'year': 2005, 'question': 'What is the last surah of the Quran?', 'options': ['Surah An-Nas', 'Surah Al-Ikhlas', 'Surah Al-Kawthar', 'Surah Al-Masad'], 'correctIndex': 0, 'explanation': 'Surah An-Nas (Mankind) is the last surah of the Quran.'},
  {'subject': 'IRS', 'year': 2006, 'question': 'What is the significance of Juz in the Quran?', 'options': ['A chapter', 'A verse', 'One of 30 equal parts', 'A section of a surah'], 'correctIndex': 2, 'explanation': 'Juz refers to one of the 30 equal parts of the Quran for reading.'},
  {'subject': 'IRS', 'year': 2007, 'question': 'Which city was the Quran mostly revealed in?', 'options': ['Madinah', 'Makkah', 'Medina', 'Taif'], 'correctIndex': 1, 'explanation': 'Most of the Quran was revealed in Makkah during the first period of revelation.'},
  {'subject': 'IRS', 'year': 2008, 'question': 'What does \'Makki\' refer to in Quranic studies?', 'options': ['Verses revealed in Madinah', 'Verses revealed in Makkah', 'Verses about trade', 'Verses about war'], 'correctIndex': 1, 'explanation': 'Makki refers to chapters revealed in Makkah before the Hijrah.'},
  {'subject': 'IRS', 'year': 2009, 'question': 'What does \'Madani\' refer to in Quranic studies?', 'options': ['Verses revealed in Makkah', 'Verses revealed in Madinah', 'Verses about prayer', 'Verses about charity'], 'correctIndex': 1, 'explanation': 'Madani refers to chapters revealed in Madinah after the Hijrah.'},

  // ---- Five Pillars of Islam ----
  {'subject': 'IRS', 'year': 2010, 'question': 'How many daily prayers are required in Islam?', 'options': ['3', '4', '5', '6'], 'correctIndex': 2, 'explanation': 'Muslims are required to perform 5 daily prayers (Salat).'},
  {'subject': 'IRS', 'year': 2011, 'question': 'What is the Islamic month of fasting called?', 'options': ['Muharram', 'Ramadan', 'Shawwal', 'Hajj'], 'correctIndex': 1, 'explanation': 'Ramadan is the month of fasting in the Islamic calendar.'},
  {'subject': 'IRS', 'year': 2012, 'question': 'What is the minimum amount of charity (Zakat) in Islamic law?', 'options': ['1%', '2%', '2.5%', '5%'], 'correctIndex': 2, 'explanation': 'Zakat is 2.5% of saved wealth given to the poor and needy.'},
  {'subject': 'IRS', 'year': 2013, 'question': 'At what age is the Hajj (pilgrimage) obligatory for Muslims?', 'options': ['18 years', '25 years', 'Anytime after puberty', 'After retirement'], 'correctIndex': 2, 'explanation': 'Hajj is obligatory for all Muslims who are physically and financially able.'},
  {'subject': 'IRS', 'year': 2014, 'question': 'What is the Islamic declaration of faith called?', 'options': ['Salat', 'Shahada', 'Zakat', 'Hajj'], 'correctIndex': 1, 'explanation': 'The Shahada is the declaration: \'There is no god but Allah, and Muhammad is His messenger.\'''},
  {'subject': 'IRS', 'year': 2015, 'question': 'Which pillar of Islam emphasizes belief in Allah and His oneness?', 'options': ['Salat', 'Zakat', 'Shahada', 'Hajj'], 'correctIndex': 2, 'explanation': 'The Shahada is the foundation, declaring belief in Allah\'s oneness and Muhammad as His messenger.'},
  {'subject': 'IRS', 'year': 2016, 'question': 'When is the Hajj performed during the Islamic calendar?', 'options': ['During Ramadan', 'During Muharram', 'During the month of Dhul-Hijjah', 'During Safar'], 'correctIndex': 2, 'explanation': 'The Hajj is performed in the month of Dhul-Hijjah, the 12th month.'},
  {'subject': 'IRS', 'year': 2017, 'question': 'What is the night of power (Laylat al-Qadr)?', 'options': ['The night of Hajj', 'The first night of Ramadan', 'The night when the Quran began revelation', 'The night of Eid'], 'correctIndex': 2, 'explanation': 'Laylat al-Qadr is the night when the Quran was first revealed to Prophet Muhammad.'},
  {'subject': 'IRS', 'year': 2018, 'question': 'What is Eid al-Fitr?', 'options': ['Celebration of Hajj', 'Celebration ending Ramadan', 'Celebration of Islamic New Year', 'Celebration of Mecca'], 'correctIndex': 1, 'explanation': 'Eid al-Fitr is the festival marking the end of Ramadan (the month of fasting).'},
  {'subject': 'IRS', 'year': 2019, 'question': 'What is Eid al-Adha?', 'options': ['Ending of Ramadan', 'Celebration of Abraham\'s sacrifice', 'Islamic New Year', 'Celebration of Prophet\'s birthday'], 'correctIndex': 1, 'explanation': 'Eid al-Adha commemorates Prophet Ibrahim\'s willingness to sacrifice his son.'},

  // ---- Islamic History ----
  {'subject': 'IRS', 'year': 2020, 'question': 'What is the Hijrah?', 'options': ['Pilgrimage to Mecca', 'Migration of Prophet Muhammad', 'Night journey', 'Battle'], 'correctIndex': 1, 'explanation': 'The Hijrah is the migration of Prophet Muhammad from Makkah to Madinah in 622 CE.'},
  {'subject': 'IRS', 'year': 2021, 'question': 'In what year did Prophet Muhammad start his prophethood?', 'options': ['570 CE', '610 CE', '630 CE', '650 CE'], 'correctIndex': 1, 'explanation': 'Prophet Muhammad received his first revelation at age 40 in 610 CE.'},
  {'subject': 'IRS', 'year': 2022, 'question': 'How many years did Prophet Muhammad live?', 'options': ['50 years', '60 years', '63 years', '70 years'], 'correctIndex': 2, 'explanation': 'Prophet Muhammad lived for 63 years (570-632 CE).'},
  {'subject': 'IRS', 'year': 2023, 'question': 'Who was the first Muslim?', 'options': ['Khadijah', 'Ali ibn Abi Talib', 'Abu Bakr', 'Prophet Muhammad'], 'correctIndex': 0, 'explanation': 'Khadijah, the Prophet\'s wife, was the first to believe in Islam.'},
  {'subject': 'IRS', 'year': 2024, 'question': 'Who was the first Caliph (leader) after Prophet Muhammad?', 'options': ['Umar ibn Al-Khattab', 'Ali ibn Abi Talib', 'Abu Bakr', 'Uthman ibn Affan'], 'correctIndex': 2, 'explanation': 'Abu Bakr As-Siddiq was the first Caliph of Islam.'},
  {'subject': 'IRS', 'year': 2025, 'question': 'What was the first battle in Islam?', 'options': ['Battle of Uhud', 'Battle of Badr', 'Battle of Khandaq', 'Battle of Khaybar'], 'correctIndex': 1, 'explanation': 'The Battle of Badr (624 CE) was the first battle in Islam.'},
  {'subject': 'IRS', 'year': 2026, 'question': 'How many wives did Prophet Muhammad have?', 'options': ['4', '6', '9', '11'], 'correctIndex': 3, 'explanation': 'Prophet Muhammad had 11 wives in total throughout his life.'},

  // ---- Islamic Law (Fiqh) ----
  {'subject': 'IRS', 'year': 2000, 'question': 'What is Halal?', 'options': ['Forbidden', 'Lawful in Islamic law', 'Neutral', 'Doubtful'], 'correctIndex': 1, 'explanation': 'Halal means permissible or lawful according to Islamic law.'},
  {'subject': 'IRS', 'year': 2001, 'question': 'What is Haram?', 'options': ['Lawful', 'Forbidden in Islamic law', 'Neutral', 'Recommended'], 'correctIndex': 1, 'explanation': 'Haram means forbidden or prohibited in Islamic law.'},
  {'subject': 'IRS', 'year': 2002, 'question': 'What is Istidlal in Islamic jurisprudence?', 'options': ['Following consensus', 'Using analogical reasoning', 'Personal opinion', 'Following tradition'], 'correctIndex': 1, 'explanation': 'Istidlal (Qiyas) is reasoning by analogy to derive Islamic rulings.'},
  {'subject': 'IRS', 'year': 2003, 'question': 'What is Ijma in Islamic jurisprudence?', 'options': ['Personal reasoning', 'Consensus of scholars', 'Following the Quran', 'Following Hadith'], 'correctIndex': 1, 'explanation': 'Ijma is the consensus of Muslim scholars on a religious matter.'},
  {'subject': 'IRS', 'year': 2004, 'question': 'What are the main sources of Islamic law?', 'options': ['Only the Quran', 'Quran and Hadith', 'Quran, Hadith, Ijma, and Qiyas', 'Only the Sunnah'], 'correctIndex': 2, 'explanation': 'The four primary sources are: Quran, Sunnah (Hadith), Ijma, and Qiyas.'},
  {'subject': 'IRS', 'year': 2005, 'question': 'What is Hudud in Islamic law?', 'options': ['Permitted actions', 'Forbidden boundaries', 'Fixed punishments for grave sins', 'Recommended deeds'], 'correctIndex': 2, 'explanation': 'Hudud refers to fixed punishments prescribed by Islamic law for specific crimes.'},
  {'subject': 'IRS', 'year': 2006, 'question': 'What is Wudu (ablution) in Islam?', 'options': ['Ritual bathing', 'Washing before prayer', 'Fasting', 'Praying'], 'correctIndex': 1, 'explanation': 'Wudu is the ritual washing of specific parts of the body before prayer.'},
  {'subject': 'IRS', 'year': 2007, 'question': 'What is Ghusl in Islam?', 'options': ['Partial washing', 'Complete ritual bathing', 'Praying', 'Fasting'], 'correctIndex': 1, 'explanation': 'Ghusl is the complete ritual washing of the entire body in Islamic practice.'},
  {'subject': 'IRS', 'year': 2008, 'question': 'Who was the greatest scholar of Hadith in Islam?', 'options': ['Ibn Malik', 'Imam Bukhari', 'At-Tirmidhi', 'Abu Dawood'], 'correctIndex': 1, 'explanation': 'Imam Bukhari compiled one of the most authentic Hadith collections.'},
  {'subject': 'IRS', 'year': 2009, 'question': 'What are the six major Hadith collections?', 'options': ['Sahih Bukhari, Muslim, and 4 others', 'Only Sahih Bukhari and Muslim', 'The 6 books of Fiqh', 'The Quranic chapters'], 'correctIndex': 0, 'explanation': 'The six authentic collections are by Bukhari, Muslim, Abu Dawood, At-Tirmidhi, An-Nasai, and Ibn Majah.'}
];
