// lib/questions_data.dart
//
// Raw question data for NaijaLearn.
// Each entry is a plain Map with these keys:
//   subject      (String, must match a name in kSubjects in main.dart)
//   year         (int)
//   question     (String)
//   options      (List<String>, exactly 4 entries)
//   correctIndex (int, 0-3)
//   explanation  (String, optional but recommended)
//
// To add more questions: just append more Map entries to this list.
// No other file needs to change.

final List<Map<String, dynamic>> sampleQuestionsData = [
  // ---------------- English ----------------
  {
    'subject': 'English',
    'year': 2021,
    'question': "Choose the option that best completes the sentence: She is ___ honest woman.",
    'options': ['a', 'an', 'the', 'no article needed'],
    'correctIndex': 1,
    'explanation': "'Honest' starts with a vowel sound, so 'an' is used.",
  },
  {
    'subject': 'English',
    'year': 2022,
    'question': "Select the correctly spelt word.",
    'options': ['Accomodate', 'Acommodate', 'Accommodate', 'Acomodate'],
    'correctIndex': 2,
    'explanation': "The correct spelling is 'Accommodate' with double C and double M.",
  },
  {
    'subject': 'English',
    'year': 2019,
    'question': "What is the synonym of 'Benevolent'?",
    'options': ['Cruel', 'Kind', 'Selfish', 'Angry'],
    'correctIndex': 1,
    'explanation': "'Benevolent' means kind and generous.",
  },
  {
    'subject': 'English',
    'year': 2023,
    'question': "Identify the figure of speech: 'The classroom was a zoo.'",
    'options': ['Simile', 'Metaphor', 'Personification', 'Hyperbole'],
    'correctIndex': 1,
    'explanation': "A direct comparison without 'like' or 'as' is a metaphor.",
  },
  {
    'subject': 'English',
    'year': 2020,
    'question': "Choose the antonym of 'Ancient'.",
    'options': ['Old', 'Modern', 'Historic', 'Aged'],
    'correctIndex': 1,
    'explanation': "'Modern' is the opposite of 'Ancient'.",
  },
  {
    'subject': 'English',
    'year': 2024,
    'question': "Which sentence is grammatically correct?",
    'options': [
      "He don't like rice",
      "He doesn't likes rice",
      "He doesn't like rice",
      "He not like rice"
    ],
    'correctIndex': 2,
    'explanation': "Third person singular negative uses 'doesn't' + base verb.",
  },

  // ---------------- Mathematics ----------------
  {
    'subject': 'Mathematics',
    'year': 2021,
    'question': "Simplify: 3x + 5x - 2x",
    'options': ['6x', '8x', '10x', '4x'],
    'correctIndex': 0,
    'explanation': "3x + 5x - 2x = 6x.",
  },
  {
    'subject': 'Mathematics',
    'year': 2022,
    'question': "What is the value of x if 2x + 6 = 20?",
    'options': ['5', '6', '7', '8'],
    'correctIndex': 2,
    'explanation': "2x = 14, so x = 7.",
  },
  {
    'subject': 'Mathematics',
    'year': 2019,
    'question': "Find the area of a rectangle with length 8cm and width 5cm.",
    'options': ['13cm²', '26cm²', '40cm²', '45cm²'],
    'correctIndex': 2,
    'explanation': "Area = length × width = 8 × 5 = 40cm².",
  },
  {
    'subject': 'Mathematics',
    'year': 2023,
    'question': "What is 15% of 200?",
    'options': ['20', '25', '30', '35'],
    'correctIndex': 2,
    'explanation': "15% of 200 = 0.15 × 200 = 30.",
  },
  {
    'subject': 'Mathematics',
    'year': 2020,
    'question': "Solve for x: x² = 49",
    'options': ['x = 6', 'x = 7', 'x = 8', 'x = 9'],
    'correctIndex': 1,
    'explanation': "√49 = 7.",
  },
  {
    'subject': 'Mathematics',
    'year': 2024,
    'question': "What is the next number in the sequence: 2, 4, 8, 16, ___?",
    'options': ['20', '24', '32', '18'],
    'correctIndex': 2,
    'explanation': "Each term doubles the previous one; 16 × 2 = 32.",
  },

  // ---------------- Physics ----------------
  {
    'subject': 'Physics',
    'year': 2021,
    'question': "What is the SI unit of force?",
    'options': ['Joule', 'Newton', 'Watt', 'Pascal'],
    'correctIndex': 1,
    'explanation': "Force is measured in Newtons (N).",
  },
  {
    'subject': 'Physics',
    'year': 2022,
    'question': "Which law states that for every action there is an equal and opposite reaction?",
    'options': ["Newton's First Law", "Newton's Second Law", "Newton's Third Law", "Law of Gravitation"],
    'correctIndex': 2,
    'explanation': "This is Newton's Third Law of Motion.",
  },
  {
    'subject': 'Physics',
    'year': 2019,
    'question': "What is the speed of light in a vacuum (approx)?",
    'options': ['3 × 10⁶ m/s', '3 × 10⁸ m/s', '3 × 10¹⁰ m/s', '3 × 10⁵ m/s'],
    'correctIndex': 1,
    'explanation': "The speed of light is approximately 3 × 10⁸ m/s.",
  },
  {
    'subject': 'Physics',
    'year': 2023,
    'question': "A body at rest has what type of energy relative to motion?",
    'options': ['Kinetic energy only', 'No energy', 'Potential energy only', 'Both kinetic and potential'],
    'correctIndex': 2,
    'explanation': "A body at rest has zero kinetic energy but may have potential energy.",
  },
  {
    'subject': 'Physics',
    'year': 2020,
    'question': "What instrument is used to measure current?",
    'options': ['Voltmeter', 'Ammeter', 'Barometer', 'Thermometer'],
    'correctIndex': 1,
    'explanation': "An ammeter measures electric current.",
  },
  {
    'subject': 'Physics',
    'year': 2024,
    'question': "What is the unit of electrical resistance?",
    'options': ['Volt', 'Ampere', 'Ohm', 'Watt'],
    'correctIndex': 2,
    'explanation': "Resistance is measured in Ohms (Ω).",
  },

  // ---------------- Chemistry ----------------
  {
    'subject': 'Chemistry',
    'year': 2021,
    'question': "What is the chemical symbol for Sodium?",
    'options': ['So', 'Sd', 'Na', 'S'],
    'correctIndex': 2,
    'explanation': "Sodium's symbol, Na, comes from its Latin name 'Natrium'.",
  },
  {
    'subject': 'Chemistry',
    'year': 2022,
    'question': "What is the pH of a neutral solution?",
    'options': ['0', '7', '14', '10'],
    'correctIndex': 1,
    'explanation': "A neutral solution has a pH of 7.",
  },
  {
    'subject': 'Chemistry',
    'year': 2019,
    'question': "Which gas is most abundant in the Earth's atmosphere?",
    'options': ['Oxygen', 'Carbon dioxide', 'Nitrogen', 'Hydrogen'],
    'correctIndex': 2,
    'explanation': "Nitrogen makes up about 78% of the atmosphere.",
  },
  {
    'subject': 'Chemistry',
    'year': 2023,
    'question': "What type of bond involves the sharing of electron pairs?",
    'options': ['Ionic bond', 'Covalent bond', 'Metallic bond', 'Hydrogen bond'],
    'correctIndex': 1,
    'explanation': "A covalent bond forms when atoms share electron pairs.",
  },
  {
    'subject': 'Chemistry',
    'year': 2020,
    'question': "What is the atomic number of Hydrogen?",
    'options': ['0', '1', '2', '3'],
    'correctIndex': 1,
    'explanation': "Hydrogen has 1 proton, giving it atomic number 1.",
  },
  {
    'subject': 'Chemistry',
    'year': 2024,
    'question': "Which of these is an example of an exothermic reaction?",
    'options': ['Photosynthesis', 'Combustion', 'Melting ice', 'Evaporation'],
    'correctIndex': 1,
    'explanation': "Combustion releases heat, making it exothermic.",
  },

  // ---------------- Biology ----------------
  {
    'subject': 'Biology',
    'year': 2021,
    'question': "What is the powerhouse of the cell?",
    'options': ['Nucleus', 'Ribosome', 'Mitochondria', 'Golgi body'],
    'correctIndex': 2,
    'explanation': "Mitochondria produce ATP, the cell's energy currency.",
  },
  {
    'subject': 'Biology',
    'year': 2022,
    'question': "Which blood cells are responsible for fighting infection?",
    'options': ['Red blood cells', 'White blood cells', 'Platelets', 'Plasma'],
    'correctIndex': 1,
    'explanation': "White blood cells (leukocytes) defend the body against infection.",
  },
  {
    'subject': 'Biology',
    'year': 2019,
    'question': "What process do plants use to make food?",
    'options': ['Respiration', 'Photosynthesis', 'Transpiration', 'Digestion'],
    'correctIndex': 1,
    'explanation': "Photosynthesis converts light energy into chemical energy in plants.",
  },
  {
    'subject': 'Biology',
    'year': 2023,
    'question': "How many chambers does the human heart have?",
    'options': ['2', '3', '4', '5'],
    'correctIndex': 2,
    'explanation': "The human heart has four chambers.",
  },
  {
    'subject': 'Biology',
    'year': 2020,
    'question': "Which organ is primarily responsible for filtering blood?",
    'options': ['Liver', 'Kidney', 'Lungs', 'Pancreas'],
    'correctIndex': 1,
    'explanation': "The kidneys filter waste from the blood.",
  },
  {
    'subject': 'Biology',
    'year': 2024,
    'question': "What is the basic unit of heredity?",
    'options': ['Cell', 'Chromosome', 'Gene', 'Protein'],
    'correctIndex': 2,
    'explanation': "Genes are the basic units of heredity.",
  },

  // ---------------- Government ----------------
  {
    'subject': 'Government',
    'year': 2021,
    'question': "What type of government does Nigeria practice?",
    'options': ['Monarchy', 'Federal Republic', 'Unitary state', 'Confederation'],
    'correctIndex': 1,
    'explanation': "Nigeria operates as a Federal Republic.",
  },
  {
    'subject': 'Government',
    'year': 2022,
    'question': "How many arms of government are there typically?",
    'options': ['1', '2', '3', '4'],
    'correctIndex': 2,
    'explanation': "The three arms are the Executive, Legislature, and Judiciary.",
  },
  {
    'subject': 'Government',
    'year': 2019,
    'question': "What is the term of office for a Nigerian President?",
    'options': ['3 years', '4 years', '5 years', '6 years'],
    'correctIndex': 1,
    'explanation': "A Nigerian President serves a 4-year term per cycle.",
  },
  {
    'subject': 'Government',
    'year': 2023,
    'question': "What is the principle of separation of powers meant to prevent?",
    'options': ['Economic growth', 'Abuse of power', 'International trade', 'Population growth'],
    'correctIndex': 1,
    'explanation': "Separation of powers prevents concentration and abuse of power.",
  },
  {
    'subject': 'Government',
    'year': 2020,
    'question': "Who is the head of the Judiciary in Nigeria?",
    'options': ['The President', 'The Senate President', 'Chief Justice of Nigeria', 'The Speaker'],
    'correctIndex': 2,
    'explanation': "The Chief Justice of Nigeria heads the judicial arm.",
  },
  {
    'subject': 'Government',
    'year': 2024,
    'question': "Which body is responsible for making laws in Nigeria?",
    'options': ['Executive', 'Legislature', 'Judiciary', 'Civil Service'],
    'correctIndex': 1,
    'explanation': "The Legislature (National Assembly) makes laws.",
  },

  // ---------------- Economics ----------------
  {
    'subject': 'Economics',
    'year': 2021,
    'question': "What does GDP stand for?",
    'options': ['General Domestic Product', 'Gross Domestic Product', 'Gross Development Plan', 'General Development Product'],
    'correctIndex': 1,
    'explanation': "GDP stands for Gross Domestic Product.",
  },
  {
    'subject': 'Economics',
    'year': 2022,
    'question': "What is the study of how individuals and firms make choices called?",
    'options': ['Macroeconomics', 'Microeconomics', 'Sociology', 'Statistics'],
    'correctIndex': 1,
    'explanation': "Microeconomics studies individual and firm-level decision making.",
  },
  {
    'subject': 'Economics',
    'year': 2019,
    'question': "What term describes a persistent rise in general price levels?",
    'options': ['Deflation', 'Inflation', 'Recession', 'Depression'],
    'correctIndex': 1,
    'explanation': "Inflation is a sustained rise in prices.",
  },
  {
    'subject': 'Economics',
    'year': 2023,
    'question': "What is the law of demand?",
    'options': [
      'Price and quantity demanded move in the same direction',
      'Price and quantity demanded move in opposite directions',
      'Demand is unaffected by price',
      'Supply determines demand'
    ],
    'correctIndex': 1,
    'explanation': "As price rises, quantity demanded typically falls, and vice versa.",
  },
  {
    'subject': 'Economics',
    'year': 2020,
    'question': "What is a monopoly?",
    'options': [
      'Many sellers, one buyer',
      'A market with a single seller',
      'A market with two sellers',
      'A market with free entry'
    ],
    'correctIndex': 1,
    'explanation': "A monopoly exists when one seller dominates the entire market.",
  },
  {
    'subject': 'Economics',
    'year': 2024,
    'question': "Which sector does agriculture belong to?",
    'options': ['Primary sector', 'Secondary sector', 'Tertiary sector', 'Quaternary sector'],
    'correctIndex': 0,
    'explanation': "Agriculture is part of the primary sector, extracting raw materials.",
  },

  // ---------------- Literature ----------------
  {
    'subject': 'Literature',
    'year': 2021,
    'question': "Who wrote 'Things Fall Apart'?",
    'options': ['Wole Soyinka', 'Chinua Achebe', 'Chimamanda Adichie', 'Ben Okri'],
    'correctIndex': 1,
    'explanation': "'Things Fall Apart' was written by Chinua Achebe.",
  },
  {
    'subject': 'Literature',
    'year': 2022,
    'question': "What is a 'protagonist'?",
    'options': ['The villain of a story', 'The main character', 'The setting', 'The narrator only'],
    'correctIndex': 1,
    'explanation': "The protagonist is the central character of a story.",
  },
  {
    'subject': 'Literature',
    'year': 2019,
    'question': "What literary device compares two unlike things using 'like' or 'as'?",
    'options': ['Metaphor', 'Simile', 'Personification', 'Irony'],
    'correctIndex': 1,
    'explanation': "A simile uses 'like' or 'as' to compare things.",
  },
  {
    'subject': 'Literature',
    'year': 2023,
    'question': "What is the term for the time and place a story occurs?",
    'options': ['Plot', 'Theme', 'Setting', 'Climax'],
    'correctIndex': 2,
    'explanation': "Setting refers to the time and place of a narrative.",
  },
  {
    'subject': 'Literature',
    'year': 2020,
    'question': "What is a 'soliloquy'?",
    'options': [
      'A conversation between two characters',
      'A speech a character makes alone, revealing inner thoughts',
      'The moral of a story',
      'A rhyming poem'
    ],
    'correctIndex': 1,
    'explanation': "A soliloquy is a character speaking their thoughts aloud, alone.",
  },
  {
    'subject': 'Literature',
    'year': 2024,
    'question': "Who wrote the play 'Death and the King's Horseman'?",
    'options': ['Chinua Achebe', 'Wole Soyinka', 'J.P. Clark', 'Zulu Sofola'],
    'correctIndex': 1,
    'explanation': "Wole Soyinka wrote 'Death and the King's Horseman'.",
  },

  // ---------------- CRS ----------------
  {
    'subject': 'CRS',
    'year': 2021,
    'question': "Who is regarded as the father of faith in Christianity?",
    'options': ['Moses', 'Abraham', 'David', 'Noah'],
    'correctIndex': 1,
    'explanation': "Abraham is called the father of faith.",
  },
  {
    'subject': 'CRS',
    'year': 2022,
    'question': "How many books are in the New Testament?",
    'options': ['27', '39', '66', '12'],
    'correctIndex': 0,
    'explanation': "The New Testament contains 27 books.",
  },
  {
    'subject': 'CRS',
    'year': 2019,
    'question': "Who betrayed Jesus Christ?",
    'options': ['Peter', 'John', 'Judas Iscariot', 'Thomas'],
    'correctIndex': 2,
    'explanation': "Judas Iscariot betrayed Jesus for thirty pieces of silver.",
  },
  {
    'subject': 'CRS',
    'year': 2023,
    'question': "On which mountain did Moses receive the Ten Commandments?",
    'options': ['Mount Zion', 'Mount Sinai', 'Mount Carmel', 'Mount Ararat'],
    'correctIndex': 1,
    'explanation': "Moses received the Ten Commandments on Mount Sinai.",
  },
  {
    'subject': 'CRS',
    'year': 2020,
    'question': "Who was thrown into the lion's den but survived?",
    'options': ['Daniel', 'Jonah', 'Elijah', 'Samuel'],
    'correctIndex': 0,
    'explanation': "Daniel survived the lion's den unharmed.",
  },
  {
    'subject': 'CRS',
    'year': 2024,
    'question': "What is the first book of the Bible?",
    'options': ['Exodus', 'Genesis', 'Leviticus', 'Numbers'],
    'correctIndex': 1,
    'explanation': "Genesis is the first book of the Bible.",
  },

  // ---------------- Geography ----------------
  {
    'subject': 'Geography',
    'year': 2021,
    'question': "What is the largest continent by land area?",
    'options': ['Africa', 'Asia', 'North America', 'Europe'],
    'correctIndex': 1,
    'explanation': "Asia is the largest continent by land area.",
  },
  {
    'subject': 'Geography',
    'year': 2022,
    'question': "Which river is the longest in Africa?",
    'options': ['Niger River', 'Congo River', 'Nile River', 'Zambezi River'],
    'correctIndex': 2,
    'explanation': "The Nile River is the longest river in Africa.",
  },
  {
    'subject': 'Geography',
    'year': 2019,
    'question': "What causes day and night?",
    'options': [
      "The Earth's revolution around the sun",
      "The Earth's rotation on its axis",
      'The Moon orbiting Earth',
      'Seasonal changes'
    ],
    'correctIndex': 1,
    'explanation': "Day and night are caused by the Earth's rotation on its axis.",
  },
  {
    'subject': 'Geography',
    'year': 2023,
    'question': "What type of rock is formed from cooled magma or lava?",
    'options': ['Sedimentary', 'Metamorphic', 'Igneous', 'Organic'],
    'correctIndex': 2,
    'explanation': "Igneous rock forms from cooled magma or lava.",
  },
  {
    'subject': 'Geography',
    'year': 2020,
    'question': "Which layer of the Earth do we live on?",
    'options': ['Core', 'Mantle', 'Crust', 'Outer core'],
    'correctIndex': 2,
    'explanation': "Humans live on the Earth's crust, the outermost layer.",
  },
  {
    'subject': 'Geography',
    'year': 2024,
    'question': "What is the term for a permanent settlement with a large population and administrative functions?",
    'options': ['Village', 'City', 'Hamlet', 'Farmstead'],
    'correctIndex': 1,
    'explanation': "A city is a large permanent settlement with administrative functions.",
  },
];
